# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('spreading_basin', 'Spreading Basin'), ('injection_well', 'Injection Well'), ('streambed', 'Streambed'), ('asr_well', 'ASR Well')], default='spreading_basin', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('capacity_acre_feet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('proposed', 'Proposed')], default='active', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('measurement_type', models.CharField(choices=[('water_level', 'Water Level'), ('flow_rate', 'Flow Rate'), ('water_quality', 'Water Quality'), ('infiltration_rate', 'Infiltration Rate')], max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recharge_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recharge.rechargesite')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='RechargeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('volume_acre_feet', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.watertype')),
                ('recharge_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recharge.rechargesite')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
