# Generated by Django 5.2.14 on 2026-05-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargesite',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_sites', to='geography.zone'),
        ),
    ]
