# Generated by Django 5.2.14 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_rechargesite_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargesite',
            name='site_type',
            field=models.CharField(choices=[('spreading_basin', 'Spreading Basin'), ('injection_well', 'Injection Well'), ('streambed', 'Streambed'), ('asr_well', 'ASR Well'), ('storage_pond', 'Storage Pond'), ('storage_tank', 'Storage Tank')], default='spreading_basin', max_length=50),
        ),
    ]
