# Generated by Django 5.2.14 on 2026-06-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0006_pointofdiversion_source_flowline'),
        ('recharge', '0003_alter_rechargesite_site_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeSitePOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basin_links', to='surface.pointofdiversion')),
                ('recharge_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_links', to='recharge.rechargesite')),
            ],
            options={
                'unique_together': {('recharge_site', 'point_of_diversion')},
            },
        ),
    ]
