# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('recharge', '0004_rechargesitepod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeEventEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('recharge_site', models.BigIntegerField(blank=True, db_column='recharge_site_id', null=True, verbose_name='recharge site')),
                ('water_type', models.BigIntegerField(blank=True, db_column='water_type_id', null=True, verbose_name='water type')),
                ('id', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('volume_acre_feet', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RechargeMeasurementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('recharge_site', models.BigIntegerField(blank=True, db_column='recharge_site_id', null=True, verbose_name='recharge site')),
                ('id', models.BigIntegerField()),
                ('measurement_date', models.DateTimeField()),
                ('measurement_type', models.CharField(choices=[('water_level', 'Water Level'), ('flow_rate', 'Flow Rate'), ('water_quality', 'Water Quality'), ('infiltration_rate', 'Infiltration Rate')], max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargeevent',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "recharge_rechargeeventevent" ("created_at", "end_date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "source_description", "start_date", "volume_acre_feet", "water_type_id") VALUES (NEW."created_at", NEW."end_date", NEW."id", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recharge_site_id", NEW."source_description", NEW."start_date", NEW."volume_acre_feet", NEW."water_type_id"); RETURN NULL;', hash='b4542f86575165fae5c5b3d880cb76e7f0b892c9', operation='INSERT', pgid='pgtrigger_insert_insert_b8ee7', table='recharge_rechargeevent', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargeevent',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "recharge_rechargeeventevent" ("created_at", "end_date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "source_description", "start_date", "volume_acre_feet", "water_type_id") VALUES (OLD."created_at", OLD."end_date", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."recharge_site_id", OLD."source_description", OLD."start_date", OLD."volume_acre_feet", OLD."water_type_id"); RETURN NULL;', hash='342197020e6693b4d2d772d8080f5ce7c4d8222a', operation='UPDATE', pgid='pgtrigger_before_update_update_7db40', table='recharge_rechargeevent', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargeevent',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "recharge_rechargeeventevent" ("created_at", "end_date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "source_description", "start_date", "volume_acre_feet", "water_type_id") VALUES (NEW."created_at", NEW."end_date", NEW."id", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recharge_site_id", NEW."source_description", NEW."start_date", NEW."volume_acre_feet", NEW."water_type_id"); RETURN NULL;', hash='7e3284391dac523bcbcbf73b9f8de8c4846076c5', operation='UPDATE', pgid='pgtrigger_update_update_832b0', table='recharge_rechargeevent', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargeevent',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "recharge_rechargeeventevent" ("created_at", "end_date", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "source_description", "start_date", "volume_acre_feet", "water_type_id") VALUES (OLD."created_at", OLD."end_date", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recharge_site_id", OLD."source_description", OLD."start_date", OLD."volume_acre_feet", OLD."water_type_id"); RETURN NULL;', hash='7b453870587035cf343a6a4ac29b5c1ee41572e7', operation='DELETE', pgid='pgtrigger_delete_delete_be592', table='recharge_rechargeevent', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargemeasurement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "recharge_rechargemeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "unit", "value") VALUES (NEW."created_at", NEW."id", NEW."measurement_date", NEW."measurement_type", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recharge_site_id", NEW."unit", NEW."value"); RETURN NULL;', hash='d50be1d77ac8b970c90e15920f1ddab53531c949', operation='INSERT', pgid='pgtrigger_insert_insert_b6d03', table='recharge_rechargemeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargemeasurement',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "recharge_rechargemeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "unit", "value") VALUES (OLD."created_at", OLD."id", OLD."measurement_date", OLD."measurement_type", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."recharge_site_id", OLD."unit", OLD."value"); RETURN NULL;', hash='b4c9f4c79cf1eeb2e971c3ca0c6d7b057e754afd', operation='UPDATE', pgid='pgtrigger_before_update_update_19a89', table='recharge_rechargemeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargemeasurement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "recharge_rechargemeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "unit", "value") VALUES (NEW."created_at", NEW."id", NEW."measurement_date", NEW."measurement_type", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recharge_site_id", NEW."unit", NEW."value"); RETURN NULL;', hash='bfa61717aacba4b5ee479fc3308e6bc140dc568c', operation='UPDATE', pgid='pgtrigger_update_update_f8e27', table='recharge_rechargemeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rechargemeasurement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "recharge_rechargemeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recharge_site_id", "unit", "value") VALUES (OLD."created_at", OLD."id", OLD."measurement_date", OLD."measurement_type", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recharge_site_id", OLD."unit", OLD."value"); RETURN NULL;', hash='87a6151886e869682ad7d532c80908a7fca95072', operation='DELETE', pgid='pgtrigger_delete_delete_8afe7', table='recharge_rechargemeasurement', when='AFTER')),
        ),
        migrations.AddField(
            model_name='rechargeeventevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='rechargeeventevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='recharge.rechargeevent'),
        ),
        migrations.AddField(
            model_name='rechargemeasurementevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='rechargemeasurementevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='recharge.rechargemeasurement'),
        ),
    ]
