# Generated by Django 5.2.14 on 2026-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_demonstration_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_recovery_horizon',
            field=models.CharField(choices=[('carry_forward', 'Carry unused water forward as a credit'), ('same_water_year', 'Unused water expires at year-end')], default='carry_forward', help_text="What happens to a district's unused allocation at year-end (agency-wide default; a district may override it).", max_length=16),
        ),
    ]
