# Generated by Django 5.2.15 on 2026-09-17 14:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_siteconfig_default_recovery_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_irrigation_efficiency',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.750'), help_text='Share of delivered water the crop consumes.', max_digits=4),
        ),
    ]
