# Generated by Django 5.2.15 on 2026-09-22 01:06
#
# 146-03 Task 3: the existing SiteConfig row gets diversion_use_type_rule=
# 'drop' and diversion_report_year_rule='water_year' -- the leading shapes'
# answers (the 145-01 memo's J3 and J6/M2), not a measurement of any real
# deployment's own file-reading convention. Both belong to `surface` exactly
# as default_irrigation_efficiency does; nothing reads them until a later
# plan's bulk diversion importer.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_literary_sentence_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='diversion_report_year_rule',
            field=models.CharField(choices=[('water_year', 'Water year (October to September)'), ('calendar_year', 'Calendar year (January to December)'), ('season', 'A single irrigation season each year')], default='water_year', help_text="How a YEAR and MONTH in the state's Water Use Reported file become a calendar month (the memo's J6 and M2).", max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='diversion_use_type_rule',
            field=models.CharField(choices=[('drop', 'Ignore USE rows'), ('returned', 'USE minus DIRECT is the returned volume'), ('as_direct', 'Treat USE as direct use')], default='drop', help_text="What a USE row in the state's Water Use Reported file means here (the memo's J3).", max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='season_start_month',
            field=models.IntegerField(blank=True, help_text="The month (1-12) this deployment's irrigation season starts. Used only when the report year rule above is a season (the memo's J6).", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
