# Generated by Django 5.2.15 on 2026-09-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loss_fractions_and_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='identifier_host',
            field=models.CharField(blank=True, help_text="The host your persistent identifiers are published under. Leave blank to use this site's own address. Set it before registering with Geoconnex so the addresses never change.", max_length=200),
        ),
    ]
