# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_identifier_host'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfigEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('agency_name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=50)),
                ('native_srid', models.IntegerField(default=4326)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('allow_google_oauth', models.BooleanField(default=False)),
                ('demonstration_mode', models.BooleanField(default=False, help_text="When on, every report surface and generated file is stamped 'demonstration — not submittable'. Off for a real agency deployment; the Merced demo seed turns it on.")),
                ('default_irrigation_efficiency', models.DecimalField(decimal_places=3, default=Decimal('0.750'), help_text='Share of delivered water the crop consumes.', max_digits=4)),
                ('default_recovery_horizon', models.CharField(choices=[('carry_forward', 'Carry unused water forward as a credit'), ('same_water_year', 'Unused water expires at year-end')], default='carry_forward', help_text="What happens to a district's unused allocation at year-end (agency-wide default; a district may override it).", max_length=16)),
                ('diversion_use_type_rule', models.CharField(choices=[('drop', 'Ignore USE rows'), ('returned', 'USE minus DIRECT is the returned volume'), ('as_direct', 'Treat USE as direct use')], default='drop', help_text="What a USE row in the state's Water Use Reported file means here (the memo's J3).", max_length=20)),
                ('diversion_report_year_rule', models.CharField(choices=[('water_year', 'Water year (October to September)'), ('calendar_year', 'Calendar year (January to December)'), ('season', 'A single irrigation season each year')], default='water_year', help_text="How a YEAR and MONTH in the state's Water Use Reported file become a calendar month (the memo's J6 and M2).", max_length=20)),
                ('season_start_month', models.IntegerField(blank=True, help_text="The month (1-12) this deployment's irrigation season starts. Used only when the report year rule above is a season (the memo's J6).", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('identifier_host', models.CharField(blank=True, help_text="The host your persistent identifiers are published under. Leave blank to use this site's own address. Set it before registering with Geoconnex so the addresses never change.", max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserUsernameFirstNameLastNameEmailIsActiveIsStaffIsSuperuserAgencyAdminEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('agency_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='37685c3ce2130d67645f581fc5edea75bcbc0f6e', operation='INSERT', pgid='pgtrigger_insert_insert_a59d5', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='16dfea64aa95391874e7a1ae881a1438b73b849d', operation='UPDATE', pgid='pgtrigger_before_update_update_9d026', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='e0a1595b52d524245d3f95288d73abc33f3a6550', operation='UPDATE', pgid='pgtrigger_update_update_5b750', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='2d47a8832cea21c58e202c2e0f442dd76557a02c', operation='DELETE', pgid='pgtrigger_delete_delete_9eae4', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userusernamefirstnamelastnameemailisactiveisstaffissup87b2" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (NEW."agency_admin", NEW."email", NEW."first_name", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."username"); RETURN NULL;', hash='e30c9fedac364e5f0b22ffcf308457c172f9ec2a', operation='INSERT', pgid='pgtrigger_insert_insert_45de6', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."agency_admin" IS DISTINCT FROM (NEW."agency_admin") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "core_userusernamefirstnamelastnameemailisactiveisstaffissup87b2" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (OLD."agency_admin", OLD."email", OLD."first_name", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."username"); RETURN NULL;', hash='a85ff0397dfe4404f5d6bcdbc1e29a7dcf1765a9', operation='UPDATE', pgid='pgtrigger_before_update_update_6bf2a', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."agency_admin" IS DISTINCT FROM (NEW."agency_admin") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "core_userusernamefirstnamelastnameemailisactiveisstaffissup87b2" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (NEW."agency_admin", NEW."email", NEW."first_name", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."username"); RETURN NULL;', hash='bb3ecdb6a2314a9e63c49f004d23b522b793accd', operation='UPDATE', pgid='pgtrigger_update_update_6ccff', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userusernamefirstnamelastnameemailisactiveisstaffissup87b2" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "username") VALUES (OLD."agency_admin", OLD."email", OLD."first_name", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."username"); RETURN NULL;', hash='2fc1b745ba1733bd8b7c7b8db6c03c5f24762470', operation='DELETE', pgid='pgtrigger_delete_delete_1425a', table='core_user', when='AFTER')),
        ),
        migrations.AddField(
            model_name='siteconfigevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='siteconfigevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.siteconfig'),
        ),
        migrations.AddField(
            model_name='userusernamefirstnamelastnameemailisactiveisstaffissuperuseragencyadminevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='userusernamefirstnamelastnameemailisactiveisstaffissuperuseragencyadminevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='username_first_name_last_name_email_is_active_is_staff_is_superuser_agency_admin_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
