# Generated by Django 5.2.15 on 2026-09-24 02:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfigevent_userevent_siteconfig_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='user',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='user',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='Viewer (read only)'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='Viewer (read only)'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userevent" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_only", "username") VALUES (NEW."agency_admin", NEW."email", NEW."first_name", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."read_only", NEW."username"); RETURN NULL;', hash='115d4cbe62b5fd5eb6c3d688b8ef9c9893a64d42', operation='INSERT', pgid='pgtrigger_insert_insert_45de6', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."agency_admin" IS DISTINCT FROM (NEW."agency_admin") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."read_only" IS DISTINCT FROM (NEW."read_only") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "core_userevent" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_only", "username") VALUES (OLD."agency_admin", OLD."email", OLD."first_name", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."read_only", OLD."username"); RETURN NULL;', hash='88c378b3f0b827a11cef1b3d11bd5203db9c93ce', operation='UPDATE', pgid='pgtrigger_before_update_update_6bf2a', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."agency_admin" IS DISTINCT FROM (NEW."agency_admin") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."first_name" IS DISTINCT FROM (NEW."first_name") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."is_staff" IS DISTINCT FROM (NEW."is_staff") OR OLD."is_superuser" IS DISTINCT FROM (NEW."is_superuser") OR OLD."last_name" IS DISTINCT FROM (NEW."last_name") OR OLD."read_only" IS DISTINCT FROM (NEW."read_only") OR OLD."username" IS DISTINCT FROM (NEW."username"))', func='INSERT INTO "core_userevent" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_only", "username") VALUES (NEW."agency_admin", NEW."email", NEW."first_name", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."read_only", NEW."username"); RETURN NULL;', hash='f032246f4efb80ec428406adbed0988fea581b5f', operation='UPDATE', pgid='pgtrigger_update_update_6ccff', table='core_user', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='user',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_userevent" ("agency_admin", "email", "first_name", "is_active", "is_staff", "is_superuser", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "read_only", "username") VALUES (OLD."agency_admin", OLD."email", OLD."first_name", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."read_only", OLD."username"); RETURN NULL;', hash='f9f770fb71b0f38b10efa753c86ec5c4a34e32f2', operation='DELETE', pgid='pgtrigger_delete_delete_1425a', table='core_user', when='AFTER')),
        ),
    ]
