# Generated by Django 5.2.15 on 2026-09-24 21:51

import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_read_only'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='groundwater_efficiency',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.800'), help_text="Divides a field's estimated groundwater consumed to give its estimated groundwater extracted, which is what the allocation is charged; the difference is recorded as deep percolation. 0.80 is the figure the Groundwater Accounting Platform's older Merced Irrigation-Urban flow hard-codes; a 2022 Madera verification measured an area-weighted 0.86 over the crops it compared, 0.46 to 1.59 by unit.", max_digits=4),
        ),
        migrations.AddField(
            model_name='siteconfigevent',
            name='groundwater_efficiency',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.800'), help_text="Divides a field's estimated groundwater consumed to give its estimated groundwater extracted, which is what the allocation is charged; the difference is recorded as deep percolation. 0.80 is the figure the Groundwater Accounting Platform's older Merced Irrigation-Urban flow hard-codes; a 2022 Madera verification measured an area-weighted 0.86 over the crops it compared, 0.46 to 1.59 by unit.", max_digits=4),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."groundwater_efficiency", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='01e958d81a1b2a845d05f92ef9b42ced5fcdd0ce', operation='INSERT', pgid='pgtrigger_insert_insert_a59d5', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."groundwater_efficiency", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='6ec70a998e5ae5c089f64eae3a144078932de717', operation='UPDATE', pgid='pgtrigger_before_update_update_9d026', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."groundwater_efficiency", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='5bc2a6e336890392289d6c65dff502dfc879b62c', operation='UPDATE', pgid='pgtrigger_update_update_5b750', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."groundwater_efficiency", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='f2b57af52f2774111d408ebc769ffea926d7df3e', operation='DELETE', pgid='pgtrigger_delete_delete_9eae4', table='core_siteconfig', when='AFTER')),
        ),
    ]
