# Generated by Django 5.2.15 on 2026-09-28 12:22

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_siteconfig_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='siteconfig',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='over_delivery_leave_behind',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='The share of a credited over-delivery left in the basin rather than credited to the landowner. Read only when the setting above is credited. Default 10%, the Lower Tule convention.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='over_delivery_treatment',
            field=models.CharField(choices=[('not_credited', 'Not credited'), ('credited', 'Credited to the landowner, less a share left in the basin'), ('named_line', 'Its own line, not a credit')], default='not_credited', help_text="What happens to the amount a canal delivery went beyond what its field's crop could use, on the month's calculation: not credited to anyone (today's behavior), credited to the landowner with a share left in the basin, or shown as its own line that is not a credit.", max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfigevent',
            name='over_delivery_leave_behind',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='The share of a credited over-delivery left in the basin rather than credited to the landowner. Read only when the setting above is credited. Default 10%, the Lower Tule convention.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='siteconfigevent',
            name='over_delivery_treatment',
            field=models.CharField(choices=[('not_credited', 'Not credited'), ('credited', 'Credited to the landowner, less a share left in the basin'), ('named_line', 'Its own line, not a credit')], default='not_credited', help_text="What happens to the amount a canal delivery went beyond what its field's crop could use, on the month's calculation: not credited to anyone (today's behavior), credited to the landowner with a share left in the basin, or shown as its own line that is not a credit.", max_length=20),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "over_delivery_leave_behind", "over_delivery_treatment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."groundwater_efficiency", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", NEW."over_delivery_leave_behind", NEW."over_delivery_treatment", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='0f89202e0c76aca1f0f85e570cb8a94a4cdc4d9b', operation='INSERT', pgid='pgtrigger_insert_insert_a59d5', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "over_delivery_leave_behind", "over_delivery_treatment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."groundwater_efficiency", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", OLD."over_delivery_leave_behind", OLD."over_delivery_treatment", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='eae2d1a5e6f2f1ae782939806e1eefe2eb8e4a5f', operation='UPDATE', pgid='pgtrigger_before_update_update_9d026', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "over_delivery_leave_behind", "over_delivery_treatment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (NEW."agency_name", NEW."allow_google_oauth", NEW."contact_email", NEW."contact_phone", NEW."default_irrigation_efficiency", NEW."default_recovery_horizon", NEW."demonstration_mode", NEW."diversion_report_year_rule", NEW."diversion_use_type_rule", NEW."groundwater_efficiency", NEW."id", NEW."identifier_host", NEW."logo", NEW."native_srid", NEW."over_delivery_leave_behind", NEW."over_delivery_treatment", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."season_start_month", NEW."timezone"); RETURN NULL;', hash='d240bcaafa25cc94354ff9a66744c4194b0ebcc2', operation='UPDATE', pgid='pgtrigger_update_update_5b750', table='core_siteconfig', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='siteconfig',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_siteconfigevent" ("agency_name", "allow_google_oauth", "contact_email", "contact_phone", "default_irrigation_efficiency", "default_recovery_horizon", "demonstration_mode", "diversion_report_year_rule", "diversion_use_type_rule", "groundwater_efficiency", "id", "identifier_host", "logo", "native_srid", "over_delivery_leave_behind", "over_delivery_treatment", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "season_start_month", "timezone") VALUES (OLD."agency_name", OLD."allow_google_oauth", OLD."contact_email", OLD."contact_phone", OLD."default_irrigation_efficiency", OLD."default_recovery_horizon", OLD."demonstration_mode", OLD."diversion_report_year_rule", OLD."diversion_use_type_rule", OLD."groundwater_efficiency", OLD."id", OLD."identifier_host", OLD."logo", OLD."native_srid", OLD."over_delivery_leave_behind", OLD."over_delivery_treatment", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."season_start_month", OLD."timezone"); RETURN NULL;', hash='1516749d48f89d6fcbd7e52b8a4c386baf1f07f1', operation='DELETE', pgid='pgtrigger_delete_delete_9eae4', table='core_siteconfig', when='AFTER')),
        ),
    ]
