# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('oauth', 'OAuth'), ('token', 'Token')], default='none', max_length=50)),
                ('sync_interval_hours', models.IntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_staged', models.IntegerField(default=0)),
                ('records_published', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.datasource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_station_id', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_data_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.datasource')),
            ],
            options={
                'unique_together': {('data_source', 'external_station_id')},
            },
        ),
        migrations.CreateModel(
            name='DataRecordStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('observation_date', models.DateTimeField()),
                ('parameter_code', models.CharField(max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('published', 'Published'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='staged', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.datasource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.monitoredstation')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
    ]
