# Generated by Django 5.2.14 on 2026-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0003_datarecordstaging_unique_obs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='openetcache',
            new_name='datasync_op_parcel__8c9892_idx',
            old_name='datasync_op_parcel__a6c8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='openetcache',
            new_name='datasync_op_queried_7f34c2_idx',
            old_name='datasync_op_queried_4f2e1a_idx',
        ),
        migrations.AddField(
            model_name='monitoredstation',
            name='usgs_site_id',
            field=models.CharField(blank=True, help_text='USGS NWIS site number (waterdata.usgs.gov), if this station is also a USGS site.', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoredstation',
            name='wqx_monitoring_location_id',
            field=models.CharField(blank=True, help_text='EPA WQX MonitoringLocationIdentifier (Water Quality Portal).', max_length=50),
        ),
    ]
