# Generated by Django 5.2.15 on 2026-07-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0004_rename_datasync_op_parcel__a6c8d7_idx_datasync_op_parcel__8c9892_idx_and_more'),
        ('parcels', '0006_parcelledger_parcelledger_supply_rows_positive_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='openetcache',
            constraint=models.UniqueConstraint(condition=models.Q(('model_name', '__PENDING__'), _negated=True), fields=('parcel', 'start_date', 'end_date', 'variable', 'model_name'), name='openetcache_one_row_per_parcel_window'),
        ),
    ]
