# Generated by Django 5.2.15 on 2026-07-18 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_reportingperiod_reporting_period_no_overlap'),
        ('parcels', '0005_alter_parcelledger_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parcelledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type__in', ('allocation', 'recharge')), _negated=True), ('amount_acre_feet__gt', 0), _connector='OR'), name='parcelledger_supply_rows_positive'),
        ),
        migrations.AddConstraint(
            model_name='parcelledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type__in', ('meter_reading', 'et_estimate', 'surface_diversion', 'calculated')), _negated=True), ('amount_acre_feet__lte', 0), _connector='OR'), name='parcelledger_usage_rows_non_positive'),
        ),
    ]
