# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_parcelledger_parcelledger_supply_rows_positive_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('parcel_number', models.CharField(max_length=50)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_override', models.BooleanField(default=False, help_text='When checked, area_acres is manually set and will not be auto-calculated from geometry.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelLedgerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('water_type', models.BigIntegerField(blank=True, db_column='water_type_id', null=True, verbose_name='water type')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('created_by', models.BigIntegerField(blank=True, db_column='created_by_id', null=True, verbose_name='created by')),
                ('id', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('amount_acre_feet', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_type', models.CharField(choices=[('meter_reading', 'Meter Reading'), ('et_estimate', 'ET Estimate'), ('manual_entry', 'Manual Entry'), ('csv_import', 'CSV Import'), ('surface_diversion', 'Surface Diversion'), ('recharge', 'Recharge'), ('allocation', 'Allocation'), ('adjustment', 'Adjustment'), ('calculated', 'Calculated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelevent" ("address", "area_acres", "area_override", "created_at", "id", "notes", "owner_name", "parcel_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."address", NEW."area_acres", NEW."area_override", NEW."created_at", NEW."id", NEW."notes", NEW."owner_name", NEW."parcel_number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status"); RETURN NULL;', hash='82d5ad9ed828a7aead3b15b5ea9e8d8ff2b25768', operation='INSERT', pgid='pgtrigger_insert_insert_4b37f', table='parcels_parcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcel',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."address" IS DISTINCT FROM (NEW."address") OR OLD."area_acres" IS DISTINCT FROM (NEW."area_acres") OR OLD."area_override" IS DISTINCT FROM (NEW."area_override") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."owner_name" IS DISTINCT FROM (NEW."owner_name") OR OLD."parcel_number" IS DISTINCT FROM (NEW."parcel_number") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "parcels_parcelevent" ("address", "area_acres", "area_override", "created_at", "id", "notes", "owner_name", "parcel_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (OLD."address", OLD."area_acres", OLD."area_override", OLD."created_at", OLD."id", OLD."notes", OLD."owner_name", OLD."parcel_number", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."status"); RETURN NULL;', hash='f73de4b70907aa0abe0edf23bfe2ad80d84c092c', operation='UPDATE', pgid='pgtrigger_before_update_update_8130a', table='parcels_parcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."address" IS DISTINCT FROM (NEW."address") OR OLD."area_acres" IS DISTINCT FROM (NEW."area_acres") OR OLD."area_override" IS DISTINCT FROM (NEW."area_override") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."owner_name" IS DISTINCT FROM (NEW."owner_name") OR OLD."parcel_number" IS DISTINCT FROM (NEW."parcel_number") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "parcels_parcelevent" ("address", "area_acres", "area_override", "created_at", "id", "notes", "owner_name", "parcel_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (NEW."address", NEW."area_acres", NEW."area_override", NEW."created_at", NEW."id", NEW."notes", NEW."owner_name", NEW."parcel_number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;', hash='069facb2c86d12ddd9563ed4297c8bd49330ecbd', operation='UPDATE', pgid='pgtrigger_update_update_3d55a', table='parcels_parcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelevent" ("address", "area_acres", "area_override", "created_at", "id", "notes", "owner_name", "parcel_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (OLD."address", OLD."area_acres", OLD."area_override", OLD."created_at", OLD."id", OLD."notes", OLD."owner_name", OLD."parcel_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status"); RETURN NULL;', hash='8039bde6676b93465d94f0c4c4529400d87acb8c', operation='DELETE', pgid='pgtrigger_delete_delete_b108c', table='parcels_parcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='20d45bb2e135d59efe0b1cdfd59d62cafb5b0371', operation='INSERT', pgid='pgtrigger_insert_insert_a3df4', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='bc0095587f5b9f45e489385b6e68b5e17794573b', operation='UPDATE', pgid='pgtrigger_before_update_update_75d87', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='f617d593ebefd74b927db80c5c8e2276f761bc24', operation='UPDATE', pgid='pgtrigger_update_update_eb9b8', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='3af70c58a9559d7b24061a170b9803b2443e3167', operation='DELETE', pgid='pgtrigger_delete_delete_fe28b', table='parcels_parcelledger', when='AFTER')),
        ),
        migrations.AddField(
            model_name='parcelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='parcelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='parcelledgerevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='parcelledgerevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='parcels.parcelledger'),
        ),
    ]
