# Generated by Django 5.2.15 on 2026-09-24 03:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_parcelevent_parcelledgerevent_parcel_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='finalized_period_lock', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE locked_name text;', func='IF TG_OP IN (\'UPDATE\', \'DELETE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((OLD."effective_date") BETWEEN p.start_date AND p.end_date OR p.id = OLD."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP IN (\'INSERT\', \'UPDATE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((NEW."effective_date") BETWEEN p.start_date AND p.end_date OR p.id = NEW."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP = \'DELETE\' THEN RETURN OLD; END IF; RETURN NEW;', hash='1b7992dea751656bb161bc2dd70a5602d33978a8', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_finalized_period_lock_3d8d8', table='parcels_parcelledger', when='BEFORE')),
        ),
    ]
