# Generated by Django 5.2.15 on 2026-10-06 12:07, then hand-edited: the data step below.

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


# The three tails the canal split has ever written into a split row's
# description. COPIED here on purpose (149-01): a migration must keep meaning
# what it meant on the day it ran, so it never imports the live
# accounting.ledger_words constants, which a later wording ruling may change.
_SPLIT_TAILS = (
    # DELIVERY_SHARE_BY_USE
    "divided up from the canal total in proportion to each field's crop "
    "water use after rain",
    # LEGACY_DELIVERY_SHARE_BY_USE (written before 2026-09-28)
    "split among the use areas it serves by each one's estimated use for the "
    "month",
    # DELIVERY_SHARE_BY_FIXED
    "the fixed share on file",
)


def mark_existing_split_rows(ParcelLedger):
    """Mark every existing surface_diversion row carrying a split tail.

    Rows the canal split wrote are told apart from a hand-entered or imported
    delivery by the tail of their description; from here on the column says it.
    Returns the number of rows marked.
    """
    tail = models.Q()
    for text in _SPLIT_TAILS:
        tail |= models.Q(description__contains=text)
    return ParcelLedger.objects.filter(source_type="surface_diversion").filter(
        tail
    ).update(divided_from_headgate=True)


def mark_split_rows(apps, schema_editor):
    ParcelLedger = apps.get_model("parcels", "ParcelLedger")
    # A backfill is not a change a person made: the finalized-period lock would
    # refuse it on a closed year's rows (the history triggers are already
    # dropped at this point in the operation list). Switch the table's user
    # triggers off for the one UPDATE and back on straight after.
    schema_editor.execute("ALTER TABLE parcels_parcelledger DISABLE TRIGGER USER")
    try:
        mark_existing_split_rows(ParcelLedger)
    finally:
        schema_editor.execute("ALTER TABLE parcels_parcelledger ENABLE TRIGGER USER")


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_parcelledger_finalized_period_lock'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='parcelledger',
            name='divided_from_headgate',
            field=models.BooleanField(default=False, help_text="Written by the canal split: this field's share of a headgate total. Replaced whenever that headgate's month is recalculated. Unticked rows are the field's own recorded delivery and are never replaced by the split."),
        ),
        migrations.AddField(
            model_name='parcelledgerevent',
            name='divided_from_headgate',
            field=models.BooleanField(default=False, help_text="Written by the canal split: this field's share of a headgate total. Replaced whenever that headgate's month is recalculated. Unticked rows are the field's own recorded delivery and are never replaced by the split."),
        ),
        migrations.RunPython(mark_split_rows, migrations.RunPython.noop),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."divided_from_headgate", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='2632078b3f8f5bbdaafcc40770044a92b127d4db', operation='INSERT', pgid='pgtrigger_insert_insert_a3df4', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."divided_from_headgate", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='99325fe85c9ea772f503a5d9459bfadb40fa3ed5', operation='UPDATE', pgid='pgtrigger_before_update_update_75d87', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."divided_from_headgate", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='5483ac84c963583bcfe483eaef1004fd7dda0b5a', operation='UPDATE', pgid='pgtrigger_update_update_eb9b8', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."divided_from_headgate", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='de572ff2e6b704705e349b3bb6494d7df8f6edc5', operation='DELETE', pgid='pgtrigger_delete_delete_fe28b', table='parcels_parcelledger', when='AFTER')),
        ),
    ]
