# Generated by Django 5.2.15 on 2026-10-06 12:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_parcelledger_divided_from_headgate'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='parcelledger',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='parcelledger',
            name='divided_from_point_pk',
            field=models.PositiveIntegerField(blank=True, help_text="On a canal split row, the point of diversion whose headgate total it is a share of, so recalculating one point never replaces another point's shares on a field both serve. Blank on a field's own recorded delivery, and on split rows written before 149-01.", null=True),
        ),
        migrations.AddField(
            model_name='parcelledgerevent',
            name='divided_from_point_pk',
            field=models.PositiveIntegerField(blank=True, help_text="On a canal split row, the point of diversion whose headgate total it is a share of, so recalculating one point never replaces another point's shares on a field both serve. Blank on a field's own recorded delivery, and on split rows written before 149-01.", null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "divided_from_point_pk", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."divided_from_headgate", NEW."divided_from_point_pk", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='c94d91554c96f17784216caa3bc4534e8ec24222', operation='INSERT', pgid='pgtrigger_insert_insert_a3df4', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "divided_from_point_pk", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."divided_from_headgate", OLD."divided_from_point_pk", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='eec07f97388c218f1b55fcf1a28925f333ed30f9', operation='UPDATE', pgid='pgtrigger_before_update_update_75d87', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "divided_from_point_pk", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."created_by_id", NEW."description", NEW."divided_from_headgate", NEW."divided_from_point_pk", NEW."effective_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reporting_period_id", NEW."source_type", NEW."transaction_date", NEW."water_type_id"); RETURN NULL;', hash='92f7226446b282347354c3a30bd49a9e26d725b3', operation='UPDATE', pgid='pgtrigger_update_update_eb9b8', table='parcels_parcelledger', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelledger',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "parcels_parcelledgerevent" ("amount_acre_feet", "created_at", "created_by_id", "description", "divided_from_headgate", "divided_from_point_pk", "effective_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "source_type", "transaction_date", "water_type_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."created_by_id", OLD."description", OLD."divided_from_headgate", OLD."divided_from_point_pk", OLD."effective_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reporting_period_id", OLD."source_type", OLD."transaction_date", OLD."water_type_id"); RETURN NULL;', hash='f2d94a4413e134be930158a6f2146357e7cfe17f', operation='DELETE', pgid='pgtrigger_delete_delete_fe28b', table='parcels_parcelledger', when='AFTER')),
        ),
    ]
