# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_sq_miles', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'boundaries',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('zone_type', models.CharField(blank=True, choices=[('management_area', 'Management Area'), ('subbasin', 'Subbasin'), ('custom', 'Custom')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='geography.boundary')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='groups', to='geography.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_zones', to='parcels.parcel')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_zones', to='geography.zone')),
            ],
            options={
                'unique_together': {('parcel', 'zone')},
            },
        ),
    ]
