# Generated by Django 5.2.14 on 2026-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_flowline'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='basin_code',
            field=models.CharField(blank=True, help_text='DWR Bulletin 118 basin/subbasin number, e.g. "5-022.11" (Kaweah). The basin identity WaDE/AB1755 expect.', max_length=20),
        ),
        migrations.AddField(
            model_name='boundary',
            name='huc',
            field=models.CharField(blank=True, help_text='Optional USGS Hydrologic Unit Code (HUC) for the area.', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='basin_code',
            field=models.CharField(blank=True, help_text='DWR Bulletin 118 subbasin number this zone maps to, e.g. "5-022.11".', max_length=20),
        ),
    ]
