# Generated by Django 5.2.15 on 2026-07-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_zone_recovery_horizon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='basin_code',
            field=models.CharField(blank=True, help_text='DWR Bulletin 118 basin/subbasin number, e.g. "5-022.04" (Merced Subbasin). The basin identity WaDE/AB1755 expect.', max_length=20),
        ),
    ]
