# Generated by Django 5.2.15 on 2026-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_alter_boundary_basin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='legal_basis',
            field=models.TextField(blank=True, help_text='The stated legal basis for the rule above. Required when the flag is set.'),
        ),
        migrations.AddField(
            model_name='zone',
            name='subsurface_supply_is_diversion',
            field=models.BooleanField(default=False, help_text='In this zone, water reaching a crop from below is a diversion under a stated legal basis (the Delta case).'),
        ),
    ]
