# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_zone_jurisdiction'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelZoneEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('zone', models.BigIntegerField(blank=True, db_column='zone_id', null=True, verbose_name='zone')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('boundary', models.BigIntegerField(blank=True, db_column='boundary_id', null=True, verbose_name='boundary')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('zone_type', models.CharField(blank=True, choices=[('management_area', 'Management Area'), ('subbasin', 'Subbasin'), ('custom', 'Custom')], max_length=50)),
                ('basin_code', models.CharField(blank=True, help_text='DWR Bulletin 118 subbasin number this zone maps to, e.g. "5-022.11".', max_length=20)),
                ('recovery_horizon', models.CharField(blank=True, choices=[('carry_forward', 'Carry unused water forward as a credit'), ('same_water_year', 'Unused water expires at year-end')], help_text='Override the agency default for this district. Blank = use the agency default.', max_length=16, null=True)),
                ('subsurface_supply_is_diversion', models.BooleanField(default=False, help_text='In this zone, water reaching a crop from below is a diversion under a stated legal basis (the Delta case).')),
                ('legal_basis', models.TextField(blank=True, help_text='The stated legal basis for the rule above. Required when the flag is set.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelzone',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "geography_parcelzoneevent" ("id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "zone_id") VALUES (NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."zone_id"); RETURN NULL;', hash='bbf2f8ffbd2036476f04c554e2dd9c7e1d18a47e', operation='INSERT', pgid='pgtrigger_insert_insert_b5257', table='geography_parcelzone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelzone',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "geography_parcelzoneevent" ("id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "zone_id") VALUES (OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."zone_id"); RETURN NULL;', hash='d9592a9c99b22a3ed28ffd0f927a61d268b864e9', operation='UPDATE', pgid='pgtrigger_before_update_update_f12d0', table='geography_parcelzone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelzone',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "geography_parcelzoneevent" ("id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "zone_id") VALUES (NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."zone_id"); RETURN NULL;', hash='2e84cda7a1a755cce0d95c431b541f8a06402bcf', operation='UPDATE', pgid='pgtrigger_update_update_02c18', table='geography_parcelzone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelzone',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "geography_parcelzoneevent" ("id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "zone_id") VALUES (OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."zone_id"); RETURN NULL;', hash='d130c49bc3551860d1533ec5e446278180bfe612', operation='DELETE', pgid='pgtrigger_delete_delete_e0dd3', table='geography_parcelzone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='zone',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "geography_zoneevent" ("basin_code", "boundary_id", "created_at", "description", "id", "legal_basis", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recovery_horizon", "subsurface_supply_is_diversion", "zone_type") VALUES (NEW."basin_code", NEW."boundary_id", NEW."created_at", NEW."description", NEW."id", NEW."legal_basis", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recovery_horizon", NEW."subsurface_supply_is_diversion", NEW."zone_type"); RETURN NULL;', hash='8db2fea83ac6b22c7581b85f3e2276850c293b37', operation='INSERT', pgid='pgtrigger_insert_insert_e2e5e', table='geography_zone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='zone',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."basin_code" IS DISTINCT FROM (NEW."basin_code") OR OLD."boundary_id" IS DISTINCT FROM (NEW."boundary_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."legal_basis" IS DISTINCT FROM (NEW."legal_basis") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."recovery_horizon" IS DISTINCT FROM (NEW."recovery_horizon") OR OLD."subsurface_supply_is_diversion" IS DISTINCT FROM (NEW."subsurface_supply_is_diversion") OR OLD."zone_type" IS DISTINCT FROM (NEW."zone_type"))', func='INSERT INTO "geography_zoneevent" ("basin_code", "boundary_id", "created_at", "description", "id", "legal_basis", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recovery_horizon", "subsurface_supply_is_diversion", "zone_type") VALUES (OLD."basin_code", OLD."boundary_id", OLD."created_at", OLD."description", OLD."id", OLD."legal_basis", OLD."name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."recovery_horizon", OLD."subsurface_supply_is_diversion", OLD."zone_type"); RETURN NULL;', hash='b283618f89800820e30dacf189defde98866cf81', operation='UPDATE', pgid='pgtrigger_before_update_update_ae2ef', table='geography_zone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='zone',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."basin_code" IS DISTINCT FROM (NEW."basin_code") OR OLD."boundary_id" IS DISTINCT FROM (NEW."boundary_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."legal_basis" IS DISTINCT FROM (NEW."legal_basis") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."recovery_horizon" IS DISTINCT FROM (NEW."recovery_horizon") OR OLD."subsurface_supply_is_diversion" IS DISTINCT FROM (NEW."subsurface_supply_is_diversion") OR OLD."zone_type" IS DISTINCT FROM (NEW."zone_type"))', func='INSERT INTO "geography_zoneevent" ("basin_code", "boundary_id", "created_at", "description", "id", "legal_basis", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recovery_horizon", "subsurface_supply_is_diversion", "zone_type") VALUES (NEW."basin_code", NEW."boundary_id", NEW."created_at", NEW."description", NEW."id", NEW."legal_basis", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recovery_horizon", NEW."subsurface_supply_is_diversion", NEW."zone_type"); RETURN NULL;', hash='bd0ae057feaa14c0a5030c64cce0a2421b7c81a1', operation='UPDATE', pgid='pgtrigger_update_update_6c079', table='geography_zone', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='zone',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "geography_zoneevent" ("basin_code", "boundary_id", "created_at", "description", "id", "legal_basis", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recovery_horizon", "subsurface_supply_is_diversion", "zone_type") VALUES (OLD."basin_code", OLD."boundary_id", OLD."created_at", OLD."description", OLD."id", OLD."legal_basis", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recovery_horizon", OLD."subsurface_supply_is_diversion", OLD."zone_type"); RETURN NULL;', hash='798227ac093bed984a0d6acfe8e77be9c86d53ba', operation='DELETE', pgid='pgtrigger_delete_delete_2f6ba', table='geography_zone', when='AFTER')),
        ),
        migrations.AddField(
            model_name='parcelzoneevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='parcelzoneevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='geography.parcelzone'),
        ),
        migrations.AddField(
            model_name='zoneevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='zoneevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='geography.zone'),
        ),
    ]
