# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('gears_by_well', 'GEARS by Well'), ('gears_by_et', 'GEARS by ET'), ('calwatrs_a1', 'CalWATRS A1'), ('calwatrs_a2', 'CalWATRS A2'), ('email_json', 'Email JSON')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('generated_file', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.reportingperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.reporttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_field', models.CharField(max_length=100)),
                ('external_field', models.CharField(max_length=100)),
                ('transform', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reporttemplate')),
            ],
            options={
                'unique_together': {('report_template', 'internal_field')},
            },
        ),
    ]
