# Generated by Django 5.2.14 on 2026-05-30 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_flowline'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubmission',
            name='reviewer_notes',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='certified_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded certifying this filing in the state portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='filed_at',
            field=models.DateTimeField(blank=True, help_text='When the user recorded that they filed this in the state portal.', null=True),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="Internal GSA/agency sign-off notes. Not a Water Board reviewer's notes."),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='state_confirmation_number',
            field=models.CharField(blank=True, help_text='Confirmation number the state portal returned to the user after filing.', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('internally_approved', 'Internally Approved'), ('exported', 'Exported'), ('filed', 'Filed at State')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('gears_by_well', 'GEARS by Well'), ('gears_by_et', 'GEARS by ET'), ('calwatrs_a1', 'CalWATRS A1'), ('calwatrs_a2', 'CalWATRS A2')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ReportingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(help_text='Legal name of the agency as it appears on state filings.', max_length=255)),
                ('gears_correspondence_id', models.CharField(blank=True, help_text='Correspondence ID mailed by SWRCB to bind the GEARS account. Supplied by the agency; OpenH2O does not issue or fetch it.', max_length=100)),
                ('certifier_name', models.CharField(blank=True, help_text='Person who certifies filings in the state portal under penalty of perjury.', max_length=200)),
                ('certifier_title', models.CharField(blank=True, max_length=200)),
                ('certifier_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary', models.OneToOneField(blank=True, help_text="The geography.Boundary representing this agency's area.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_profile', to='geography.boundary')),
            ],
        ),
    ]
