# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('reporting', '0003_reportsubmission_prefill_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmissionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('report_template', models.BigIntegerField(blank=True, db_column='report_template_id', null=True, verbose_name='report template')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('certified_by', models.BigIntegerField(blank=True, db_column='certified_by_id', null=True, verbose_name='certified by')),
                ('id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internally_approved', 'Internally Approved'), ('exported', 'Exported'), ('filed', 'Filed at State')], default='draft', max_length=20)),
                ('generated_file', models.CharField(blank=True, max_length=500)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, help_text='When the user recorded that they filed this in the state portal.', null=True)),
                ('state_confirmation_number', models.CharField(blank=True, help_text='Confirmation number the state portal returned to the user after filing.', max_length=100)),
                ('internal_notes', models.TextField(blank=True, help_text="Internal GSA/agency sign-off notes. Not a Water Board reviewer's notes.")),
                ('prefill_overrides', models.JSONField(blank=True, default=dict, help_text="User-edited OpenET pre-fill values, keyed by entity+month (e.g. 'well:12:2024-03'). These are the agency's reviewed figures for data entry; they are NOT written back to the parcel ledger, so they never double-count against the et_estimate entries the generators read.")),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportsubmission',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "reporting_reportsubmissionevent" ("certified_by_id", "created_at", "filed_at", "generated_at", "generated_file", "id", "internal_notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefill_overrides", "report_template_id", "reporting_period_id", "state_confirmation_number", "status", "validation_warnings") VALUES (NEW."certified_by_id", NEW."created_at", NEW."filed_at", NEW."generated_at", NEW."generated_file", NEW."id", NEW."internal_notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."prefill_overrides", NEW."report_template_id", NEW."reporting_period_id", NEW."state_confirmation_number", NEW."status", NEW."validation_warnings"); RETURN NULL;', hash='bcd19c7e1052ccccdd0622e0e8603f2c97cbd824', operation='INSERT', pgid='pgtrigger_insert_insert_ed4cc', table='reporting_reportsubmission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportsubmission',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."certified_by_id" IS DISTINCT FROM (NEW."certified_by_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."filed_at" IS DISTINCT FROM (NEW."filed_at") OR OLD."generated_at" IS DISTINCT FROM (NEW."generated_at") OR OLD."generated_file" IS DISTINCT FROM (NEW."generated_file") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."internal_notes" IS DISTINCT FROM (NEW."internal_notes") OR OLD."prefill_overrides" IS DISTINCT FROM (NEW."prefill_overrides") OR OLD."report_template_id" IS DISTINCT FROM (NEW."report_template_id") OR OLD."reporting_period_id" IS DISTINCT FROM (NEW."reporting_period_id") OR OLD."state_confirmation_number" IS DISTINCT FROM (NEW."state_confirmation_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."validation_warnings" IS DISTINCT FROM (NEW."validation_warnings"))', func='INSERT INTO "reporting_reportsubmissionevent" ("certified_by_id", "created_at", "filed_at", "generated_at", "generated_file", "id", "internal_notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefill_overrides", "report_template_id", "reporting_period_id", "state_confirmation_number", "status", "validation_warnings") VALUES (OLD."certified_by_id", OLD."created_at", OLD."filed_at", OLD."generated_at", OLD."generated_file", OLD."id", OLD."internal_notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."prefill_overrides", OLD."report_template_id", OLD."reporting_period_id", OLD."state_confirmation_number", OLD."status", OLD."validation_warnings"); RETURN NULL;', hash='9cf62b399225713ca0d37bc5774bfbab69581006', operation='UPDATE', pgid='pgtrigger_before_update_update_0bd37', table='reporting_reportsubmission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportsubmission',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."certified_by_id" IS DISTINCT FROM (NEW."certified_by_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."filed_at" IS DISTINCT FROM (NEW."filed_at") OR OLD."generated_at" IS DISTINCT FROM (NEW."generated_at") OR OLD."generated_file" IS DISTINCT FROM (NEW."generated_file") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."internal_notes" IS DISTINCT FROM (NEW."internal_notes") OR OLD."prefill_overrides" IS DISTINCT FROM (NEW."prefill_overrides") OR OLD."report_template_id" IS DISTINCT FROM (NEW."report_template_id") OR OLD."reporting_period_id" IS DISTINCT FROM (NEW."reporting_period_id") OR OLD."state_confirmation_number" IS DISTINCT FROM (NEW."state_confirmation_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."validation_warnings" IS DISTINCT FROM (NEW."validation_warnings"))', func='INSERT INTO "reporting_reportsubmissionevent" ("certified_by_id", "created_at", "filed_at", "generated_at", "generated_file", "id", "internal_notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefill_overrides", "report_template_id", "reporting_period_id", "state_confirmation_number", "status", "validation_warnings") VALUES (NEW."certified_by_id", NEW."created_at", NEW."filed_at", NEW."generated_at", NEW."generated_file", NEW."id", NEW."internal_notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."prefill_overrides", NEW."report_template_id", NEW."reporting_period_id", NEW."state_confirmation_number", NEW."status", NEW."validation_warnings"); RETURN NULL;', hash='ca4d8f7bddc4f90591e8e3fb1a3a344eb0b50796', operation='UPDATE', pgid='pgtrigger_update_update_2127b', table='reporting_reportsubmission', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportsubmission',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "reporting_reportsubmissionevent" ("certified_by_id", "created_at", "filed_at", "generated_at", "generated_file", "id", "internal_notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "prefill_overrides", "report_template_id", "reporting_period_id", "state_confirmation_number", "status", "validation_warnings") VALUES (OLD."certified_by_id", OLD."created_at", OLD."filed_at", OLD."generated_at", OLD."generated_file", OLD."id", OLD."internal_notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."prefill_overrides", OLD."report_template_id", OLD."reporting_period_id", OLD."state_confirmation_number", OLD."status", OLD."validation_warnings"); RETURN NULL;', hash='1e83ef1451401fe5750ab3194c01be3558a7288c', operation='DELETE', pgid='pgtrigger_delete_delete_dc58f', table='reporting_reportsubmission', when='AFTER')),
        ),
        migrations.AddField(
            model_name='reportsubmissionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='reportsubmissionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='reporting.reportsubmission'),
        ),
    ]
