# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtailmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('watershed', models.CharField(blank=True, max_length=200)),
                ('priority_date_cutoff', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('rescinded', 'Rescinded')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_id', models.CharField(max_length=50, unique=True)),
                ('holder_name', models.CharField(max_length=200)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('face_value_acre_feet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('curtailed', 'Curtailed'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterRightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfDiversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stream_name', models.CharField(blank=True, max_length=200)),
                ('max_rate_cfs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('water_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.waterright')),
            ],
        ),
        migrations.AddField(
            model_name='waterright',
            name='right_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surface.waterrighttype'),
        ),
        migrations.CreateModel(
            name='DiversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('volume_acre_feet', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_flow_rate_cfs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('diversion_type', models.CharField(choices=[('direct_use', 'Direct Use'), ('to_storage', 'To Storage')], default='direct_use', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.reportingperiod')),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.pointofdiversion')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('point_of_diversion', 'month', 'diversion_type')},
            },
        ),
    ]
