# Generated by Django 5.2.14 on 2026-05-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('surface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterRightParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_right_parcels', to='parcels.parcel')),
                ('water_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_right_parcels', to='surface.waterright')),
            ],
            options={
                'unique_together': {('water_right', 'parcel')},
            },
        ),
    ]
