# Generated by Django 5.2.14 on 2026-05-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('surface', '0002_waterrightparcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfDiversionParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_parcels', to='parcels.parcel')),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_parcels', to='surface.pointofdiversion')),
            ],
            options={
                'unique_together': {('point_of_diversion', 'parcel')},
            },
        ),
    ]
