# Generated by Django 5.2.14 on 2026-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0004_pointofdiversion_water_right_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterright',
            name='calwatrs_pin',
            field=models.CharField(blank=True, help_text='CalWATRS PIN mailed by SWRCB for this water right. The state issues one PIN per right; supplied by the agency, not fetched by OpenH2O.', max_length=50),
        ),
    ]
