# Generated by Django 5.2.14 on 2026-06-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_flowline'),
        ('surface', '0005_waterright_calwatrs_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofdiversion',
            name='source_flowline',
            field=models.ForeignKey(blank=True, help_text='The real NHD/canal waterway this diversion sits on (provenance). stream_name stays the human-readable eWRIMS label.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diversions', to='geography.flowline'),
        ),
    ]
