# Generated by Django 5.2.14 on 2026-06-06 00:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0006_pointofdiversion_source_flowline'),
    ]

    operations = [
        migrations.AddField(
            model_name='diversionrecord',
            name='returned_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Agency-asserted acre-feet of this diversion returned to the stream (0 = fully consumed; = full volume for non-consumptive / hydropower passthrough).', max_digits=12),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='rediverted_from',
            field=models.ForeignKey(blank=True, help_text='Upstream point of diversion this point re-diverts from (one hop; the return-flow source).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rediversions', to='surface.pointofdiversion'),
        ),
    ]
