# Generated by Django 5.2.15 on 2026-07-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_reportingperiod_reporting_period_no_overlap'),
        ('surface', '0007_diversion_return_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnallocatedDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First of the month this surplus arose in.')),
                ('amount_acre_feet', models.DecimalField(decimal_places=4, help_text='Positive magnitude of delivered water not explained by demand.', max_digits=12)),
                ('delivery_acre_feet', models.DecimalField(decimal_places=4, help_text="The month's total consumed delivery, for context.", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.pointofdiversion')),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.reportingperiod')),
            ],
            options={
                'verbose_name_plural': 'unallocated deliveries',
                'ordering': ['-month', 'point_of_diversion_id'],
                'constraints': [models.UniqueConstraint(fields=('point_of_diversion', 'month'), name='unallocated_delivery_one_per_pod_month'), models.CheckConstraint(condition=models.Q(('amount_acre_feet__gt', 0)), name='unallocated_delivery_amount_positive')],
            },
        ),
    ]
