# Generated by Django 5.2.15 on 2026-09-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_alter_boundary_basin_code'),
        ('surface', '0008_unallocateddelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofdiversion',
            name='source_flowline',
            field=models.ForeignKey(blank=True, help_text='Waterway (NHD or canal) this diversion is on, for provenance. stream_name stays the human-readable eWRIMS label.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diversions', to='geography.flowline'),
        ),
    ]
