# Generated by Django 5.2.15 on 2026-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0009_literary_sentence_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterright',
            name='direct_season_end_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_END_DAY_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='direct_season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_END_MONTH_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='direct_season_start_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_START_DAY_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='direct_season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_SEASON_START_MONTH_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='license_number',
            field=models.CharField(blank=True, help_text="LICENSE_ID in the state's rights list.", max_length=50),
        ),
        migrations.AddField(
            model_name='waterright',
            name='max_rate_cfs',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="MAX_DD_APPL in the state's rights list, in cubic feet per second.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='net_acreage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="USE_NET_ACREAGE in the state's rights list, in acres.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='permit_number',
            field=models.CharField(blank=True, help_text="PERMIT_ID in the state's rights list.", max_length=50),
        ),
        migrations.AddField(
            model_name='waterright',
            name='purpose_of_use',
            field=models.CharField(blank=True, help_text="USE_CODE in the state's rights list (Irrigation, Municipal...).", max_length=100),
        ),
        migrations.AddField(
            model_name='waterright',
            name='state_status',
            field=models.CharField(blank=True, help_text="WATER_RIGHT_STATUS in the state's rights list (Licensed, Permitted, Claimed...). Separate from the Status field above, which this platform tracks on its own.", max_length=50),
        ),
        migrations.AddField(
            model_name='waterright',
            name='storage_season_end_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_END_DAY_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='storage_season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_END_MONTH_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='storage_season_start_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_START_DAY_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='storage_season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_START_MONTH_1 in the state's rights list.", null=True),
        ),
        migrations.AddField(
            model_name='waterright',
            name='watershed',
            field=models.CharField(blank=True, help_text="WATERSHED in the state's rights list.", max_length=200),
        ),
    ]
