# Generated by Django 5.2.15 on 2026-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0010_water_right_season_rate_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtailmentorder',
            name='watershed',
            field=models.CharField(blank=True, help_text="As the order names it; matched against a right's watershed or source name.", max_length=200),
        ),
    ]
