# Generated by Django 5.2.15 on 2026-09-21 23:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0011_curtailment_watershed_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text="This platform's own name for the device, shown in place of make and model wherever one is set. Not a 934(b) field.", max_length=100)),
                ('device_type', models.CharField(choices=[('inline_flow_meter', 'Inline flow meter'), ('submerged_orifice_gate', 'Submerged orifice gate'), ('rectangular_weir', 'Rectangular weir'), ('v_notch_weir', 'V-notch weir'), ('broad_crested_weir', 'Broad-crested weir'), ('rated_gate', 'Rated gate'), ('staff_gage_rating', 'Staff gage rating'), ('other', 'Other')], help_text="934(b)(1)(C): type of measuring device. The state's own list is inline flow meters, submerged orifice gates, rectangular weirs, v-notch weirs and broad crested weirs; rated gate and staff gage rating are added here as common devices that list does not name, and Other covers anything else.", max_length=30)),
                ('make', models.CharField(blank=True, help_text='934(b)(1)(B): make and model number of the measuring device.', max_length=100)),
                ('model_number', models.CharField(blank=True, help_text='934(b)(1)(B): make and model number of the measuring device.', max_length=100)),
                ('recording_make', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('recording_model', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('recording_type', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('measured_parameter', models.CharField(blank=True, choices=[('flow_rate', 'Flow rate'), ('volume', 'Volume'), ('stage', 'Stage'), ('other', 'Other')], help_text='934(b)(1)(F): measured parameter and associated units of the raw device output.', max_length=20)),
                ('raw_units', models.CharField(blank=True, help_text='934(b)(1)(F): measured parameter and associated units of the raw device output.', max_length=30)),
                ('accuracy_percent', models.DecimalField(blank=True, decimal_places=2, help_text='934(b)(1)(G): accuracy of the measurement data, as a percentage.', max_digits=5, null=True)),
                ('installed_on', models.DateField(blank=True, help_text='934(b)(1)(H): date of installation.', null=True)),
                ('installer_contact', models.CharField(blank=True, help_text='934(b)(1)(I): contact information for the qualified individual who installed and verified the accuracy of the measuring device.', max_length=200)),
                ('last_evidence_on', models.DateField(blank=True, help_text="934(d): date of the calibration report, certification or field test that stands as this device's evidence of proper functioning, due on or before the first annual report after installation and at least once every five years after that.", null=True)),
                ('state_device_id', models.CharField(blank=True, help_text="The number the state's own registry generates for this device, once filed there. Not itself a 934(b) field.", max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='934(b)(1)(D): location of the measuring device, when it sits apart from the point of diversion it is linked to below.', null=True, srid=4326)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_rights', models.ManyToManyField(blank=True, help_text='934(b)(1)(A): identification number of each claimed water right that uses the measuring device or recording device.', related_name='measuring_devices', to='surface.waterright')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfDiversionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.measuringdevice')),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.pointofdiversion')),
            ],
            options={
                'unique_together': {('point_of_diversion', 'device')},
            },
        ),
    ]
