# Generated by Django 5.2.15 on 2026-09-22 00:06
#
# 146-03 Task 2: method, device and data state on every diversion record.
# Every existing DiversionRecord gets method='' (not stated) and
# data_state='provisional' by this migration's defaults -- not because either
# is known to be true of a prior row, but because no prior row said what it
# was: 'not stated' and 'provisional' are the honest defaults for data this
# platform never asked the operator about until now, never a guess dressed
# up as a measurement.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0012_measuring_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='diversionrecord',
            name='data_state',
            field=models.CharField(choices=[('raw', 'Raw'), ('provisional', 'Provisional'), ('non_provisional', 'Non-provisional')], default='provisional', help_text='931(s) and 931(j)(3): raw, provisional or non-provisional. Only non-provisional data goes in an annual report.', max_length=20),
        ),
        migrations.AddField(
            model_name='diversionrecord',
            name='device',
            field=models.ForeignKey(blank=True, help_text="The measuring device behind this record's number, when method is 'a measuring device'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='surface.measuringdevice'),
        ),
        migrations.AddField(
            model_name='diversionrecord',
            name='method',
            field=models.CharField(blank=True, choices=[('device', 'A measuring device'), ('methodology', 'A measurement methodology on file'), ('alternative_compliance', 'An alternative compliance plan (for example remote sensing)'), ('apportioned', 'Apportioned from a shared aggregate, 934(a)(8)'), ('below_threshold', 'Under 10 acre-feet a year: no standard applies'), ('outage_estimate', 'Estimated during a device outage, 937(b)(4)'), ('estimated_from_use', "Estimated forward from use (Phase 149's estimator)")], help_text="How this number is known, in the state's own words (Water Code 5002(b): 'the method of measurement used'). Blank means not stated.", max_length=30),
        ),
    ]
