# Generated by Django 5.2.15 on 2026-09-22 01:24
#
# 146-03 Task 3: the three canal-loss fractions on every existing
# PointOfDiversion row get evaporation_fraction=0.0100, seepage_fraction=0
# and spill_fraction=0 -- the design-implications document's own defaults
# (2026-09-18, convention 4), not a measurement of any real canal. Phase 148
# rules on who owns each share and what value is right for a given canal;
# Phase 149's engine is the first thing that computes with them. Nothing in
# this plan does, so an existing row landing on the default is a safe no-op
# until then. miners_inch_gpm=11.22 is the statute's own gallons-a-minute
# figure (the memo's J1), likewise not district-specific until edited.

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0013_diversion_record_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofdiversion',
            name='contract_unit',
            field=models.CharField(blank=True, choices=[('cfs', 'Cubic feet per second (cfs)'), ('miners_inch', "Miner's inch"), ('gpm', 'Gallons per minute (gpm)'), ('acre_feet_per_day', 'Acre-feet per day')], help_text="The unit the operator's own delivery record is kept in, when it is not cfs.", max_length=20),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='evaporation_band_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='evaporation_fraction',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text="Share of the diverted volume lost to evaporation off the canal, about 1 percent by convention. An agency's own measured or district figure replaces this default.", max_digits=5),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='local_name',
            field=models.CharField(blank=True, help_text='The ditch tender\'s own name for this point, such as a headgate, a run or a turnout. Shown as "known locally as" beside the point\'s own name when set.', max_length=200),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='loss_basis',
            field=models.CharField(choices=[('measured', 'Measured'), ('district_estimate', 'District estimate'), ('default', 'Default (not district-specific)')], default='default', help_text="How the three shares above were set: measured on this canal, a district estimate, or this platform's own default.", max_length=20),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='miners_inch_gpm',
            field=models.DecimalField(decimal_places=2, default=Decimal('11.22'), help_text="The statute's 11.22 gallons a minute, unless the district's own contract says 10 or 9.", max_digits=5),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='seepage_band_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread. Turlock publishes seepage at ±35%.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='seepage_fraction',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Share of the diverted volume lost to canal seepage. Defaults to 0 (not stated) rather than guessing a district's figure.", max_digits=5),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='spill_band_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='spill_device',
            field=models.ForeignKey(blank=True, help_text='Spill measured at the terminus where a device exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spill_points', to='surface.measuringdevice'),
        ),
        migrations.AddField(
            model_name='pointofdiversion',
            name='spill_fraction',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Share of the diverted volume that spills downstream, re-diverted at the point spill_device or rediverted_from names. Defaults to 0 (not stated).', max_digits=5),
        ),
    ]
