# Generated by Django 5.2.15 on 2026-09-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_parcelledger_parcelledger_supply_rows_positive_and_more'),
        ('surface', '0014_loss_fractions_and_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assigned_efficiency', models.DecimalField(decimal_places=3, help_text='The share of applied water the table assigns this method, as a fraction (0.600 is 60%).', max_digits=4)),
                ('range_low', models.DecimalField(decimal_places=3, help_text="Low end of the table's published range, as a fraction.", max_digits=4)),
                ('range_high', models.DecimalField(decimal_places=3, help_text="High end of the table's published range, as a fraction.", max_digits=4)),
                ('source', models.CharField(help_text='The published table this row is copied from.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParcelIrrigationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='use_areas', to='surface.irrigationmethod')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation', to='parcels.parcel')),
            ],
        ),
    ]
