# Generated by Django 5.2.15 on 2026-09-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_account_unit_kind_delivery'),
        ('surface', '0016_seed_irrigation_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAccountDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surface_delivery_point', to='accounting.wateraccount')),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_accounts', to='surface.pointofdiversion')),
            ],
        ),
    ]
