# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('surface', '0017_water_account_delivery_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurtailmentOrderEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('order_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('watershed', models.CharField(blank=True, help_text="As the order names it; matched against a right's watershed or source name.", max_length=200)),
                ('priority_date_cutoff', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('rescinded', 'Rescinded')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiversionRecordEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('device', models.BigIntegerField(blank=True, db_column='device_id', null=True, verbose_name='device')),
                ('id', models.BigIntegerField()),
                ('month', models.DateField()),
                ('volume_acre_feet', models.DecimalField(decimal_places=4, max_digits=12)),
                ('returned_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Agency-asserted acre-feet of this diversion returned to the stream (0 = fully consumed; = full volume for non-consumptive / hydropower passthrough).', max_digits=12)),
                ('max_flow_rate_cfs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('diversion_type', models.CharField(choices=[('direct_use', 'Direct Use'), ('to_storage', 'To Storage')], default='direct_use', max_length=50)),
                ('method', models.CharField(blank=True, choices=[('device', 'A measuring device'), ('methodology', 'A measurement methodology on file'), ('alternative_compliance', 'An alternative compliance plan (for example remote sensing)'), ('apportioned', 'Apportioned from a shared aggregate, 934(a)(8)'), ('below_threshold', 'Under 10 acre-feet a year: no standard applies'), ('outage_estimate', 'Estimated during a device outage, 937(b)(4)'), ('estimated_from_use', "Estimated forward from use (Phase 149's estimator)")], help_text="How this number is known, in the state's own words (Water Code 5002(b): 'the method of measurement used'). Blank means not stated.", max_length=30)),
                ('data_state', models.CharField(choices=[('raw', 'Raw'), ('provisional', 'Provisional'), ('non_provisional', 'Non-provisional')], default='provisional', help_text='931(s) and 931(j)(3): raw, provisional or non-provisional. Only non-provisional data goes in an annual report.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrrigationMethodEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('assigned_efficiency', models.DecimalField(decimal_places=3, help_text='The share of applied water the table assigns this method, as a fraction (0.600 is 60%).', max_digits=4)),
                ('range_low', models.DecimalField(decimal_places=3, help_text="Low end of the table's published range, as a fraction.", max_digits=4)),
                ('range_high', models.DecimalField(decimal_places=3, help_text="High end of the table's published range, as a fraction.", max_digits=4)),
                ('source', models.CharField(help_text='The published table this row is copied from.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasuringDeviceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('nickname', models.CharField(blank=True, help_text="This platform's own name for the device, shown in place of make and model wherever one is set. Not a 934(b) field.", max_length=100)),
                ('device_type', models.CharField(choices=[('inline_flow_meter', 'Inline flow meter'), ('submerged_orifice_gate', 'Submerged orifice gate'), ('rectangular_weir', 'Rectangular weir'), ('v_notch_weir', 'V-notch weir'), ('broad_crested_weir', 'Broad-crested weir'), ('rated_gate', 'Rated gate'), ('staff_gage_rating', 'Staff gage rating'), ('other', 'Other')], help_text="934(b)(1)(C): type of measuring device. The state's own list is inline flow meters, submerged orifice gates, rectangular weirs, v-notch weirs and broad crested weirs; rated gate and staff gage rating are added here as common devices that list does not name, and Other covers anything else.", max_length=30)),
                ('make', models.CharField(blank=True, help_text='934(b)(1)(B): make and model number of the measuring device.', max_length=100)),
                ('model_number', models.CharField(blank=True, help_text='934(b)(1)(B): make and model number of the measuring device.', max_length=100)),
                ('recording_make', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('recording_model', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('recording_type', models.CharField(blank=True, help_text='934(b)(1)(E): make, model number and type of the recording device, if different from the measuring device.', max_length=100)),
                ('measured_parameter', models.CharField(blank=True, choices=[('flow_rate', 'Flow rate'), ('volume', 'Volume'), ('stage', 'Stage'), ('other', 'Other')], help_text='934(b)(1)(F): measured parameter and associated units of the raw device output.', max_length=20)),
                ('raw_units', models.CharField(blank=True, help_text='934(b)(1)(F): measured parameter and associated units of the raw device output.', max_length=30)),
                ('accuracy_percent', models.DecimalField(blank=True, decimal_places=2, help_text='934(b)(1)(G): accuracy of the measurement data, as a percentage.', max_digits=5, null=True)),
                ('installed_on', models.DateField(blank=True, help_text='934(b)(1)(H): date of installation.', null=True)),
                ('installer_contact', models.CharField(blank=True, help_text='934(b)(1)(I): contact information for the qualified individual who installed and verified the accuracy of the measuring device.', max_length=200)),
                ('last_evidence_on', models.DateField(blank=True, help_text="934(d): date of the calibration report, certification or field test that stands as this device's evidence of proper functioning, due on or before the first annual report after installation and at least once every five years after that.", null=True)),
                ('state_device_id', models.CharField(blank=True, help_text="The number the state's own registry generates for this device, once filed there. Not itself a 934(b) field.", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelIrrigationMethodEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('method', models.BigIntegerField(blank=True, db_column='method_id', null=True, verbose_name='method')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfDiversionDeviceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('device', models.BigIntegerField(blank=True, db_column='device_id', null=True, verbose_name='device')),
                ('id', models.BigIntegerField()),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfDiversionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('water_right', models.BigIntegerField(blank=True, db_column='water_right_id', null=True, verbose_name='water right')),
                ('rediverted_from', models.BigIntegerField(blank=True, db_column='rediverted_from_id', null=True, verbose_name='rediverted from')),
                ('source_flowline', models.BigIntegerField(blank=True, db_column='source_flowline_id', null=True, verbose_name='source flowline')),
                ('spill_device', models.BigIntegerField(blank=True, db_column='spill_device_id', null=True, verbose_name='spill device')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('stream_name', models.CharField(blank=True, max_length=200)),
                ('max_rate_cfs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('evaporation_fraction', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text="Share of the diverted volume lost to evaporation off the canal, about 1 percent by convention. An agency's own measured or district figure replaces this default.", max_digits=5)),
                ('seepage_fraction', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Share of the diverted volume lost to canal seepage. Defaults to 0 (not stated) rather than guessing a district's figure.", max_digits=5)),
                ('spill_fraction', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Share of the diverted volume that spills downstream, re-diverted at the point spill_device or rediverted_from names. Defaults to 0 (not stated).', max_digits=5)),
                ('evaporation_band_percent', models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread.", max_digits=5, null=True)),
                ('seepage_band_percent', models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread. Turlock publishes seepage at ±35%.", max_digits=5, null=True)),
                ('spill_band_percent', models.DecimalField(blank=True, decimal_places=2, help_text="The district's stated uncertainty; blank when none is stated; never a model spread.", max_digits=5, null=True)),
                ('loss_basis', models.CharField(choices=[('measured', 'Measured'), ('district_estimate', 'District estimate'), ('default', 'Default (not district-specific)')], default='default', help_text="How the three shares above were set: measured on this canal, a district estimate, or this platform's own default.", max_length=20)),
                ('local_name', models.CharField(blank=True, help_text='The ditch tender\'s own name for this point, such as a headgate, a run or a turnout. Shown as "known locally as" beside the point\'s own name when set.', max_length=200)),
                ('contract_unit', models.CharField(blank=True, choices=[('cfs', 'Cubic feet per second (cfs)'), ('miners_inch', "Miner's inch"), ('gpm', 'Gallons per minute (gpm)'), ('acre_feet_per_day', 'Acre-feet per day')], help_text="The unit the operator's own delivery record is kept in, when it is not cfs.", max_length=20)),
                ('miners_inch_gpm', models.DecimalField(decimal_places=2, default=Decimal('11.22'), help_text="The statute's 11.22 gallons a minute, unless the district's own contract says 10 or 9.", max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfDiversionParcelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('id', models.BigIntegerField()),
                ('fraction', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnallocatedDeliveryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('id', models.BigIntegerField()),
                ('month', models.DateField(help_text='First of the month this surplus arose in.')),
                ('amount_acre_feet', models.DecimalField(decimal_places=4, help_text='Positive magnitude of delivered water not explained by demand.', max_digits=12)),
                ('delivery_acre_feet', models.DecimalField(decimal_places=4, help_text="The month's total consumed delivery, for context.", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterAccountDeliveryPointEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('account', models.BigIntegerField(blank=True, db_column='account_id', null=True, verbose_name='account')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterRightEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('right_type', models.BigIntegerField(blank=True, db_column='right_type_id', null=True, verbose_name='right type')),
                ('id', models.BigIntegerField()),
                ('right_id', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=200)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('face_value_acre_feet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('curtailed', 'Curtailed'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('calwatrs_pin', models.CharField(blank=True, help_text='CalWATRS PIN mailed by SWRCB for this water right. The state issues one PIN per right; supplied by the agency, not fetched by OpenH2O.', max_length=50)),
                ('state_status', models.CharField(blank=True, help_text="WATER_RIGHT_STATUS in the state's rights list (Licensed, Permitted, Claimed...). Separate from the Status field above, which this platform tracks on its own.", max_length=50)),
                ('permit_number', models.CharField(blank=True, help_text="PERMIT_ID in the state's rights list.", max_length=50)),
                ('license_number', models.CharField(blank=True, help_text="LICENSE_ID in the state's rights list.", max_length=50)),
                ('purpose_of_use', models.CharField(blank=True, help_text="USE_CODE in the state's rights list (Irrigation, Municipal...).", max_length=100)),
                ('net_acreage', models.DecimalField(blank=True, decimal_places=2, help_text="USE_NET_ACREAGE in the state's rights list, in acres.", max_digits=12, null=True)),
                ('max_rate_cfs', models.DecimalField(blank=True, decimal_places=4, help_text="MAX_DD_APPL in the state's rights list, in cubic feet per second.", max_digits=10, null=True)),
                ('direct_season_start_month', models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_SEASON_START_MONTH_1 in the state's rights list.", null=True)),
                ('direct_season_start_day', models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_START_DAY_1 in the state's rights list.", null=True)),
                ('direct_season_end_month', models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_END_MONTH_1 in the state's rights list.", null=True)),
                ('direct_season_end_day', models.PositiveSmallIntegerField(blank=True, help_text="DIRECT_DIV_SEASON_END_DAY_1 in the state's rights list.", null=True)),
                ('storage_season_start_month', models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_START_MONTH_1 in the state's rights list.", null=True)),
                ('storage_season_start_day', models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_START_DAY_1 in the state's rights list.", null=True)),
                ('storage_season_end_month', models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_END_MONTH_1 in the state's rights list.", null=True)),
                ('storage_season_end_day', models.PositiveSmallIntegerField(blank=True, help_text="STORAGE_SEASON_END_DAY_1 in the state's rights list.", null=True)),
                ('watershed', models.CharField(blank=True, help_text="WATERSHED in the state's rights list.", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterRightParcelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('water_right', models.BigIntegerField(blank=True, db_column='water_right_id', null=True, verbose_name='water right')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('id', models.BigIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='curtailmentorder',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_curtailmentorderevent" ("created_at", "effective_date", "end_date", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date_cutoff", "status", "title", "watershed") VALUES (NEW."created_at", NEW."effective_date", NEW."end_date", NEW."id", NEW."notes", NEW."order_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority_date_cutoff", NEW."status", NEW."title", NEW."watershed"); RETURN NULL;', hash='f9d1c2215edafbe93be70367ef15d96ba41dea23', operation='INSERT', pgid='pgtrigger_insert_insert_22bd5', table='surface_curtailmentorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='curtailmentorder',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."effective_date" IS DISTINCT FROM (NEW."effective_date") OR OLD."end_date" IS DISTINCT FROM (NEW."end_date") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."order_id" IS DISTINCT FROM (NEW."order_id") OR OLD."priority_date_cutoff" IS DISTINCT FROM (NEW."priority_date_cutoff") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."watershed" IS DISTINCT FROM (NEW."watershed"))', func='INSERT INTO "surface_curtailmentorderevent" ("created_at", "effective_date", "end_date", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date_cutoff", "status", "title", "watershed") VALUES (OLD."created_at", OLD."effective_date", OLD."end_date", OLD."id", OLD."notes", OLD."order_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."priority_date_cutoff", OLD."status", OLD."title", OLD."watershed"); RETURN NULL;', hash='c9fa3f1e7c110e9b6005d24513c4d42b3b8d1ee9', operation='UPDATE', pgid='pgtrigger_before_update_update_ad617', table='surface_curtailmentorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='curtailmentorder',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."effective_date" IS DISTINCT FROM (NEW."effective_date") OR OLD."end_date" IS DISTINCT FROM (NEW."end_date") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."order_id" IS DISTINCT FROM (NEW."order_id") OR OLD."priority_date_cutoff" IS DISTINCT FROM (NEW."priority_date_cutoff") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."watershed" IS DISTINCT FROM (NEW."watershed"))', func='INSERT INTO "surface_curtailmentorderevent" ("created_at", "effective_date", "end_date", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date_cutoff", "status", "title", "watershed") VALUES (NEW."created_at", NEW."effective_date", NEW."end_date", NEW."id", NEW."notes", NEW."order_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority_date_cutoff", NEW."status", NEW."title", NEW."watershed"); RETURN NULL;', hash='c24ffe1b568766968e53c91949e51c1914f5b256', operation='UPDATE', pgid='pgtrigger_update_update_92cec', table='surface_curtailmentorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='curtailmentorder',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_curtailmentorderevent" ("created_at", "effective_date", "end_date", "id", "notes", "order_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date_cutoff", "status", "title", "watershed") VALUES (OLD."created_at", OLD."effective_date", OLD."end_date", OLD."id", OLD."notes", OLD."order_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority_date_cutoff", OLD."status", OLD."title", OLD."watershed"); RETURN NULL;', hash='901682e5f53ef38b6211c0c871fd9a204686d6a9', operation='DELETE', pgid='pgtrigger_delete_delete_b4856', table='surface_curtailmentorder', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diversionrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_diversionrecordevent" ("created_at", "data_state", "device_id", "diversion_type", "id", "max_flow_rate_cfs", "method", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id", "returned_af", "volume_acre_feet") VALUES (NEW."created_at", NEW."data_state", NEW."device_id", NEW."diversion_type", NEW."id", NEW."max_flow_rate_cfs", NEW."method", NEW."month", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id", NEW."reporting_period_id", NEW."returned_af", NEW."volume_acre_feet"); RETURN NULL;', hash='b1f5d538d6c2997145b32966e8fe1ac646ec887e', operation='INSERT', pgid='pgtrigger_insert_insert_8b5f2', table='surface_diversionrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diversionrecord',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_diversionrecordevent" ("created_at", "data_state", "device_id", "diversion_type", "id", "max_flow_rate_cfs", "method", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id", "returned_af", "volume_acre_feet") VALUES (OLD."created_at", OLD."data_state", OLD."device_id", OLD."diversion_type", OLD."id", OLD."max_flow_rate_cfs", OLD."method", OLD."month", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id", OLD."reporting_period_id", OLD."returned_af", OLD."volume_acre_feet"); RETURN NULL;', hash='c1955663920ed7e107b2880d1b792745c800cbf6', operation='UPDATE', pgid='pgtrigger_before_update_update_20774', table='surface_diversionrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diversionrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_diversionrecordevent" ("created_at", "data_state", "device_id", "diversion_type", "id", "max_flow_rate_cfs", "method", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id", "returned_af", "volume_acre_feet") VALUES (NEW."created_at", NEW."data_state", NEW."device_id", NEW."diversion_type", NEW."id", NEW."max_flow_rate_cfs", NEW."method", NEW."month", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id", NEW."reporting_period_id", NEW."returned_af", NEW."volume_acre_feet"); RETURN NULL;', hash='8353c5b1986b6f8252e87510c402335a9330a638', operation='UPDATE', pgid='pgtrigger_update_update_94686', table='surface_diversionrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='diversionrecord',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_diversionrecordevent" ("created_at", "data_state", "device_id", "diversion_type", "id", "max_flow_rate_cfs", "method", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id", "returned_af", "volume_acre_feet") VALUES (OLD."created_at", OLD."data_state", OLD."device_id", OLD."diversion_type", OLD."id", OLD."max_flow_rate_cfs", OLD."method", OLD."month", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id", OLD."reporting_period_id", OLD."returned_af", OLD."volume_acre_feet"); RETURN NULL;', hash='a2eb86f06cbcf41bb21786e03eabbac518a38be0', operation='DELETE', pgid='pgtrigger_delete_delete_278c4', table='surface_diversionrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='irrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_irrigationmethodevent" ("assigned_efficiency", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "range_high", "range_low", "sort_order", "source") VALUES (NEW."assigned_efficiency", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."range_high", NEW."range_low", NEW."sort_order", NEW."source"); RETURN NULL;', hash='79b3a2fe0ae3a9d4a46ffe06973de317e1d96d1b', operation='INSERT', pgid='pgtrigger_insert_insert_2d181', table='surface_irrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='irrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_irrigationmethodevent" ("assigned_efficiency", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "range_high", "range_low", "sort_order", "source") VALUES (OLD."assigned_efficiency", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."range_high", OLD."range_low", OLD."sort_order", OLD."source"); RETURN NULL;', hash='98abb12b20c1547f7469756ac213166087dbd34c', operation='UPDATE', pgid='pgtrigger_before_update_update_4002a', table='surface_irrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='irrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_irrigationmethodevent" ("assigned_efficiency", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "range_high", "range_low", "sort_order", "source") VALUES (NEW."assigned_efficiency", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."range_high", NEW."range_low", NEW."sort_order", NEW."source"); RETURN NULL;', hash='e512f89d2f0e42d07ac20e4b0ca0adb2239b6e86', operation='UPDATE', pgid='pgtrigger_update_update_67c5f', table='surface_irrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='irrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_irrigationmethodevent" ("assigned_efficiency", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "range_high", "range_low", "sort_order", "source") VALUES (OLD."assigned_efficiency", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."range_high", OLD."range_low", OLD."sort_order", OLD."source"); RETURN NULL;', hash='3389f88fc718f7537ddae184fb6b44a2d6a4efb2', operation='DELETE', pgid='pgtrigger_delete_delete_1192b', table='surface_irrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='measuringdevice',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_measuringdeviceevent" ("accuracy_percent", "created_at", "device_type", "id", "installed_on", "installer_contact", "last_evidence_on", "make", "measured_parameter", "model_number", "nickname", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_units", "recording_make", "recording_model", "recording_type", "state_device_id", "status") VALUES (NEW."accuracy_percent", NEW."created_at", NEW."device_type", NEW."id", NEW."installed_on", NEW."installer_contact", NEW."last_evidence_on", NEW."make", NEW."measured_parameter", NEW."model_number", NEW."nickname", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."raw_units", NEW."recording_make", NEW."recording_model", NEW."recording_type", NEW."state_device_id", NEW."status"); RETURN NULL;', hash='ba524f3f25204dc3d9b23130a3d90a602b9da4fb', operation='INSERT', pgid='pgtrigger_insert_insert_85426', table='surface_measuringdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='measuringdevice',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."accuracy_percent" IS DISTINCT FROM (NEW."accuracy_percent") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_type" IS DISTINCT FROM (NEW."device_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."installed_on" IS DISTINCT FROM (NEW."installed_on") OR OLD."installer_contact" IS DISTINCT FROM (NEW."installer_contact") OR OLD."last_evidence_on" IS DISTINCT FROM (NEW."last_evidence_on") OR OLD."make" IS DISTINCT FROM (NEW."make") OR OLD."measured_parameter" IS DISTINCT FROM (NEW."measured_parameter") OR OLD."model_number" IS DISTINCT FROM (NEW."model_number") OR OLD."nickname" IS DISTINCT FROM (NEW."nickname") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."raw_units" IS DISTINCT FROM (NEW."raw_units") OR OLD."recording_make" IS DISTINCT FROM (NEW."recording_make") OR OLD."recording_model" IS DISTINCT FROM (NEW."recording_model") OR OLD."recording_type" IS DISTINCT FROM (NEW."recording_type") OR OLD."state_device_id" IS DISTINCT FROM (NEW."state_device_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "surface_measuringdeviceevent" ("accuracy_percent", "created_at", "device_type", "id", "installed_on", "installer_contact", "last_evidence_on", "make", "measured_parameter", "model_number", "nickname", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_units", "recording_make", "recording_model", "recording_type", "state_device_id", "status") VALUES (OLD."accuracy_percent", OLD."created_at", OLD."device_type", OLD."id", OLD."installed_on", OLD."installer_contact", OLD."last_evidence_on", OLD."make", OLD."measured_parameter", OLD."model_number", OLD."nickname", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."raw_units", OLD."recording_make", OLD."recording_model", OLD."recording_type", OLD."state_device_id", OLD."status"); RETURN NULL;', hash='11ab84bff8f5f0eead90ba6b1238018a6499bd65', operation='UPDATE', pgid='pgtrigger_before_update_update_64fc6', table='surface_measuringdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='measuringdevice',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."accuracy_percent" IS DISTINCT FROM (NEW."accuracy_percent") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_type" IS DISTINCT FROM (NEW."device_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."installed_on" IS DISTINCT FROM (NEW."installed_on") OR OLD."installer_contact" IS DISTINCT FROM (NEW."installer_contact") OR OLD."last_evidence_on" IS DISTINCT FROM (NEW."last_evidence_on") OR OLD."make" IS DISTINCT FROM (NEW."make") OR OLD."measured_parameter" IS DISTINCT FROM (NEW."measured_parameter") OR OLD."model_number" IS DISTINCT FROM (NEW."model_number") OR OLD."nickname" IS DISTINCT FROM (NEW."nickname") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."raw_units" IS DISTINCT FROM (NEW."raw_units") OR OLD."recording_make" IS DISTINCT FROM (NEW."recording_make") OR OLD."recording_model" IS DISTINCT FROM (NEW."recording_model") OR OLD."recording_type" IS DISTINCT FROM (NEW."recording_type") OR OLD."state_device_id" IS DISTINCT FROM (NEW."state_device_id") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "surface_measuringdeviceevent" ("accuracy_percent", "created_at", "device_type", "id", "installed_on", "installer_contact", "last_evidence_on", "make", "measured_parameter", "model_number", "nickname", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_units", "recording_make", "recording_model", "recording_type", "state_device_id", "status") VALUES (NEW."accuracy_percent", NEW."created_at", NEW."device_type", NEW."id", NEW."installed_on", NEW."installer_contact", NEW."last_evidence_on", NEW."make", NEW."measured_parameter", NEW."model_number", NEW."nickname", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."raw_units", NEW."recording_make", NEW."recording_model", NEW."recording_type", NEW."state_device_id", NEW."status"); RETURN NULL;', hash='75d5298e748412a3038d19b466777ef44b55d5c4', operation='UPDATE', pgid='pgtrigger_update_update_fb2ad', table='surface_measuringdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='measuringdevice',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_measuringdeviceevent" ("accuracy_percent", "created_at", "device_type", "id", "installed_on", "installer_contact", "last_evidence_on", "make", "measured_parameter", "model_number", "nickname", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_units", "recording_make", "recording_model", "recording_type", "state_device_id", "status") VALUES (OLD."accuracy_percent", OLD."created_at", OLD."device_type", OLD."id", OLD."installed_on", OLD."installer_contact", OLD."last_evidence_on", OLD."make", OLD."measured_parameter", OLD."model_number", OLD."nickname", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."raw_units", OLD."recording_make", OLD."recording_model", OLD."recording_type", OLD."state_device_id", OLD."status"); RETURN NULL;', hash='08f6c3707c1d3f4a1f4f0dd74bea3d4eff1789eb', operation='DELETE', pgid='pgtrigger_delete_delete_414de', table='surface_measuringdevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelirrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_parcelirrigationmethodevent" ("id", "method_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."method_id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='74a894a87e53cb072f95f7e001dca31dcadeee5b', operation='INSERT', pgid='pgtrigger_insert_insert_a16f6', table='surface_parcelirrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelirrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_parcelirrigationmethodevent" ("id", "method_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."method_id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id"); RETURN NULL;', hash='4da86eeebbeca6bdc236c5c8910afb71a0f90458', operation='UPDATE', pgid='pgtrigger_before_update_update_799a0', table='surface_parcelirrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelirrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_parcelirrigationmethodevent" ("id", "method_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."id", NEW."method_id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='311ed5ec9950ed6f827ff6a7c961896a0fdb9de6', operation='UPDATE', pgid='pgtrigger_update_update_7e0a3', table='surface_parcelirrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='parcelirrigationmethod',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_parcelirrigationmethodevent" ("id", "method_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."id", OLD."method_id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='2e9a31fe8e8ef797fa4dde957425422034e7d0e3', operation='DELETE', pgid='pgtrigger_delete_delete_21b22', table='surface_parcelirrigationmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversionevent" ("contract_unit", "evaporation_band_percent", "evaporation_fraction", "id", "local_name", "loss_basis", "max_rate_cfs", "miners_inch_gpm", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rediverted_from_id", "seepage_band_percent", "seepage_fraction", "source_flowline_id", "spill_band_percent", "spill_device_id", "spill_fraction", "status", "stream_name", "water_right_id") VALUES (NEW."contract_unit", NEW."evaporation_band_percent", NEW."evaporation_fraction", NEW."id", NEW."local_name", NEW."loss_basis", NEW."max_rate_cfs", NEW."miners_inch_gpm", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rediverted_from_id", NEW."seepage_band_percent", NEW."seepage_fraction", NEW."source_flowline_id", NEW."spill_band_percent", NEW."spill_device_id", NEW."spill_fraction", NEW."status", NEW."stream_name", NEW."water_right_id"); RETURN NULL;', hash='afb5d9f2e614cffed2771c537171ca5e7a48bad0', operation='INSERT', pgid='pgtrigger_insert_insert_aa504', table='surface_pointofdiversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversion',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."contract_unit" IS DISTINCT FROM (NEW."contract_unit") OR OLD."evaporation_band_percent" IS DISTINCT FROM (NEW."evaporation_band_percent") OR OLD."evaporation_fraction" IS DISTINCT FROM (NEW."evaporation_fraction") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."local_name" IS DISTINCT FROM (NEW."local_name") OR OLD."loss_basis" IS DISTINCT FROM (NEW."loss_basis") OR OLD."max_rate_cfs" IS DISTINCT FROM (NEW."max_rate_cfs") OR OLD."miners_inch_gpm" IS DISTINCT FROM (NEW."miners_inch_gpm") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."rediverted_from_id" IS DISTINCT FROM (NEW."rediverted_from_id") OR OLD."seepage_band_percent" IS DISTINCT FROM (NEW."seepage_band_percent") OR OLD."seepage_fraction" IS DISTINCT FROM (NEW."seepage_fraction") OR OLD."source_flowline_id" IS DISTINCT FROM (NEW."source_flowline_id") OR OLD."spill_band_percent" IS DISTINCT FROM (NEW."spill_band_percent") OR OLD."spill_device_id" IS DISTINCT FROM (NEW."spill_device_id") OR OLD."spill_fraction" IS DISTINCT FROM (NEW."spill_fraction") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."stream_name" IS DISTINCT FROM (NEW."stream_name") OR OLD."water_right_id" IS DISTINCT FROM (NEW."water_right_id"))', func='INSERT INTO "surface_pointofdiversionevent" ("contract_unit", "evaporation_band_percent", "evaporation_fraction", "id", "local_name", "loss_basis", "max_rate_cfs", "miners_inch_gpm", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rediverted_from_id", "seepage_band_percent", "seepage_fraction", "source_flowline_id", "spill_band_percent", "spill_device_id", "spill_fraction", "status", "stream_name", "water_right_id") VALUES (OLD."contract_unit", OLD."evaporation_band_percent", OLD."evaporation_fraction", OLD."id", OLD."local_name", OLD."loss_basis", OLD."max_rate_cfs", OLD."miners_inch_gpm", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."rediverted_from_id", OLD."seepage_band_percent", OLD."seepage_fraction", OLD."source_flowline_id", OLD."spill_band_percent", OLD."spill_device_id", OLD."spill_fraction", OLD."status", OLD."stream_name", OLD."water_right_id"); RETURN NULL;', hash='38f34ea271fada2ea7739341a197cea4d8000af5', operation='UPDATE', pgid='pgtrigger_before_update_update_11fe8', table='surface_pointofdiversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."contract_unit" IS DISTINCT FROM (NEW."contract_unit") OR OLD."evaporation_band_percent" IS DISTINCT FROM (NEW."evaporation_band_percent") OR OLD."evaporation_fraction" IS DISTINCT FROM (NEW."evaporation_fraction") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."local_name" IS DISTINCT FROM (NEW."local_name") OR OLD."loss_basis" IS DISTINCT FROM (NEW."loss_basis") OR OLD."max_rate_cfs" IS DISTINCT FROM (NEW."max_rate_cfs") OR OLD."miners_inch_gpm" IS DISTINCT FROM (NEW."miners_inch_gpm") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."rediverted_from_id" IS DISTINCT FROM (NEW."rediverted_from_id") OR OLD."seepage_band_percent" IS DISTINCT FROM (NEW."seepage_band_percent") OR OLD."seepage_fraction" IS DISTINCT FROM (NEW."seepage_fraction") OR OLD."source_flowline_id" IS DISTINCT FROM (NEW."source_flowline_id") OR OLD."spill_band_percent" IS DISTINCT FROM (NEW."spill_band_percent") OR OLD."spill_device_id" IS DISTINCT FROM (NEW."spill_device_id") OR OLD."spill_fraction" IS DISTINCT FROM (NEW."spill_fraction") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."stream_name" IS DISTINCT FROM (NEW."stream_name") OR OLD."water_right_id" IS DISTINCT FROM (NEW."water_right_id"))', func='INSERT INTO "surface_pointofdiversionevent" ("contract_unit", "evaporation_band_percent", "evaporation_fraction", "id", "local_name", "loss_basis", "max_rate_cfs", "miners_inch_gpm", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rediverted_from_id", "seepage_band_percent", "seepage_fraction", "source_flowline_id", "spill_band_percent", "spill_device_id", "spill_fraction", "status", "stream_name", "water_right_id") VALUES (NEW."contract_unit", NEW."evaporation_band_percent", NEW."evaporation_fraction", NEW."id", NEW."local_name", NEW."loss_basis", NEW."max_rate_cfs", NEW."miners_inch_gpm", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rediverted_from_id", NEW."seepage_band_percent", NEW."seepage_fraction", NEW."source_flowline_id", NEW."spill_band_percent", NEW."spill_device_id", NEW."spill_fraction", NEW."status", NEW."stream_name", NEW."water_right_id"); RETURN NULL;', hash='2ba100aa1477bd8b63a4bef3a7da5df4a265c510', operation='UPDATE', pgid='pgtrigger_update_update_5b2df', table='surface_pointofdiversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversion',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversionevent" ("contract_unit", "evaporation_band_percent", "evaporation_fraction", "id", "local_name", "loss_basis", "max_rate_cfs", "miners_inch_gpm", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rediverted_from_id", "seepage_band_percent", "seepage_fraction", "source_flowline_id", "spill_band_percent", "spill_device_id", "spill_fraction", "status", "stream_name", "water_right_id") VALUES (OLD."contract_unit", OLD."evaporation_band_percent", OLD."evaporation_fraction", OLD."id", OLD."local_name", OLD."loss_basis", OLD."max_rate_cfs", OLD."miners_inch_gpm", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."rediverted_from_id", OLD."seepage_band_percent", OLD."seepage_fraction", OLD."source_flowline_id", OLD."spill_band_percent", OLD."spill_device_id", OLD."spill_fraction", OLD."status", OLD."stream_name", OLD."water_right_id"); RETURN NULL;', hash='51c1596aaa2a9e662fc55007de31cc316ff8712d', operation='DELETE', pgid='pgtrigger_delete_delete_33b90', table='surface_pointofdiversion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversiondevice',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversiondeviceevent" ("device_id", "id", "installed_on", "is_current", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "removed_on") VALUES (NEW."device_id", NEW."id", NEW."installed_on", NEW."is_current", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id", NEW."removed_on"); RETURN NULL;', hash='c8c38d643c123b17592699635a64497565ceb25e', operation='INSERT', pgid='pgtrigger_insert_insert_67182', table='surface_pointofdiversiondevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversiondevice',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_pointofdiversiondeviceevent" ("device_id", "id", "installed_on", "is_current", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "removed_on") VALUES (OLD."device_id", OLD."id", OLD."installed_on", OLD."is_current", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id", OLD."removed_on"); RETURN NULL;', hash='93cc1b868340a5b7b54cb20c3d2a2832631a473d', operation='UPDATE', pgid='pgtrigger_before_update_update_6c5ca', table='surface_pointofdiversiondevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversiondevice',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_pointofdiversiondeviceevent" ("device_id", "id", "installed_on", "is_current", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "removed_on") VALUES (NEW."device_id", NEW."id", NEW."installed_on", NEW."is_current", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id", NEW."removed_on"); RETURN NULL;', hash='506fdf6c519693b08e789d1007639e348f3658cd', operation='UPDATE', pgid='pgtrigger_update_update_36c79', table='surface_pointofdiversiondevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversiondevice',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversiondeviceevent" ("device_id", "id", "installed_on", "is_current", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "removed_on") VALUES (OLD."device_id", OLD."id", OLD."installed_on", OLD."is_current", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id", OLD."removed_on"); RETURN NULL;', hash='bf5bcdc5800d5b40b9af35abffcb1f46f45b1423', operation='DELETE', pgid='pgtrigger_delete_delete_b87af', table='surface_pointofdiversiondevice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversionparcel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversionparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (NEW."fraction", NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id"); RETURN NULL;', hash='50c6f3e2eb85a15ff8d3477732a150c4c2c6d3b6', operation='INSERT', pgid='pgtrigger_insert_insert_de116', table='surface_pointofdiversionparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversionparcel',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_pointofdiversionparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (OLD."fraction", OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id"); RETURN NULL;', hash='9ac8ac7b5d07d42d431fac2f70eb2c7033dd2fca', operation='UPDATE', pgid='pgtrigger_before_update_update_91756', table='surface_pointofdiversionparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversionparcel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_pointofdiversionparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (NEW."fraction", NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id"); RETURN NULL;', hash='de8ca4a6229246ab1f4418a429f01339758f393f', operation='UPDATE', pgid='pgtrigger_update_update_3e714', table='surface_pointofdiversionparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='pointofdiversionparcel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_pointofdiversionparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (OLD."fraction", OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id"); RETURN NULL;', hash='1d4ea538934efef5017c98b18d9854d9528f56a3', operation='DELETE', pgid='pgtrigger_delete_delete_6d17a', table='surface_pointofdiversionparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unallocateddelivery',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_unallocateddeliveryevent" ("amount_acre_feet", "created_at", "delivery_acre_feet", "id", "month", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."delivery_acre_feet", NEW."id", NEW."month", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id", NEW."reporting_period_id"); RETURN NULL;', hash='56fd5138eba75519bb2b8598230af574f7f468e7', operation='INSERT', pgid='pgtrigger_insert_insert_b9817', table='surface_unallocateddelivery', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unallocateddelivery',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_unallocateddeliveryevent" ("amount_acre_feet", "created_at", "delivery_acre_feet", "id", "month", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."delivery_acre_feet", OLD."id", OLD."month", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id", OLD."reporting_period_id"); RETURN NULL;', hash='a8119e9397f70a0c6ee0e1d450cbe20a000016db', operation='UPDATE', pgid='pgtrigger_before_update_update_6ef8f', table='surface_unallocateddelivery', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unallocateddelivery',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_unallocateddeliveryevent" ("amount_acre_feet", "created_at", "delivery_acre_feet", "id", "month", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id") VALUES (NEW."amount_acre_feet", NEW."created_at", NEW."delivery_acre_feet", NEW."id", NEW."month", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id", NEW."reporting_period_id"); RETURN NULL;', hash='521e0a75f6ee419158fb7c5385bbc9e921d5e686', operation='UPDATE', pgid='pgtrigger_update_update_7e11e', table='surface_unallocateddelivery', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unallocateddelivery',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_unallocateddeliveryevent" ("amount_acre_feet", "created_at", "delivery_acre_feet", "id", "month", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "reporting_period_id") VALUES (OLD."amount_acre_feet", OLD."created_at", OLD."delivery_acre_feet", OLD."id", OLD."month", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id", OLD."reporting_period_id"); RETURN NULL;', hash='ac3602fe8bc55f6767e0048c9bd8e451840787d4', operation='DELETE', pgid='pgtrigger_delete_delete_ef598', table='surface_unallocateddelivery', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountdeliverypoint',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_wateraccountdeliverypointevent" ("account_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (NEW."account_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id"); RETURN NULL;', hash='2e39da8eff375b1cea699cb89701b1115852b448', operation='INSERT', pgid='pgtrigger_insert_insert_25cf4', table='surface_wateraccountdeliverypoint', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountdeliverypoint',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_wateraccountdeliverypointevent" ("account_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (OLD."account_id", OLD."id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id"); RETURN NULL;', hash='a0c0ad27fd5c40129135ee686bac68de41fb0608', operation='UPDATE', pgid='pgtrigger_before_update_update_f293c', table='surface_wateraccountdeliverypoint', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountdeliverypoint',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_wateraccountdeliverypointevent" ("account_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (NEW."account_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id"); RETURN NULL;', hash='ba7cbf5d3efc2d3698d0c53621af79b7d3bf0fae', operation='UPDATE', pgid='pgtrigger_update_update_ec4d9', table='surface_wateraccountdeliverypoint', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountdeliverypoint',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_wateraccountdeliverypointevent" ("account_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id") VALUES (OLD."account_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id"); RETURN NULL;', hash='ce11e23c3ee6a6bafc34a129302dc20788168c20', operation='DELETE', pgid='pgtrigger_delete_delete_de8d9', table='surface_wateraccountdeliverypoint', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterright',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_waterrightevent" ("calwatrs_pin", "created_at", "direct_season_end_day", "direct_season_end_month", "direct_season_start_day", "direct_season_start_month", "face_value_acre_feet", "holder_name", "id", "license_number", "max_rate_cfs", "net_acreage", "notes", "permit_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date", "purpose_of_use", "right_id", "right_type_id", "source_name", "state_status", "status", "storage_season_end_day", "storage_season_end_month", "storage_season_start_day", "storage_season_start_month", "watershed") VALUES (NEW."calwatrs_pin", NEW."created_at", NEW."direct_season_end_day", NEW."direct_season_end_month", NEW."direct_season_start_day", NEW."direct_season_start_month", NEW."face_value_acre_feet", NEW."holder_name", NEW."id", NEW."license_number", NEW."max_rate_cfs", NEW."net_acreage", NEW."notes", NEW."permit_number", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority_date", NEW."purpose_of_use", NEW."right_id", NEW."right_type_id", NEW."source_name", NEW."state_status", NEW."status", NEW."storage_season_end_day", NEW."storage_season_end_month", NEW."storage_season_start_day", NEW."storage_season_start_month", NEW."watershed"); RETURN NULL;', hash='e414a7e4824228e741b8f72efc8e4ab87e998a0f', operation='INSERT', pgid='pgtrigger_insert_insert_cec0b', table='surface_waterright', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterright',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."calwatrs_pin" IS DISTINCT FROM (NEW."calwatrs_pin") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."direct_season_end_day" IS DISTINCT FROM (NEW."direct_season_end_day") OR OLD."direct_season_end_month" IS DISTINCT FROM (NEW."direct_season_end_month") OR OLD."direct_season_start_day" IS DISTINCT FROM (NEW."direct_season_start_day") OR OLD."direct_season_start_month" IS DISTINCT FROM (NEW."direct_season_start_month") OR OLD."face_value_acre_feet" IS DISTINCT FROM (NEW."face_value_acre_feet") OR OLD."holder_name" IS DISTINCT FROM (NEW."holder_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."license_number" IS DISTINCT FROM (NEW."license_number") OR OLD."max_rate_cfs" IS DISTINCT FROM (NEW."max_rate_cfs") OR OLD."net_acreage" IS DISTINCT FROM (NEW."net_acreage") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."permit_number" IS DISTINCT FROM (NEW."permit_number") OR OLD."priority_date" IS DISTINCT FROM (NEW."priority_date") OR OLD."purpose_of_use" IS DISTINCT FROM (NEW."purpose_of_use") OR OLD."right_id" IS DISTINCT FROM (NEW."right_id") OR OLD."right_type_id" IS DISTINCT FROM (NEW."right_type_id") OR OLD."source_name" IS DISTINCT FROM (NEW."source_name") OR OLD."state_status" IS DISTINCT FROM (NEW."state_status") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."storage_season_end_day" IS DISTINCT FROM (NEW."storage_season_end_day") OR OLD."storage_season_end_month" IS DISTINCT FROM (NEW."storage_season_end_month") OR OLD."storage_season_start_day" IS DISTINCT FROM (NEW."storage_season_start_day") OR OLD."storage_season_start_month" IS DISTINCT FROM (NEW."storage_season_start_month") OR OLD."watershed" IS DISTINCT FROM (NEW."watershed"))', func='INSERT INTO "surface_waterrightevent" ("calwatrs_pin", "created_at", "direct_season_end_day", "direct_season_end_month", "direct_season_start_day", "direct_season_start_month", "face_value_acre_feet", "holder_name", "id", "license_number", "max_rate_cfs", "net_acreage", "notes", "permit_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date", "purpose_of_use", "right_id", "right_type_id", "source_name", "state_status", "status", "storage_season_end_day", "storage_season_end_month", "storage_season_start_day", "storage_season_start_month", "watershed") VALUES (OLD."calwatrs_pin", OLD."created_at", OLD."direct_season_end_day", OLD."direct_season_end_month", OLD."direct_season_start_day", OLD."direct_season_start_month", OLD."face_value_acre_feet", OLD."holder_name", OLD."id", OLD."license_number", OLD."max_rate_cfs", OLD."net_acreage", OLD."notes", OLD."permit_number", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."priority_date", OLD."purpose_of_use", OLD."right_id", OLD."right_type_id", OLD."source_name", OLD."state_status", OLD."status", OLD."storage_season_end_day", OLD."storage_season_end_month", OLD."storage_season_start_day", OLD."storage_season_start_month", OLD."watershed"); RETURN NULL;', hash='bdbbddde94eeb8ae73e6b7bdb25e939891692439', operation='UPDATE', pgid='pgtrigger_before_update_update_fe9c8', table='surface_waterright', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterright',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."calwatrs_pin" IS DISTINCT FROM (NEW."calwatrs_pin") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."direct_season_end_day" IS DISTINCT FROM (NEW."direct_season_end_day") OR OLD."direct_season_end_month" IS DISTINCT FROM (NEW."direct_season_end_month") OR OLD."direct_season_start_day" IS DISTINCT FROM (NEW."direct_season_start_day") OR OLD."direct_season_start_month" IS DISTINCT FROM (NEW."direct_season_start_month") OR OLD."face_value_acre_feet" IS DISTINCT FROM (NEW."face_value_acre_feet") OR OLD."holder_name" IS DISTINCT FROM (NEW."holder_name") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."license_number" IS DISTINCT FROM (NEW."license_number") OR OLD."max_rate_cfs" IS DISTINCT FROM (NEW."max_rate_cfs") OR OLD."net_acreage" IS DISTINCT FROM (NEW."net_acreage") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."permit_number" IS DISTINCT FROM (NEW."permit_number") OR OLD."priority_date" IS DISTINCT FROM (NEW."priority_date") OR OLD."purpose_of_use" IS DISTINCT FROM (NEW."purpose_of_use") OR OLD."right_id" IS DISTINCT FROM (NEW."right_id") OR OLD."right_type_id" IS DISTINCT FROM (NEW."right_type_id") OR OLD."source_name" IS DISTINCT FROM (NEW."source_name") OR OLD."state_status" IS DISTINCT FROM (NEW."state_status") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."storage_season_end_day" IS DISTINCT FROM (NEW."storage_season_end_day") OR OLD."storage_season_end_month" IS DISTINCT FROM (NEW."storage_season_end_month") OR OLD."storage_season_start_day" IS DISTINCT FROM (NEW."storage_season_start_day") OR OLD."storage_season_start_month" IS DISTINCT FROM (NEW."storage_season_start_month") OR OLD."watershed" IS DISTINCT FROM (NEW."watershed"))', func='INSERT INTO "surface_waterrightevent" ("calwatrs_pin", "created_at", "direct_season_end_day", "direct_season_end_month", "direct_season_start_day", "direct_season_start_month", "face_value_acre_feet", "holder_name", "id", "license_number", "max_rate_cfs", "net_acreage", "notes", "permit_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date", "purpose_of_use", "right_id", "right_type_id", "source_name", "state_status", "status", "storage_season_end_day", "storage_season_end_month", "storage_season_start_day", "storage_season_start_month", "watershed") VALUES (NEW."calwatrs_pin", NEW."created_at", NEW."direct_season_end_day", NEW."direct_season_end_month", NEW."direct_season_start_day", NEW."direct_season_start_month", NEW."face_value_acre_feet", NEW."holder_name", NEW."id", NEW."license_number", NEW."max_rate_cfs", NEW."net_acreage", NEW."notes", NEW."permit_number", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority_date", NEW."purpose_of_use", NEW."right_id", NEW."right_type_id", NEW."source_name", NEW."state_status", NEW."status", NEW."storage_season_end_day", NEW."storage_season_end_month", NEW."storage_season_start_day", NEW."storage_season_start_month", NEW."watershed"); RETURN NULL;', hash='dc0936861ecc814e30c9e5c78d72ed6ed4e4aa8a', operation='UPDATE', pgid='pgtrigger_update_update_af051', table='surface_waterright', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterright',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_waterrightevent" ("calwatrs_pin", "created_at", "direct_season_end_day", "direct_season_end_month", "direct_season_start_day", "direct_season_start_month", "face_value_acre_feet", "holder_name", "id", "license_number", "max_rate_cfs", "net_acreage", "notes", "permit_number", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority_date", "purpose_of_use", "right_id", "right_type_id", "source_name", "state_status", "status", "storage_season_end_day", "storage_season_end_month", "storage_season_start_day", "storage_season_start_month", "watershed") VALUES (OLD."calwatrs_pin", OLD."created_at", OLD."direct_season_end_day", OLD."direct_season_end_month", OLD."direct_season_start_day", OLD."direct_season_start_month", OLD."face_value_acre_feet", OLD."holder_name", OLD."id", OLD."license_number", OLD."max_rate_cfs", OLD."net_acreage", OLD."notes", OLD."permit_number", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."priority_date", OLD."purpose_of_use", OLD."right_id", OLD."right_type_id", OLD."source_name", OLD."state_status", OLD."status", OLD."storage_season_end_day", OLD."storage_season_end_month", OLD."storage_season_start_day", OLD."storage_season_start_month", OLD."watershed"); RETURN NULL;', hash='420fdcc57e8a8eed47d0dac77c76770df07aeff5', operation='DELETE', pgid='pgtrigger_delete_delete_1a181', table='surface_waterright', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterrightparcel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_waterrightparcelevent" ("id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_right_id") VALUES (NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."water_right_id"); RETURN NULL;', hash='011899b23ee427dd3385c9e6e680740f54782ed3', operation='INSERT', pgid='pgtrigger_insert_insert_035f3', table='surface_waterrightparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterrightparcel',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_waterrightparcelevent" ("id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_right_id") VALUES (OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."water_right_id"); RETURN NULL;', hash='6352bc30e68d9034cfaea81eb694e2743fc9627c', operation='UPDATE', pgid='pgtrigger_before_update_update_bd10e', table='surface_waterrightparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterrightparcel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_waterrightparcelevent" ("id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_right_id") VALUES (NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."water_right_id"); RETURN NULL;', hash='7c3d2efad2490e612c05c3ddc40bb93b1652253a', operation='UPDATE', pgid='pgtrigger_update_update_4c1cd', table='surface_waterrightparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='waterrightparcel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_waterrightparcelevent" ("id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_right_id") VALUES (OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."water_right_id"); RETURN NULL;', hash='0d7c081cbf07a8e27fce4f9b29d9542a98198ebf', operation='DELETE', pgid='pgtrigger_delete_delete_520f8', table='surface_waterrightparcel', when='AFTER')),
        ),
        migrations.AddField(
            model_name='curtailmentorderevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='curtailmentorderevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.curtailmentorder'),
        ),
        migrations.AddField(
            model_name='diversionrecordevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='diversionrecordevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.diversionrecord'),
        ),
        migrations.AddField(
            model_name='irrigationmethodevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='irrigationmethodevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.irrigationmethod'),
        ),
        migrations.AddField(
            model_name='measuringdeviceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='measuringdeviceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.measuringdevice'),
        ),
        migrations.AddField(
            model_name='parcelirrigationmethodevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='parcelirrigationmethodevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.parcelirrigationmethod'),
        ),
        migrations.AddField(
            model_name='pointofdiversiondeviceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pointofdiversiondeviceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.pointofdiversiondevice'),
        ),
        migrations.AddField(
            model_name='pointofdiversionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pointofdiversionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.pointofdiversion'),
        ),
        migrations.AddField(
            model_name='pointofdiversionparcelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='pointofdiversionparcelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.pointofdiversionparcel'),
        ),
        migrations.AddField(
            model_name='unallocateddeliveryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='unallocateddeliveryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.unallocateddelivery'),
        ),
        migrations.AddField(
            model_name='wateraccountdeliverypointevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wateraccountdeliverypointevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.wateraccountdeliverypoint'),
        ),
        migrations.AddField(
            model_name='waterrightevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='waterrightevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.waterright'),
        ),
        migrations.AddField(
            model_name='waterrightparcelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='waterrightparcelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.waterrightparcel'),
        ),
    ]
