# Generated by Django 5.2.15 on 2026-09-24 03:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0018_curtailmentorderevent_diversionrecordevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='diversionrecord',
            trigger=pgtrigger.compiler.Trigger(name='finalized_period_lock', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE locked_name text;', func='IF TG_OP IN (\'UPDATE\', \'DELETE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((OLD."month") BETWEEN p.start_date AND p.end_date OR p.id = OLD."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP IN (\'INSERT\', \'UPDATE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((NEW."month") BETWEEN p.start_date AND p.end_date OR p.id = NEW."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP = \'DELETE\' THEN RETURN OLD; END IF; RETURN NEW;', hash='df56b12abc5aa1be785448a28b5d50407259c298', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_finalized_period_lock_58fb6', table='surface_diversionrecord', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='unallocateddelivery',
            trigger=pgtrigger.compiler.Trigger(name='finalized_period_lock', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE locked_name text;', func='IF TG_OP IN (\'UPDATE\', \'DELETE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((OLD."month") BETWEEN p.start_date AND p.end_date OR p.id = OLD."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP IN (\'INSERT\', \'UPDATE\') THEN SELECT p.name INTO locked_name FROM accounting_reportingperiod p WHERE p.is_finalized AND ((NEW."month") BETWEEN p.start_date AND p.end_date OR p.id = NEW."reporting_period_id") ORDER BY p.start_date LIMIT 1; IF locked_name IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE = \'OH409\', MESSAGE = locked_name || \' is finalized. An administrator can reopen it on the period page.\', DETAIL = TG_TABLE_NAME; END IF; END IF; IF TG_OP = \'DELETE\' THEN RETURN OLD; END IF; RETURN NEW;', hash='e6de3c871d4a019a289b21f6c3f5e35d447bc4e8', operation='INSERT OR UPDATE OR DELETE', pgid='pgtrigger_finalized_period_lock_1e723', table='surface_unallocateddelivery', when='BEFORE')),
        ),
    ]
