# Generated by Django 5.2.15 on 2026-10-06 14:10

import django.db.models.deletion
import django.db.models.expressions
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_parcelzoneevent_zoneevent_parcelzone_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('surface', '0019_diversionrecord_finalized_period_lock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalMonthLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First of the calendar month.')),
                ('diverted_af', models.DecimalField(decimal_places=4, help_text="The month's direct-use total the split started from: volume less returned to the stream.", max_digits=12)),
                ('evaporation_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('seepage_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('spill_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('available_af', models.DecimalField(decimal_places=4, help_text='What is left for the fields after the three losses.', max_digits=12)),
                ('own_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="The served fields' own recorded deliveries for the month, taken from what was left before the rest was divided up.", max_digits=12)),
                ('seepage_water_year', models.PositiveIntegerField(blank=True, help_text="Which water year's seepage pool took it.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_of_diversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surface.pointofdiversion')),
                ('seepage_zone', models.ForeignKey(blank=True, help_text="The zone whose seepage pool took this month's seepage; blank when no zone could.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geography.zone')),
            ],
            options={
                'ordering': ['-month', 'point_of_diversion_id'],
            },
        ),
        migrations.CreateModel(
            name='CanalMonthLossEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('point_of_diversion', models.BigIntegerField(blank=True, db_column='point_of_diversion_id', null=True, verbose_name='point of diversion')),
                ('seepage_zone', models.BigIntegerField(blank=True, db_column='seepage_zone_id', null=True, verbose_name='seepage zone')),
                ('id', models.BigIntegerField()),
                ('month', models.DateField(help_text='First of the calendar month.')),
                ('diverted_af', models.DecimalField(decimal_places=4, help_text="The month's direct-use total the split started from: volume less returned to the stream.", max_digits=12)),
                ('evaporation_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('seepage_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('spill_af', models.DecimalField(decimal_places=4, max_digits=12)),
                ('available_af', models.DecimalField(decimal_places=4, help_text='What is left for the fields after the three losses.', max_digits=12)),
                ('own_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="The served fields' own recorded deliveries for the month, taken from what was left before the rest was divided up.", max_digits=12)),
                ('seepage_water_year', models.PositiveIntegerField(blank=True, help_text="Which water year's seepage pool took it.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='surface.canalmonthloss')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='canalmonthloss',
            constraint=models.CheckConstraint(condition=models.Q(('diverted_af', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('evaporation_af'), '+', models.F('seepage_af')), '+', models.F('spill_af')), '+', models.F('available_af')))), name='canal_month_loss_parts_add_up'),
        ),
        migrations.AlterUniqueTogether(
            name='canalmonthloss',
            unique_together={('point_of_diversion', 'month')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='canalmonthloss',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_canalmonthlossevent" ("available_af", "created_at", "diverted_af", "evaporation_af", "id", "month", "own_af", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "seepage_af", "seepage_water_year", "seepage_zone_id", "spill_af") VALUES (NEW."available_af", NEW."created_at", NEW."diverted_af", NEW."evaporation_af", NEW."id", NEW."month", NEW."own_af", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."point_of_diversion_id", NEW."seepage_af", NEW."seepage_water_year", NEW."seepage_zone_id", NEW."spill_af"); RETURN NULL;', hash='b3f032721cb00f84339a87b60ed02597c65d6309', operation='INSERT', pgid='pgtrigger_insert_insert_5720f', table='surface_canalmonthloss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='canalmonthloss',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_canalmonthlossevent" ("available_af", "created_at", "diverted_af", "evaporation_af", "id", "month", "own_af", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "seepage_af", "seepage_water_year", "seepage_zone_id", "spill_af") VALUES (OLD."available_af", OLD."created_at", OLD."diverted_af", OLD."evaporation_af", OLD."id", OLD."month", OLD."own_af", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."point_of_diversion_id", OLD."seepage_af", OLD."seepage_water_year", OLD."seepage_zone_id", OLD."spill_af"); RETURN NULL;', hash='e71ddad49ec53142981aacc1e6a3d5f2f80f5cf8', operation='UPDATE', pgid='pgtrigger_before_update_update_58886', table='surface_canalmonthloss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='canalmonthloss',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "surface_canalmonthlossevent" ("available_af", "created_at", "diverted_af", "evaporation_af", "id", "month", "own_af", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "seepage_af", "seepage_water_year", "seepage_zone_id", "spill_af") VALUES (NEW."available_af", NEW."created_at", NEW."diverted_af", NEW."evaporation_af", NEW."id", NEW."month", NEW."own_af", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."point_of_diversion_id", NEW."seepage_af", NEW."seepage_water_year", NEW."seepage_zone_id", NEW."spill_af"); RETURN NULL;', hash='ab6e4ca53febff93e33df93eb8cd17155791583f', operation='UPDATE', pgid='pgtrigger_update_update_9e4be', table='surface_canalmonthloss', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='canalmonthloss',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "surface_canalmonthlossevent" ("available_af", "created_at", "diverted_af", "evaporation_af", "id", "month", "own_af", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "point_of_diversion_id", "seepage_af", "seepage_water_year", "seepage_zone_id", "spill_af") VALUES (OLD."available_af", OLD."created_at", OLD."diverted_af", OLD."evaporation_af", OLD."id", OLD."month", OLD."own_af", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."point_of_diversion_id", OLD."seepage_af", OLD."seepage_water_year", OLD."seepage_zone_id", OLD."spill_af"); RETURN NULL;', hash='9095fe09233c0d82d1753a97ef2ac2413bd4b6f1', operation='DELETE', pgid='pgtrigger_delete_delete_917a5', table='surface_canalmonthloss', when='AFTER')),
        ),
    ]
