# Generated by Django 5.2.15 on 2026-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0020_canalmonthloss_canalmonthlossevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversionrecord',
            name='method',
            field=models.CharField(blank=True, choices=[('device', 'A measuring device'), ('methodology', 'A measurement methodology on file'), ('alternative_compliance', 'An alternative compliance plan (for example remote sensing)'), ('apportioned', 'Apportioned from a shared aggregate, 934(a)(8)'), ('below_threshold', 'Under 10 acre-feet a year: no standard applies'), ('outage_estimate', 'Estimated during a device outage, 937(b)(4)'), ('estimated_from_use', "Estimated from the fields' crop water use")], help_text="How this number is known, in the state's own words (Water Code 5002(b): 'the method of measurement used'). Blank means not stated.", max_length=30),
        ),
        migrations.AlterField(
            model_name='diversionrecordevent',
            name='method',
            field=models.CharField(blank=True, choices=[('device', 'A measuring device'), ('methodology', 'A measurement methodology on file'), ('alternative_compliance', 'An alternative compliance plan (for example remote sensing)'), ('apportioned', 'Apportioned from a shared aggregate, 934(a)(8)'), ('below_threshold', 'Under 10 acre-feet a year: no standard applies'), ('outage_estimate', 'Estimated during a device outage, 937(b)(4)'), ('estimated_from_use', "Estimated from the fields' crop water use")], help_text="How this number is known, in the state's own words (Water Code 5002(b): 'the method of measurement used'). Blank means not stated.", max_length=30),
        ),
    ]
