# Generated by Django 5.2.15 on 2026-10-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0021_alter_diversionrecord_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofdiversion',
            name='max_rate_cfs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Max rate'),
        ),
        migrations.AlterField(
            model_name='pointofdiversionevent',
            name='max_rate_cfs',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Max rate'),
        ),
        migrations.AlterField(
            model_name='waterright',
            name='calwatrs_pin',
            field=models.CharField(blank=True, help_text='CalWATRS PIN mailed by SWRCB for this water right. The state issues one PIN per right; supplied by the agency, not fetched by OpenH2O.', max_length=50, verbose_name='CalWATRS PIN'),
        ),
        migrations.AlterField(
            model_name='waterright',
            name='max_rate_cfs',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="MAX_DD_APPL in the state's rights list, in cubic feet per second.", max_digits=10, null=True, verbose_name='Max rate'),
        ),
        migrations.AlterField(
            model_name='waterrightevent',
            name='calwatrs_pin',
            field=models.CharField(blank=True, help_text='CalWATRS PIN mailed by SWRCB for this water right. The state issues one PIN per right; supplied by the agency, not fetched by OpenH2O.', max_length=50, verbose_name='CalWATRS PIN'),
        ),
        migrations.AlterField(
            model_name='waterrightevent',
            name='max_rate_cfs',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="MAX_DD_APPL in the state's rights list, in cubic feet per second.", max_digits=10, null=True, verbose_name='Max rate'),
        ),
    ]
