# Generated by Django 5.2.14 on 2026-05-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='observed_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to='standards.observedproperty'),
        ),
        migrations.AddField(
            model_name='sensormeasurement',
            name='observed_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_measurements', to='standards.observedproperty'),
        ),
        migrations.AddField(
            model_name='watermeasurement',
            name='observed_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_measurements', to='standards.observedproperty'),
        ),
    ]
