# Generated by Django 5.2.14 on 2026-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_meterreading_observed_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='quality',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('approved', 'Approved'), ('estimated', 'Estimated')], default='provisional', help_text='Observation quality/status (SensorThings/USGS). Defaults to provisional until a review workflow approves it.', max_length=20),
        ),
        migrations.AddField(
            model_name='sensormeasurement',
            name='quality',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('approved', 'Approved'), ('estimated', 'Estimated')], default='provisional', help_text='Observation quality/status (SensorThings/USGS). Defaults to provisional until a review workflow approves it.', max_length=20),
        ),
    ]
