# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_meterreading_quality_sensormeasurement_quality'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadingEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('meter', models.BigIntegerField(blank=True, db_column='meter_id', null=True, verbose_name='meter')),
                ('observed_property', models.BigIntegerField(blank=True, db_column='observed_property_id', null=True, verbose_name='observed property')),
                ('read_by', models.BigIntegerField(blank=True, db_column='read_by_id', null=True, verbose_name='read by')),
                ('id', models.BigIntegerField()),
                ('reading_date', models.DateTimeField()),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculated_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quality', models.CharField(choices=[('provisional', 'Provisional'), ('approved', 'Approved'), ('estimated', 'Estimated')], default='provisional', help_text='Observation quality/status (SensorThings/USGS). Defaults to provisional until a review workflow approves it.', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterMeasurementEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('observed_property', models.BigIntegerField(blank=True, db_column='observed_property_id', null=True, verbose_name='observed property')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('well', models.BigIntegerField(blank=True, db_column='well_id', null=True, verbose_name='well')),
                ('recorded_by', models.BigIntegerField(blank=True, db_column='recorded_by_id', null=True, verbose_name='recorded by')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('measurement_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('measurement_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('imported', 'Imported')], default='manual', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='meterreading',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "measurements_meterreadingevent" ("calculated_volume", "created_at", "current_value", "id", "meter_id", "notes", "observed_property_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_value", "quality", "read_by_id", "reading_date") VALUES (NEW."calculated_volume", NEW."created_at", NEW."current_value", NEW."id", NEW."meter_id", NEW."notes", NEW."observed_property_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."previous_value", NEW."quality", NEW."read_by_id", NEW."reading_date"); RETURN NULL;', hash='b2fa4f7cf370b28e26393591efe1e46244c1a36e', operation='INSERT', pgid='pgtrigger_insert_insert_65158', table='measurements_meterreading', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='meterreading',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "measurements_meterreadingevent" ("calculated_volume", "created_at", "current_value", "id", "meter_id", "notes", "observed_property_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_value", "quality", "read_by_id", "reading_date") VALUES (OLD."calculated_volume", OLD."created_at", OLD."current_value", OLD."id", OLD."meter_id", OLD."notes", OLD."observed_property_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."previous_value", OLD."quality", OLD."read_by_id", OLD."reading_date"); RETURN NULL;', hash='66c36385f32358ffba71a647747c466b8bcebca2', operation='UPDATE', pgid='pgtrigger_before_update_update_0a65a', table='measurements_meterreading', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='meterreading',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "measurements_meterreadingevent" ("calculated_volume", "created_at", "current_value", "id", "meter_id", "notes", "observed_property_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_value", "quality", "read_by_id", "reading_date") VALUES (NEW."calculated_volume", NEW."created_at", NEW."current_value", NEW."id", NEW."meter_id", NEW."notes", NEW."observed_property_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."previous_value", NEW."quality", NEW."read_by_id", NEW."reading_date"); RETURN NULL;', hash='ad3a23048692e0e80c15309ee88ae1c2a597f0a7', operation='UPDATE', pgid='pgtrigger_update_update_1be0e', table='measurements_meterreading', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='meterreading',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "measurements_meterreadingevent" ("calculated_volume", "created_at", "current_value", "id", "meter_id", "notes", "observed_property_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "previous_value", "quality", "read_by_id", "reading_date") VALUES (OLD."calculated_volume", OLD."created_at", OLD."current_value", OLD."id", OLD."meter_id", OLD."notes", OLD."observed_property_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."previous_value", OLD."quality", OLD."read_by_id", OLD."reading_date"); RETURN NULL;', hash='7f5cbd113a31f34e922eacf28fabba6478c5c91d', operation='DELETE', pgid='pgtrigger_delete_delete_24ebf', table='measurements_meterreading', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watermeasurement',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "measurements_watermeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "name", "notes", "observed_property_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_by_id", "source", "unit", "value", "well_id") VALUES (NEW."created_at", NEW."id", NEW."measurement_date", NEW."measurement_type", NEW."name", NEW."notes", NEW."observed_property_id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."recorded_by_id", NEW."source", NEW."unit", NEW."value", NEW."well_id"); RETURN NULL;', hash='6f20b7664486f06f617579bc748123e615268f9d', operation='INSERT', pgid='pgtrigger_insert_insert_d610e', table='measurements_watermeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watermeasurement',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "measurements_watermeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "name", "notes", "observed_property_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_by_id", "source", "unit", "value", "well_id") VALUES (OLD."created_at", OLD."id", OLD."measurement_date", OLD."measurement_type", OLD."name", OLD."notes", OLD."observed_property_id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."recorded_by_id", OLD."source", OLD."unit", OLD."value", OLD."well_id"); RETURN NULL;', hash='8cd86b88119567afe0cc19645ba8c7e52f5594ba', operation='UPDATE', pgid='pgtrigger_before_update_update_b9456', table='measurements_watermeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watermeasurement',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "measurements_watermeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "name", "notes", "observed_property_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_by_id", "source", "unit", "value", "well_id") VALUES (NEW."created_at", NEW."id", NEW."measurement_date", NEW."measurement_type", NEW."name", NEW."notes", NEW."observed_property_id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."recorded_by_id", NEW."source", NEW."unit", NEW."value", NEW."well_id"); RETURN NULL;', hash='c85b1cfad64f7b5503384932d5d18a757121f018', operation='UPDATE', pgid='pgtrigger_update_update_78ce0', table='measurements_watermeasurement', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watermeasurement',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "measurements_watermeasurementevent" ("created_at", "id", "measurement_date", "measurement_type", "name", "notes", "observed_property_id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "recorded_by_id", "source", "unit", "value", "well_id") VALUES (OLD."created_at", OLD."id", OLD."measurement_date", OLD."measurement_type", OLD."name", OLD."notes", OLD."observed_property_id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."recorded_by_id", OLD."source", OLD."unit", OLD."value", OLD."well_id"); RETURN NULL;', hash='56dac2ca7c4cd63a9e60d9ba42746a6456470184', operation='DELETE', pgid='pgtrigger_delete_delete_78ede', table='measurements_watermeasurement', when='AFTER')),
        ),
        migrations.AddField(
            model_name='meterreadingevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='meterreadingevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='measurements.meterreading'),
        ),
        migrations.AddField(
            model_name='watermeasurementevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='watermeasurementevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='measurements.watermeasurement'),
        ),
    ]
