# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_registration_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('depth_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('capacity_gpm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('destroyed', 'Destroyed'), ('proposed', 'Proposed')], default='active', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_agency', models.CharField(blank=True, max_length=200)),
                ('measurement_frequency', models.CharField(blank=True, max_length=50)),
                ('reference_elevation_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='well_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wells.welltype'),
        ),
        migrations.CreateModel(
            name='WellIrrigatedParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
            options={
                'unique_together': {('well', 'parcel')},
            },
        ),
        migrations.CreateModel(
            name='WellMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.meter')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wells.well')),
            ],
            options={
                'unique_together': {('well', 'meter')},
            },
        ),
    ]
