# Generated by Django 5.2.14 on 2026-05-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='casing_diameter_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='casing_material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='well',
            name='measurement_method',
            field=models.CharField(blank=True, choices=[('certified_meter', 'Certified Meter'), ('unmetered_estimate', 'Unmetered Estimate'), ('power_conversion', 'Power Conversion'), ('et_method', 'ET Method')], max_length=30),
        ),
        migrations.AddField(
            model_name='well',
            name='pump_type',
            field=models.CharField(blank=True, choices=[('submersible', 'Submersible'), ('turbine', 'Turbine'), ('centrifugal', 'Centrifugal'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='well',
            name='screen_bottom_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='screen_top_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='state_well_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='well',
            name='tested_yield_gpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='wcr_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='well',
            name='year_pumping_began',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellmeter',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
