# Generated by Django 5.2.14 on 2026-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_well_casing_diameter_in_well_casing_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringwell',
            name='vertical_datum',
            field=models.CharField(blank=True, choices=[('NAVD88', 'NAVD88'), ('NGVD29', 'NGVD29')], help_text='Vertical datum (NAVD88 / NGVD29) for reference_elevation_ft.', max_length=10),
        ),
        migrations.AddField(
            model_name='well',
            name='usgs_site_id',
            field=models.CharField(blank=True, help_text='USGS NWIS site number (waterdata.usgs.gov), if this well is also a USGS monitoring site.', max_length=50),
        ),
        migrations.AddField(
            model_name='well',
            name='vertical_datum',
            field=models.CharField(blank=True, choices=[('NAVD88', 'NAVD88'), ('NGVD29', 'NGVD29')], help_text='Vertical datum (NAVD88 / NGVD29) the screen-interval depths reference. Required to express depths as elevations.', max_length=10),
        ),
        migrations.AddField(
            model_name='well',
            name='wqx_monitoring_location_id',
            field=models.CharField(blank=True, help_text='EPA WQX MonitoringLocationIdentifier (Water Quality Portal).', max_length=50),
        ),
    ]
