# Generated by Django 5.2.15 on 2026-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_monitoringwell_vertical_datum_well_usgs_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='accuracy_band',
            field=models.CharField(blank=True, choices=[('0-5', '0-5%'), ('5-10', '5-10%'), ('10-20', '10-20%'), ('20-30', '20-30%'), ('over_30', 'Over 30%')], default='', help_text="The accuracy band DWR's annual report table takes for this method; blank when none is stated.", max_length=10),
        ),
        migrations.AddField(
            model_name='well',
            name='dwr_direct_or_estimate',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('estimate', 'Estimate')], default='', help_text='Whether the extraction method above is a direct measurement or an estimate.', max_length=10),
        ),
        migrations.AddField(
            model_name='well',
            name='dwr_extraction_method',
            field=models.CharField(blank=True, choices=[('meters', 'Meters'), ('electrical_records', 'Electrical Records'), ('land_use', 'Land Use'), ('groundwater_model', 'Groundwater Model'), ('other', 'Other')], default='', help_text="Which of DWR's five annual-report method rows this well's extraction is measured under (23 CCR 356.2(b)(2)).", max_length=30),
        ),
    ]
