# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('wells', '0005_derive_dwr_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('well_type', models.BigIntegerField(blank=True, db_column='well_type_id', null=True, verbose_name='well type')),
                ('id', models.BigIntegerField()),
                ('well_registration_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('depth_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('capacity_gpm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('destroyed', 'Destroyed'), ('proposed', 'Proposed')], default='active', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('year_pumping_began', models.IntegerField(blank=True, null=True)),
                ('measurement_method', models.CharField(blank=True, choices=[('certified_meter', 'Certified Meter'), ('unmetered_estimate', 'Unmetered Estimate'), ('power_conversion', 'Power Conversion'), ('et_method', 'ET Method')], max_length=30)),
                ('dwr_extraction_method', models.CharField(blank=True, choices=[('meters', 'Meters'), ('electrical_records', 'Electrical Records'), ('land_use', 'Land Use'), ('groundwater_model', 'Groundwater Model'), ('other', 'Other')], default='', help_text="Which of DWR's five annual-report method rows this well's extraction is measured under (23 CCR 356.2(b)(2)).", max_length=30)),
                ('dwr_direct_or_estimate', models.CharField(blank=True, choices=[('direct', 'Direct'), ('estimate', 'Estimate')], default='', help_text='Whether the extraction method above is a direct measurement or an estimate.', max_length=10)),
                ('accuracy_band', models.CharField(blank=True, choices=[('0-5', '0-5%'), ('5-10', '5-10%'), ('10-20', '10-20%'), ('20-30', '20-30%'), ('over_30', 'Over 30%')], default='', help_text="The accuracy band DWR's annual report table takes for this method; blank when none is stated.", max_length=10)),
                ('wcr_number', models.CharField(blank=True, max_length=50)),
                ('state_well_number', models.CharField(blank=True, max_length=50)),
                ('usgs_site_id', models.CharField(blank=True, help_text='USGS NWIS site number (waterdata.usgs.gov), if this well is also a USGS monitoring site.', max_length=50)),
                ('wqx_monitoring_location_id', models.CharField(blank=True, help_text='EPA WQX MonitoringLocationIdentifier (Water Quality Portal).', max_length=50)),
                ('vertical_datum', models.CharField(blank=True, choices=[('NAVD88', 'NAVD88'), ('NGVD29', 'NGVD29')], help_text='Vertical datum (NAVD88 / NGVD29) the screen-interval depths reference. Required to express depths as elevations.', max_length=10)),
                ('casing_diameter_in', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('casing_material', models.CharField(blank=True, max_length=50)),
                ('screen_top_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('screen_bottom_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tested_yield_gpm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pump_type', models.CharField(blank=True, choices=[('submersible', 'Submersible'), ('turbine', 'Turbine'), ('centrifugal', 'Centrifugal'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellIrrigatedParcelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('well', models.BigIntegerField(blank=True, db_column='well_id', null=True, verbose_name='well')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('id', models.BigIntegerField()),
                ('fraction', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellMeterEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('well', models.BigIntegerField(blank=True, db_column='well_id', null=True, verbose_name='well')),
                ('meter', models.BigIntegerField(blank=True, db_column='meter_id', null=True, verbose_name='meter')),
                ('id', models.BigIntegerField()),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='well',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellevent" ("accuracy_band", "capacity_gpm", "casing_diameter_in", "casing_material", "created_at", "depth_ft", "dwr_direct_or_estimate", "dwr_extraction_method", "id", "measurement_method", "name", "notes", "owner_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pump_type", "screen_bottom_ft", "screen_top_ft", "state_well_number", "status", "tested_yield_gpm", "usgs_site_id", "vertical_datum", "wcr_number", "well_registration_id", "well_type_id", "wqx_monitoring_location_id", "year_pumping_began") VALUES (NEW."accuracy_band", NEW."capacity_gpm", NEW."casing_diameter_in", NEW."casing_material", NEW."created_at", NEW."depth_ft", NEW."dwr_direct_or_estimate", NEW."dwr_extraction_method", NEW."id", NEW."measurement_method", NEW."name", NEW."notes", NEW."owner_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."pump_type", NEW."screen_bottom_ft", NEW."screen_top_ft", NEW."state_well_number", NEW."status", NEW."tested_yield_gpm", NEW."usgs_site_id", NEW."vertical_datum", NEW."wcr_number", NEW."well_registration_id", NEW."well_type_id", NEW."wqx_monitoring_location_id", NEW."year_pumping_began"); RETURN NULL;', hash='125512062f29fd46f0045165fa397e1038119fb6', operation='INSERT', pgid='pgtrigger_insert_insert_9aa0a', table='wells_well', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='well',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."accuracy_band" IS DISTINCT FROM (NEW."accuracy_band") OR OLD."capacity_gpm" IS DISTINCT FROM (NEW."capacity_gpm") OR OLD."casing_diameter_in" IS DISTINCT FROM (NEW."casing_diameter_in") OR OLD."casing_material" IS DISTINCT FROM (NEW."casing_material") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."depth_ft" IS DISTINCT FROM (NEW."depth_ft") OR OLD."dwr_direct_or_estimate" IS DISTINCT FROM (NEW."dwr_direct_or_estimate") OR OLD."dwr_extraction_method" IS DISTINCT FROM (NEW."dwr_extraction_method") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."measurement_method" IS DISTINCT FROM (NEW."measurement_method") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."owner_name" IS DISTINCT FROM (NEW."owner_name") OR OLD."pump_type" IS DISTINCT FROM (NEW."pump_type") OR OLD."screen_bottom_ft" IS DISTINCT FROM (NEW."screen_bottom_ft") OR OLD."screen_top_ft" IS DISTINCT FROM (NEW."screen_top_ft") OR OLD."state_well_number" IS DISTINCT FROM (NEW."state_well_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."tested_yield_gpm" IS DISTINCT FROM (NEW."tested_yield_gpm") OR OLD."usgs_site_id" IS DISTINCT FROM (NEW."usgs_site_id") OR OLD."vertical_datum" IS DISTINCT FROM (NEW."vertical_datum") OR OLD."wcr_number" IS DISTINCT FROM (NEW."wcr_number") OR OLD."well_registration_id" IS DISTINCT FROM (NEW."well_registration_id") OR OLD."well_type_id" IS DISTINCT FROM (NEW."well_type_id") OR OLD."wqx_monitoring_location_id" IS DISTINCT FROM (NEW."wqx_monitoring_location_id") OR OLD."year_pumping_began" IS DISTINCT FROM (NEW."year_pumping_began"))', func='INSERT INTO "wells_wellevent" ("accuracy_band", "capacity_gpm", "casing_diameter_in", "casing_material", "created_at", "depth_ft", "dwr_direct_or_estimate", "dwr_extraction_method", "id", "measurement_method", "name", "notes", "owner_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pump_type", "screen_bottom_ft", "screen_top_ft", "state_well_number", "status", "tested_yield_gpm", "usgs_site_id", "vertical_datum", "wcr_number", "well_registration_id", "well_type_id", "wqx_monitoring_location_id", "year_pumping_began") VALUES (OLD."accuracy_band", OLD."capacity_gpm", OLD."casing_diameter_in", OLD."casing_material", OLD."created_at", OLD."depth_ft", OLD."dwr_direct_or_estimate", OLD."dwr_extraction_method", OLD."id", OLD."measurement_method", OLD."name", OLD."notes", OLD."owner_name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."pump_type", OLD."screen_bottom_ft", OLD."screen_top_ft", OLD."state_well_number", OLD."status", OLD."tested_yield_gpm", OLD."usgs_site_id", OLD."vertical_datum", OLD."wcr_number", OLD."well_registration_id", OLD."well_type_id", OLD."wqx_monitoring_location_id", OLD."year_pumping_began"); RETURN NULL;', hash='33fdd0b19d2b8d3e2eb5479c2a80880a5f194f29', operation='UPDATE', pgid='pgtrigger_before_update_update_e4ce1', table='wells_well', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='well',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."accuracy_band" IS DISTINCT FROM (NEW."accuracy_band") OR OLD."capacity_gpm" IS DISTINCT FROM (NEW."capacity_gpm") OR OLD."casing_diameter_in" IS DISTINCT FROM (NEW."casing_diameter_in") OR OLD."casing_material" IS DISTINCT FROM (NEW."casing_material") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."depth_ft" IS DISTINCT FROM (NEW."depth_ft") OR OLD."dwr_direct_or_estimate" IS DISTINCT FROM (NEW."dwr_direct_or_estimate") OR OLD."dwr_extraction_method" IS DISTINCT FROM (NEW."dwr_extraction_method") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."measurement_method" IS DISTINCT FROM (NEW."measurement_method") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."owner_name" IS DISTINCT FROM (NEW."owner_name") OR OLD."pump_type" IS DISTINCT FROM (NEW."pump_type") OR OLD."screen_bottom_ft" IS DISTINCT FROM (NEW."screen_bottom_ft") OR OLD."screen_top_ft" IS DISTINCT FROM (NEW."screen_top_ft") OR OLD."state_well_number" IS DISTINCT FROM (NEW."state_well_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."tested_yield_gpm" IS DISTINCT FROM (NEW."tested_yield_gpm") OR OLD."usgs_site_id" IS DISTINCT FROM (NEW."usgs_site_id") OR OLD."vertical_datum" IS DISTINCT FROM (NEW."vertical_datum") OR OLD."wcr_number" IS DISTINCT FROM (NEW."wcr_number") OR OLD."well_registration_id" IS DISTINCT FROM (NEW."well_registration_id") OR OLD."well_type_id" IS DISTINCT FROM (NEW."well_type_id") OR OLD."wqx_monitoring_location_id" IS DISTINCT FROM (NEW."wqx_monitoring_location_id") OR OLD."year_pumping_began" IS DISTINCT FROM (NEW."year_pumping_began"))', func='INSERT INTO "wells_wellevent" ("accuracy_band", "capacity_gpm", "casing_diameter_in", "casing_material", "created_at", "depth_ft", "dwr_direct_or_estimate", "dwr_extraction_method", "id", "measurement_method", "name", "notes", "owner_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pump_type", "screen_bottom_ft", "screen_top_ft", "state_well_number", "status", "tested_yield_gpm", "usgs_site_id", "vertical_datum", "wcr_number", "well_registration_id", "well_type_id", "wqx_monitoring_location_id", "year_pumping_began") VALUES (NEW."accuracy_band", NEW."capacity_gpm", NEW."casing_diameter_in", NEW."casing_material", NEW."created_at", NEW."depth_ft", NEW."dwr_direct_or_estimate", NEW."dwr_extraction_method", NEW."id", NEW."measurement_method", NEW."name", NEW."notes", NEW."owner_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."pump_type", NEW."screen_bottom_ft", NEW."screen_top_ft", NEW."state_well_number", NEW."status", NEW."tested_yield_gpm", NEW."usgs_site_id", NEW."vertical_datum", NEW."wcr_number", NEW."well_registration_id", NEW."well_type_id", NEW."wqx_monitoring_location_id", NEW."year_pumping_began"); RETURN NULL;', hash='4ea8258d492ca5b95b2fea7264689c8ac316516b', operation='UPDATE', pgid='pgtrigger_update_update_e7f8c', table='wells_well', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='well',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellevent" ("accuracy_band", "capacity_gpm", "casing_diameter_in", "casing_material", "created_at", "depth_ft", "dwr_direct_or_estimate", "dwr_extraction_method", "id", "measurement_method", "name", "notes", "owner_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pump_type", "screen_bottom_ft", "screen_top_ft", "state_well_number", "status", "tested_yield_gpm", "usgs_site_id", "vertical_datum", "wcr_number", "well_registration_id", "well_type_id", "wqx_monitoring_location_id", "year_pumping_began") VALUES (OLD."accuracy_band", OLD."capacity_gpm", OLD."casing_diameter_in", OLD."casing_material", OLD."created_at", OLD."depth_ft", OLD."dwr_direct_or_estimate", OLD."dwr_extraction_method", OLD."id", OLD."measurement_method", OLD."name", OLD."notes", OLD."owner_name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."pump_type", OLD."screen_bottom_ft", OLD."screen_top_ft", OLD."state_well_number", OLD."status", OLD."tested_yield_gpm", OLD."usgs_site_id", OLD."vertical_datum", OLD."wcr_number", OLD."well_registration_id", OLD."well_type_id", OLD."wqx_monitoring_location_id", OLD."year_pumping_began"); RETURN NULL;', hash='4585c9d25c29781a55deeaca5d266847e75c2cdd', operation='DELETE', pgid='pgtrigger_delete_delete_d4a99', table='wells_well', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellirrigatedparcel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellirrigatedparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "well_id") VALUES (NEW."fraction", NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."well_id"); RETURN NULL;', hash='0b4a2758b1faf554d4774e517d0281e75d52efe2', operation='INSERT', pgid='pgtrigger_insert_insert_ea4e4', table='wells_wellirrigatedparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellirrigatedparcel',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "wells_wellirrigatedparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "well_id") VALUES (OLD."fraction", OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."well_id"); RETURN NULL;', hash='9035e47d489150602d517f2dc154d9131f9f056d', operation='UPDATE', pgid='pgtrigger_before_update_update_c577a', table='wells_wellirrigatedparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellirrigatedparcel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "wells_wellirrigatedparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "well_id") VALUES (NEW."fraction", NEW."id", NEW."notes", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."well_id"); RETURN NULL;', hash='821dbb6eed06127e613f90229ad620eddf9c3676', operation='UPDATE', pgid='pgtrigger_update_update_c1724', table='wells_wellirrigatedparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellirrigatedparcel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellirrigatedparcelevent" ("fraction", "id", "notes", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "well_id") VALUES (OLD."fraction", OLD."id", OLD."notes", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."well_id"); RETURN NULL;', hash='0cf0d5ecdc015df587907db1961c8ca147eb5dfb', operation='DELETE', pgid='pgtrigger_delete_delete_4ef29', table='wells_wellirrigatedparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellmeter',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellmeterevent" ("calibration_date", "id", "installed_date", "is_current", "meter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "well_id") VALUES (NEW."calibration_date", NEW."id", NEW."installed_date", NEW."is_current", NEW."meter_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."removed_date", NEW."well_id"); RETURN NULL;', hash='871ded0a8c5f320deabcc528f34ae0c7457b02ce', operation='INSERT', pgid='pgtrigger_insert_insert_b87c2', table='wells_wellmeter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellmeter',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "wells_wellmeterevent" ("calibration_date", "id", "installed_date", "is_current", "meter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "well_id") VALUES (OLD."calibration_date", OLD."id", OLD."installed_date", OLD."is_current", OLD."meter_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."removed_date", OLD."well_id"); RETURN NULL;', hash='6ed7c734bc6487391695dd53608f170234d386a3', operation='UPDATE', pgid='pgtrigger_before_update_update_ff7b2', table='wells_wellmeter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellmeter',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "wells_wellmeterevent" ("calibration_date", "id", "installed_date", "is_current", "meter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "well_id") VALUES (NEW."calibration_date", NEW."id", NEW."installed_date", NEW."is_current", NEW."meter_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."removed_date", NEW."well_id"); RETURN NULL;', hash='a7a364df9b9fbe096a7a87606726a4125c04d7bb', operation='UPDATE', pgid='pgtrigger_update_update_69627', table='wells_wellmeter', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wellmeter',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "wells_wellmeterevent" ("calibration_date", "id", "installed_date", "is_current", "meter_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "well_id") VALUES (OLD."calibration_date", OLD."id", OLD."installed_date", OLD."is_current", OLD."meter_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."removed_date", OLD."well_id"); RETURN NULL;', hash='4b91f5f3599c164bb548510d8d9128a50d30c864', operation='DELETE', pgid='pgtrigger_delete_delete_41ca6', table='wells_wellmeter', when='AFTER')),
        ),
        migrations.AddField(
            model_name='wellevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wellevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='wells.well'),
        ),
        migrations.AddField(
            model_name='wellirrigatedparcelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wellirrigatedparcelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='wells.wellirrigatedparcel'),
        ),
        migrations.AddField(
            model_name='wellmeterevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wellmeterevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='wells.wellmeter'),
        ),
    ]
