# Generated by Django 5.2.15 on 2026-07-19 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0002_datastream'),
        ('wells', '0003_monitoringwell_vertical_datum_well_usgs_site_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_code', models.CharField(help_text='Primary Station Code, the composite {pwsid}_{facility_id}_{point_number} exactly as DDW publishes it. Stored verbatim — never derived on read.', max_length=60, unique=True)),
                ('name', models.CharField(blank=True, help_text='e.g. "LCR Tap Sample", "DBPR Sample".', max_length=200)),
                ('point_type', models.CharField(blank=True, choices=[('source', 'Source'), ('entry_point', 'Entry Point'), ('distribution', 'Distribution'), ('tap', 'Tap')], max_length=20)),
            ],
            options={
                'verbose_name': 'Sampling Point',
                'ordering': ['ps_code'],
            },
        ),
        migrations.CreateModel(
            name='WaterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwsid', models.CharField(help_text='Public Water System ID, e.g. CA1910067. THE persistent identifier; joins the Water Data Standard crosswalk.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('activity_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Proposed')], default='A', max_length=1)),
                ('pws_type', models.CharField(blank=True, choices=[('CWS', 'Community water system'), ('NTNCWS', 'Non-transient non-community water system'), ('TNCWS', 'Transient non-community water system')], help_text='Federal PWS type.', max_length=10)),
                ('state_classification', models.CharField(blank=True, choices=[('C', 'Community'), ('NC', 'Noncommunity (transient)'), ('NTNC', 'Nontransient-noncommunity'), ('NP', 'NonPublic')], help_text='State classification. CA adds NP (non-public).', max_length=4)),
                ('owner_type', models.CharField(blank=True, choices=[('F', 'Federal government'), ('L', 'Local government'), ('M', 'Public/Private'), ('N', 'Native American'), ('P', 'Private'), ('S', 'State government')], max_length=1)),
                ('primary_source_code', models.CharField(blank=True, choices=[('GW', 'Ground water'), ('GWP', 'Ground water purchased'), ('GU', 'Ground water under the influence of surface water'), ('GUP', 'Purchased ground water under the influence of surface water'), ('SW', 'Surface water'), ('SWP', 'Surface water purchased')], max_length=3)),
                ('is_wholesaler', models.BooleanField(default=False)),
                ('is_school_or_daycare', models.BooleanField(default=False)),
                ('population_residential', models.IntegerField(blank=True, null=True)),
                ('population_non_transient', models.IntegerField(blank=True, null=True)),
                ('population_transient', models.IntegerField(blank=True, null=True)),
                ('connections_agricultural', models.IntegerField(blank=True, null=True)),
                ('connections_combined', models.IntegerField(blank=True, null=True)),
                ('connections_commercial', models.IntegerField(blank=True, null=True)),
                ('connections_industrial', models.IntegerField(blank=True, null=True)),
                ('connections_residential', models.IntegerField(blank=True, null=True)),
                ('regulating_agency', models.CharField(blank=True, help_text='DDW district office or Local Primacy Agency; NM: NMED DWB.', max_length=100)),
                ('seller_pwsid', models.CharField(blank=True, help_text='Consecutive-system link: the PWSID this system buys from.', max_length=20)),
            ],
            options={
                'verbose_name': 'Water System',
                'ordering': ['pwsid'],
            },
        ),
        migrations.CreateModel(
            name='Analyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddw_code', models.CharField(blank=True, help_text="DDW's four-digit analyte code. NULL when no verifiable code is known — never fabricate one.", max_length=4, null=True, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('storet_code', models.CharField(blank=True, help_text='Legacy STORET code (historical files).', max_length=10)),
                ('observed_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drinking_analytes', to='standards.observedproperty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('mcl', 'Maximum Contaminant Level'), ('secondary_mcl', 'Secondary MCL'), ('mrdl', 'Maximum Residual Disinfectant Level'), ('action_level', 'Action Level'), ('tt_trigger', 'Treatment Technique Trigger'), ('dlr', 'Detection Limit for Reporting'), ('notification_level', 'Notification Level')], max_length=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=16)),
                ('unit', models.CharField(help_text='e.g. mg/L, ug/L, pCi/L.', max_length=20)),
                ('jurisdiction', models.CharField(help_text='e.g. "federal", "CA", "NM".', max_length=20)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, help_text='NULL = still in force. Inclusive.', null=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='drinking.analyte')),
            ],
            options={
                'verbose_name': 'Regulatory Limit',
                'ordering': ['analyte', 'limit_type', 'jurisdiction', '-effective_start'],
            },
        ),
        migrations.CreateModel(
            name='SampleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('sample_time', models.TimeField(blank=True, null=True)),
                ('sample_type', models.CharField(choices=[('routine', 'Routine'), ('repeat', 'Repeat'), ('confirmation', 'Confirmation'), ('special', 'Special')], default='routine', max_length=20)),
                ('collector', models.CharField(blank=True, max_length=200)),
                ('chain_of_custody_note', models.TextField(blank=True)),
                ('sampling_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='drinking.samplingpoint')),
            ],
            options={
                'verbose_name': 'Sample Event',
                'ordering': ['-sample_date', 'sampling_point'],
            },
        ),
        migrations.CreateModel(
            name='SystemFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(help_text='State-assigned facility ID.', max_length=30)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('facility_type', models.CharField(blank=True, choices=[('CC', 'Consecutive Connection'), ('CH', 'Common Headers'), ('CS', 'Cistern'), ('CW', 'Clear Well'), ('DS', 'Distribution System'), ('IG', 'Infiltration Gallery'), ('IN', 'Intake'), ('NN', 'Non-piped, Non-Purchased'), ('NP', 'Non-piped, Purchased'), ('OT', 'Other'), ('PC', 'Pressure Control'), ('PF', 'Pump Facility'), ('RC', 'Roof Catchment'), ('RS', 'Reservoir'), ('SI', 'Surface Impoundment'), ('SP', 'Spring'), ('SS', 'Sampling Station'), ('ST', 'Storage'), ('TM', 'Transmission Main (Manifold)'), ('TP', 'Treatment Plant'), ('WH', 'Wellhead'), ('WL', 'Well')], max_length=2)),
                ('activity_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Proposed')], default='A', max_length=1)),
                ('is_source', models.BooleanField(default=False)),
                ('water_type', models.CharField(blank=True, choices=[('GW', 'Ground water'), ('SW', 'Surface water'), ('GU', 'Ground water under the influence of surface water')], max_length=2)),
                ('availability', models.CharField(blank=True, choices=[('E', 'Emergency'), ('I', 'Interim'), ('P', 'Permanent'), ('O', 'Other'), ('S', 'Seasonal'), ('U', 'Unknown')], max_length=1)),
                ('well', models.ForeignKey(blank=True, help_text='The physical well this facility is, when it is a well.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drinking_facilities', to='wells.well')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='drinking.watersystem')),
            ],
            options={
                'verbose_name': 'System Facility',
                'verbose_name_plural': 'System Facilities',
                'ordering': ['system', 'facility_id'],
                'unique_together': {('system', 'facility_id')},
            },
        ),
        migrations.AddField(
            model_name='samplingpoint',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_points', to='drinking.systemfacility'),
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_kind', models.CharField(choices=[('numeric', 'Numeric'), ('presence_absence', 'Presence / Absence')], default='numeric', max_length=20)),
                ('result_value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('presence', models.BooleanField(blank=True, help_text='True = present. Presence/absence results only.', null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('less_than_rl', models.BooleanField(default=False, help_text="Non-detect flag (DDW 'Less Than Reporting Level' = Y).")),
                ('reporting_level', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('counting_error', models.DecimalField(blank=True, decimal_places=6, help_text='Statistical variability of the analysis; radionuclides.', max_digits=16, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('lab_cert_no', models.CharField(blank=True, help_text='ELAP certification number.', max_length=20)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='drinking.analyte')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='drinking.sampleevent')),
            ],
            options={
                'verbose_name': 'Sample Result',
                'ordering': ['-event__sample_date', 'analyte'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('result_kind', 'numeric'), _negated=True), ('presence__isnull', True), _connector='OR'), name='drinking_numeric_result_has_no_presence'), models.CheckConstraint(condition=models.Q(models.Q(('result_kind', 'presence_absence'), _negated=True), models.Q(('result_value__isnull', True), ('less_than_rl', False)), _connector='OR'), name='drinking_presence_result_has_no_value')],
            },
        ),
    ]
