# Generated by Django 5.2.15 on 2026-07-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvirofactsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwsid', models.CharField(db_index=True, max_length=20)),
                ('table_name', models.CharField(help_text='WATER_SYSTEM | WATER_SYSTEM_FACILITY | GEOGRAPHIC_AREA', max_length=40)),
                ('payload', models.JSONField(help_text='The raw Envirofacts response, verbatim')),
                ('queried_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Envirofacts cache entry',
                'verbose_name_plural': 'Envirofacts cache entries',
                'unique_together': {('pwsid', 'table_name')},
            },
        ),
    ]
