# Generated by Django 5.2.15 on 2026-07-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0002_envirofactscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfacility',
            name='epa_facility_id',
            field=models.CharField(blank=True, db_index=True, help_text="EPA's own facility ID. Provenance only — never a PS Code segment. See .planning/phases/79-envirofacts-adapter/79-RESEARCH.md.", max_length=20),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='mailing_address_line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='mailing_address_line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='mailing_state',
            field=models.CharField(blank=True, help_text="The ADMINISTRATOR'S MAILING state, NOT the primacy state. EPA's WATER_SYSTEM.state_code is the address on file: PWSID 083090017 is a Colorado system (primacy_agency_code 08) whose state_code is CA because its administrator's address is in Anaheim. Never filter jurisdiction by this field — use primacy agency.", max_length=2),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='mailing_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='systemfacility',
            name='facility_id',
            field=models.CharField(help_text="State-assigned facility ID — the segment DDW's PS Codes are built from (CA1010001_010_010). From EPA this is state_facility_id, NEVER EPA's own facility_id. Not always numeric: DST is real.", max_length=30),
        ),
    ]
