# Generated by Django 5.2.15 on 2026-07-29 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0004_sampleevent_triggered_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfacility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Published location of the facility. From GAMA, which publishes coordinates for source wells only — most facilities have none, and NULL is the honest value.', null=True, srid=4326),
        ),
    ]
