# Generated by Django 5.2.15 on 2026-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0006_backfill_facility_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystem',
            name='population_served_total',
            field=models.IntegerField(blank=True, help_text='EPA WATER_SYSTEM.population_served_count — the published aggregate. The residential / non-transient / transient split beside it comes from the state eAR, not from EPA; a system may have this total with no split, or a split with no total.', null=True),
        ),
        migrations.AddField(
            model_name='watersystem',
            name='service_connections_total',
            field=models.IntegerField(blank=True, help_text='EPA WATER_SYSTEM.service_connections_count — the published aggregate. The per-use-type connection breakdown beside it comes from the state eAR, not from EPA; a system may have this total with no breakdown, or a breakdown with no total.', null=True),
        ),
    ]
