# Generated by Django 5.2.15 on 2026-09-17 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0007_watersystem_population_served_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfacility',
            name='epa_facility_id',
            field=models.CharField(blank=True, db_index=True, help_text="EPA's own facility ID. Provenance only; never a PS Code segment.", max_length=20),
        ),
        migrations.AlterField(
            model_name='systemfacility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Published location of the facility, from GAMA, which publishes coordinates for source wells only; most facilities have none.', null=True, srid=4326),
        ),
    ]
