# Generated by Django 5.2.15 on 2026-09-22 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0008_literary_sentence_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='1 to 12. Null means the year was reported as one figure -- the eAR puts that in the January row, so the importer keeps it as month 1 and sets annual_in_january rather than leaving this blank.', null=True)),
                ('type_code', models.CharField(choices=[('GW', 'Groundwater'), ('SW', 'Surface water'), ('PU', 'Purchased'), ('SO', 'Sold'), ('NP', 'Non-potable'), ('RC', 'Recycled')], max_length=2)),
                ('volume_as_reported', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_as_reported', models.CharField(choices=[('G', 'Gallons'), ('MG', 'Million gallons'), ('AF', 'Acre-feet'), ('CCF', 'Hundred cubic feet (CCF)')], max_length=3)),
                ('volume_gallons', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('volume_acre_feet', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('provenance', models.CharField(choices=[('ear_export', 'State eAR export'), ('operator_log', "Operator's monthly log"), ('typed', 'Typed in')], max_length=20)),
                ('annual_in_january', models.BooleanField(default=False, help_text='This January row stands for the whole year; no other month of this year and type appears in the file it came from.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, help_text="The source, when the operator's log names one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='drinking.systemfacility')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='drinking.watersystem')),
            ],
            options={
                'verbose_name': 'System Production',
                'verbose_name_plural': 'System Production',
                'ordering': ['system', '-year', 'month', 'type_code'],
                'unique_together': {('system', 'year', 'month', 'type_code', 'facility')},
            },
        ),
    ]
