# Generated by Django 5.2.15 on 2026-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0009_system_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfacility',
            name='added_by_hand',
            field=models.BooleanField(default=False, help_text="Entered on this deployment's facility form rather than written from the federal record."),
        ),
        migrations.AddField(
            model_name='systemfacility',
            name='local_name',
            field=models.CharField(blank=True, help_text='What the operator calls it: Cedar Well 02.', max_length=200),
        ),
    ]
