# Generated by Django 5.2.15 on 2026-09-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0010_facility_local_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(blank=True, help_text='What the row covers when it is not one analyte: coliform, nitrate, chlorine residual, siting plan.', max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('every_3_years', 'Every 3 years'), ('every_9_years', 'Every 9 years'), ('every_10_years', 'Every 10 years'), ('other', 'Other')], max_length=20)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, help_text='Typed by the operator; never computed from the frequency.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rows', to='drinking.analyte')),
                ('sampling_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_rows', to='drinking.samplingpoint')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_schedule', to='drinking.watersystem')),
            ],
            options={
                'verbose_name': 'Sampling Schedule Row',
                'verbose_name_plural': 'Sampling Schedule',
                'ordering': [models.OrderBy(models.F('next_due'), nulls_last=True), 'pk'],
            },
        ),
    ]
