# Generated by Django 5.2.15 on 2026-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0011_sampling_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleresult',
            name='dlr_as_reported',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="The DLR column of the laboratory's file for this row, as reported, in the row's own units.", max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='limits_file_date',
            field=models.DateField(blank=True, help_text='The date that file was imported.', null=True),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='limits_source_file',
            field=models.CharField(blank=True, help_text='The file the two limits above arrived in.', max_length=255),
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='mcl_as_reported',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="The MCL column of the laboratory's file for this row, as reported, in the row's own units.", max_digits=16, null=True),
        ),
    ]
