# Generated by Django 5.2.15 on 2026-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0012_limits_as_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemproduction',
            name='type_code',
            field=models.CharField(choices=[('GW', 'Groundwater'), ('SW', 'Surface water'), ('PU', 'Purchased'), ('SO', 'Sold'), ('NP', 'Non-potable'), ('RC', 'Recycled'), ('NS', 'Non-potable sold')], max_length=2),
        ),
    ]
