# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinking', '0013_production_type_non_potable_sold'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleResultEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('event', models.BigIntegerField(blank=True, db_column='event_id', null=True, verbose_name='event')),
                ('analyte', models.BigIntegerField(blank=True, db_column='analyte_id', null=True, verbose_name='analyte')),
                ('id', models.BigIntegerField()),
                ('result_kind', models.CharField(choices=[('numeric', 'Numeric'), ('presence_absence', 'Presence / Absence')], default='numeric', max_length=20)),
                ('result_value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('presence', models.BooleanField(blank=True, help_text='True = present. Presence/absence results only.', null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('less_than_rl', models.BooleanField(default=False, help_text="Non-detect flag (DDW 'Less Than Reporting Level' = Y).")),
                ('reporting_level', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('counting_error', models.DecimalField(blank=True, decimal_places=6, help_text='Statistical variability of the analysis; radionuclides.', max_digits=16, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('lab_cert_no', models.CharField(blank=True, help_text='ELAP certification number.', max_length=20)),
                ('mcl_as_reported', models.DecimalField(blank=True, decimal_places=6, help_text="The MCL column of the laboratory's file for this row, as reported, in the row's own units.", max_digits=16, null=True)),
                ('dlr_as_reported', models.DecimalField(blank=True, decimal_places=6, help_text="The DLR column of the laboratory's file for this row, as reported, in the row's own units.", max_digits=16, null=True)),
                ('limits_source_file', models.CharField(blank=True, help_text='The file the two limits above arrived in.', max_length=255)),
                ('limits_file_date', models.DateField(blank=True, help_text='The date that file was imported.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingScheduleEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('system', models.BigIntegerField(blank=True, db_column='system_id', null=True, verbose_name='system')),
                ('sampling_point', models.BigIntegerField(blank=True, db_column='sampling_point_id', null=True, verbose_name='sampling point')),
                ('analyte', models.BigIntegerField(blank=True, db_column='analyte_id', null=True, verbose_name='analyte')),
                ('id', models.BigIntegerField()),
                ('group_label', models.CharField(blank=True, help_text='What the row covers when it is not one analyte: coliform, nitrate, chlorine residual, siting plan.', max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('every_3_years', 'Every 3 years'), ('every_9_years', 'Every 9 years'), ('every_10_years', 'Every 10 years'), ('other', 'Other')], max_length=20)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, help_text='Typed by the operator; never computed from the frequency.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemFacilityEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('system', models.BigIntegerField(blank=True, db_column='system_id', null=True, verbose_name='system')),
                ('well', models.BigIntegerField(blank=True, db_column='well_id', null=True, verbose_name='well')),
                ('id', models.BigIntegerField()),
                ('facility_id', models.CharField(help_text="State-assigned facility ID — the segment DDW's PS Codes are built from (CA1010001_010_010). From EPA this is state_facility_id, NEVER EPA's own facility_id. Not always numeric: DST is real.", max_length=30)),
                ('epa_facility_id', models.CharField(blank=True, help_text="EPA's own facility ID. Provenance only; never a PS Code segment.", max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('local_name', models.CharField(blank=True, help_text='What the operator calls it: Cedar Well 02.', max_length=200)),
                ('added_by_hand', models.BooleanField(default=False, help_text="Entered on this deployment's facility form rather than written from the federal record.")),
                ('facility_type', models.CharField(blank=True, choices=[('CC', 'Consecutive Connection'), ('CH', 'Common Headers'), ('CS', 'Cistern'), ('CW', 'Clear Well'), ('DS', 'Distribution System'), ('IG', 'Infiltration Gallery'), ('IN', 'Intake'), ('NN', 'Non-piped, Non-Purchased'), ('NP', 'Non-piped, Purchased'), ('OT', 'Other'), ('PC', 'Pressure Control'), ('PF', 'Pump Facility'), ('RC', 'Roof Catchment'), ('RS', 'Reservoir'), ('SI', 'Surface Impoundment'), ('SP', 'Spring'), ('SS', 'Sampling Station'), ('ST', 'Storage'), ('TM', 'Transmission Main (Manifold)'), ('TP', 'Treatment Plant'), ('WH', 'Wellhead'), ('WL', 'Well')], max_length=2)),
                ('activity_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Proposed')], default='A', max_length=1)),
                ('is_source', models.BooleanField(default=False)),
                ('water_type', models.CharField(blank=True, choices=[('GW', 'Ground water'), ('SW', 'Surface water'), ('GU', 'Ground water under the influence of surface water')], max_length=2)),
                ('availability', models.CharField(blank=True, choices=[('E', 'Emergency'), ('I', 'Interim'), ('P', 'Permanent'), ('O', 'Other'), ('S', 'Seasonal'), ('U', 'Unknown')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemProductionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('system', models.BigIntegerField(blank=True, db_column='system_id', null=True, verbose_name='system')),
                ('facility', models.BigIntegerField(blank=True, db_column='facility_id', null=True, verbose_name='facility')),
                ('id', models.BigIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='1 to 12. Null means the year was reported as one figure -- the eAR puts that in the January row, so the importer keeps it as month 1 and sets annual_in_january rather than leaving this blank.', null=True)),
                ('type_code', models.CharField(choices=[('GW', 'Groundwater'), ('SW', 'Surface water'), ('PU', 'Purchased'), ('SO', 'Sold'), ('NP', 'Non-potable'), ('RC', 'Recycled'), ('NS', 'Non-potable sold')], max_length=2)),
                ('volume_as_reported', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_as_reported', models.CharField(choices=[('G', 'Gallons'), ('MG', 'Million gallons'), ('AF', 'Acre-feet'), ('CCF', 'Hundred cubic feet (CCF)')], max_length=3)),
                ('volume_gallons', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('volume_acre_feet', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('provenance', models.CharField(choices=[('ear_export', 'State eAR export'), ('operator_log', "Operator's monthly log"), ('typed', 'Typed in')], max_length=20)),
                ('annual_in_january', models.BooleanField(default=False, help_text='This January row stands for the whole year; no other month of this year and type appears in the file it came from.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterSystemEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('pwsid', models.CharField(help_text='Public Water System ID, e.g. CA1910067. THE persistent identifier; joins the Water Data Standard crosswalk.', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('activity_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('P', 'Proposed')], default='A', max_length=1)),
                ('pws_type', models.CharField(blank=True, choices=[('CWS', 'Community water system'), ('NTNCWS', 'Non-transient non-community water system'), ('TNCWS', 'Transient non-community water system')], help_text='Federal PWS type.', max_length=10)),
                ('state_classification', models.CharField(blank=True, choices=[('C', 'Community'), ('NC', 'Noncommunity (transient)'), ('NTNC', 'Nontransient-noncommunity'), ('NP', 'NonPublic')], help_text='State classification. CA adds NP (non-public).', max_length=4)),
                ('owner_type', models.CharField(blank=True, choices=[('F', 'Federal government'), ('L', 'Local government'), ('M', 'Public/Private'), ('N', 'Native American'), ('P', 'Private'), ('S', 'State government')], max_length=1)),
                ('primary_source_code', models.CharField(blank=True, choices=[('GW', 'Ground water'), ('GWP', 'Ground water purchased'), ('GU', 'Ground water under the influence of surface water'), ('GUP', 'Purchased ground water under the influence of surface water'), ('SW', 'Surface water'), ('SWP', 'Surface water purchased')], max_length=3)),
                ('is_wholesaler', models.BooleanField(default=False)),
                ('is_school_or_daycare', models.BooleanField(default=False)),
                ('population_served_total', models.IntegerField(blank=True, help_text='EPA WATER_SYSTEM.population_served_count — the published aggregate. The residential / non-transient / transient split beside it comes from the state eAR, not from EPA; a system may have this total with no split, or a split with no total.', null=True)),
                ('service_connections_total', models.IntegerField(blank=True, help_text='EPA WATER_SYSTEM.service_connections_count — the published aggregate. The per-use-type connection breakdown beside it comes from the state eAR, not from EPA; a system may have this total with no breakdown, or a breakdown with no total.', null=True)),
                ('population_residential', models.IntegerField(blank=True, null=True)),
                ('population_non_transient', models.IntegerField(blank=True, null=True)),
                ('population_transient', models.IntegerField(blank=True, null=True)),
                ('connections_agricultural', models.IntegerField(blank=True, null=True)),
                ('connections_combined', models.IntegerField(blank=True, null=True)),
                ('connections_commercial', models.IntegerField(blank=True, null=True)),
                ('connections_industrial', models.IntegerField(blank=True, null=True)),
                ('connections_residential', models.IntegerField(blank=True, null=True)),
                ('mailing_address_line1', models.CharField(blank=True, max_length=100)),
                ('mailing_address_line2', models.CharField(blank=True, max_length=100)),
                ('mailing_city', models.CharField(blank=True, max_length=100)),
                ('mailing_state', models.CharField(blank=True, help_text="The ADMINISTRATOR'S MAILING state, NOT the primacy state. EPA's WATER_SYSTEM.state_code is the address on file: PWSID 083090017 is a Colorado system (primacy_agency_code 08) whose state_code is CA because its administrator's address is in Anaheim. Never filter jurisdiction by this field — use primacy agency.", max_length=2)),
                ('mailing_zip', models.CharField(blank=True, max_length=10)),
                ('regulating_agency', models.CharField(blank=True, help_text='DDW district office or Local Primacy Agency; NM: NMED DWB.', max_length=100)),
                ('seller_pwsid', models.CharField(blank=True, help_text='Consecutive-system link: the PWSID this system buys from.', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sampleresult',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_sampleresultevent" ("analysis_date", "analyte_id", "counting_error", "dlr_as_reported", "event_id", "id", "lab_cert_no", "lab_name", "less_than_rl", "limits_file_date", "limits_source_file", "mcl_as_reported", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "presence", "reporting_level", "result_kind", "result_value", "unit") VALUES (NEW."analysis_date", NEW."analyte_id", NEW."counting_error", NEW."dlr_as_reported", NEW."event_id", NEW."id", NEW."lab_cert_no", NEW."lab_name", NEW."less_than_rl", NEW."limits_file_date", NEW."limits_source_file", NEW."mcl_as_reported", NEW."method", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."presence", NEW."reporting_level", NEW."result_kind", NEW."result_value", NEW."unit"); RETURN NULL;', hash='5b31b92bad88024c4f9cb3e86a541b3e73a637f2', operation='INSERT', pgid='pgtrigger_insert_insert_66199', table='drinking_sampleresult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sampleresult',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "drinking_sampleresultevent" ("analysis_date", "analyte_id", "counting_error", "dlr_as_reported", "event_id", "id", "lab_cert_no", "lab_name", "less_than_rl", "limits_file_date", "limits_source_file", "mcl_as_reported", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "presence", "reporting_level", "result_kind", "result_value", "unit") VALUES (OLD."analysis_date", OLD."analyte_id", OLD."counting_error", OLD."dlr_as_reported", OLD."event_id", OLD."id", OLD."lab_cert_no", OLD."lab_name", OLD."less_than_rl", OLD."limits_file_date", OLD."limits_source_file", OLD."mcl_as_reported", OLD."method", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."presence", OLD."reporting_level", OLD."result_kind", OLD."result_value", OLD."unit"); RETURN NULL;', hash='3a30f91049ebc27a94c66b9d377dcdf5a2151b2a', operation='UPDATE', pgid='pgtrigger_before_update_update_6612e', table='drinking_sampleresult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sampleresult',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "drinking_sampleresultevent" ("analysis_date", "analyte_id", "counting_error", "dlr_as_reported", "event_id", "id", "lab_cert_no", "lab_name", "less_than_rl", "limits_file_date", "limits_source_file", "mcl_as_reported", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "presence", "reporting_level", "result_kind", "result_value", "unit") VALUES (NEW."analysis_date", NEW."analyte_id", NEW."counting_error", NEW."dlr_as_reported", NEW."event_id", NEW."id", NEW."lab_cert_no", NEW."lab_name", NEW."less_than_rl", NEW."limits_file_date", NEW."limits_source_file", NEW."mcl_as_reported", NEW."method", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."presence", NEW."reporting_level", NEW."result_kind", NEW."result_value", NEW."unit"); RETURN NULL;', hash='99197f14b0005fd4a4c8ff13a7559be82dd6edf7', operation='UPDATE', pgid='pgtrigger_update_update_9fdc2', table='drinking_sampleresult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sampleresult',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_sampleresultevent" ("analysis_date", "analyte_id", "counting_error", "dlr_as_reported", "event_id", "id", "lab_cert_no", "lab_name", "less_than_rl", "limits_file_date", "limits_source_file", "mcl_as_reported", "method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "presence", "reporting_level", "result_kind", "result_value", "unit") VALUES (OLD."analysis_date", OLD."analyte_id", OLD."counting_error", OLD."dlr_as_reported", OLD."event_id", OLD."id", OLD."lab_cert_no", OLD."lab_name", OLD."less_than_rl", OLD."limits_file_date", OLD."limits_source_file", OLD."mcl_as_reported", OLD."method", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."presence", OLD."reporting_level", OLD."result_kind", OLD."result_value", OLD."unit"); RETURN NULL;', hash='7b5a93811b9a6e4b911274e2762f20dc2774d9f3', operation='DELETE', pgid='pgtrigger_delete_delete_bb7a9', table='drinking_sampleresult', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='samplingschedule',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_samplingscheduleevent" ("analyte_id", "created_at", "frequency", "group_label", "id", "last_done", "next_due", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sampling_point_id", "system_id") VALUES (NEW."analyte_id", NEW."created_at", NEW."frequency", NEW."group_label", NEW."id", NEW."last_done", NEW."next_due", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sampling_point_id", NEW."system_id"); RETURN NULL;', hash='b59ce939beec1aed6b1282ea3184e26c249f6f93', operation='INSERT', pgid='pgtrigger_insert_insert_83763', table='drinking_samplingschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='samplingschedule',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."analyte_id" IS DISTINCT FROM (NEW."analyte_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."frequency" IS DISTINCT FROM (NEW."frequency") OR OLD."group_label" IS DISTINCT FROM (NEW."group_label") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_done" IS DISTINCT FROM (NEW."last_done") OR OLD."next_due" IS DISTINCT FROM (NEW."next_due") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."sampling_point_id" IS DISTINCT FROM (NEW."sampling_point_id") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id"))', func='INSERT INTO "drinking_samplingscheduleevent" ("analyte_id", "created_at", "frequency", "group_label", "id", "last_done", "next_due", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sampling_point_id", "system_id") VALUES (OLD."analyte_id", OLD."created_at", OLD."frequency", OLD."group_label", OLD."id", OLD."last_done", OLD."next_due", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."sampling_point_id", OLD."system_id"); RETURN NULL;', hash='06293848c3c25d604e570654766f98236d15e7fa', operation='UPDATE', pgid='pgtrigger_before_update_update_21eb1', table='drinking_samplingschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='samplingschedule',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."analyte_id" IS DISTINCT FROM (NEW."analyte_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."frequency" IS DISTINCT FROM (NEW."frequency") OR OLD."group_label" IS DISTINCT FROM (NEW."group_label") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_done" IS DISTINCT FROM (NEW."last_done") OR OLD."next_due" IS DISTINCT FROM (NEW."next_due") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."sampling_point_id" IS DISTINCT FROM (NEW."sampling_point_id") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id"))', func='INSERT INTO "drinking_samplingscheduleevent" ("analyte_id", "created_at", "frequency", "group_label", "id", "last_done", "next_due", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sampling_point_id", "system_id") VALUES (NEW."analyte_id", NEW."created_at", NEW."frequency", NEW."group_label", NEW."id", NEW."last_done", NEW."next_due", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sampling_point_id", NEW."system_id"); RETURN NULL;', hash='51d38711df2a828317bfbcc16c511f71f408f41f', operation='UPDATE', pgid='pgtrigger_update_update_10a73', table='drinking_samplingschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='samplingschedule',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_samplingscheduleevent" ("analyte_id", "created_at", "frequency", "group_label", "id", "last_done", "next_due", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sampling_point_id", "system_id") VALUES (OLD."analyte_id", OLD."created_at", OLD."frequency", OLD."group_label", OLD."id", OLD."last_done", OLD."next_due", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."sampling_point_id", OLD."system_id"); RETURN NULL;', hash='e5e0e3e5847d7a77d2a7b373a36b6fd3489936db', operation='DELETE', pgid='pgtrigger_delete_delete_6b296', table='drinking_samplingschedule', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemfacility',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_systemfacilityevent" ("activity_status", "added_by_hand", "availability", "epa_facility_id", "facility_id", "facility_type", "id", "is_source", "local_name", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "system_id", "water_type", "well_id") VALUES (NEW."activity_status", NEW."added_by_hand", NEW."availability", NEW."epa_facility_id", NEW."facility_id", NEW."facility_type", NEW."id", NEW."is_source", NEW."local_name", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."system_id", NEW."water_type", NEW."well_id"); RETURN NULL;', hash='62b5ba8c4e94af2b2fcf74d27a1936b5372629f5', operation='INSERT', pgid='pgtrigger_insert_insert_12607', table='drinking_systemfacility', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemfacility',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."activity_status" IS DISTINCT FROM (NEW."activity_status") OR OLD."added_by_hand" IS DISTINCT FROM (NEW."added_by_hand") OR OLD."availability" IS DISTINCT FROM (NEW."availability") OR OLD."epa_facility_id" IS DISTINCT FROM (NEW."epa_facility_id") OR OLD."facility_id" IS DISTINCT FROM (NEW."facility_id") OR OLD."facility_type" IS DISTINCT FROM (NEW."facility_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_source" IS DISTINCT FROM (NEW."is_source") OR OLD."local_name" IS DISTINCT FROM (NEW."local_name") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id") OR OLD."water_type" IS DISTINCT FROM (NEW."water_type") OR OLD."well_id" IS DISTINCT FROM (NEW."well_id"))', func='INSERT INTO "drinking_systemfacilityevent" ("activity_status", "added_by_hand", "availability", "epa_facility_id", "facility_id", "facility_type", "id", "is_source", "local_name", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "system_id", "water_type", "well_id") VALUES (OLD."activity_status", OLD."added_by_hand", OLD."availability", OLD."epa_facility_id", OLD."facility_id", OLD."facility_type", OLD."id", OLD."is_source", OLD."local_name", OLD."name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."system_id", OLD."water_type", OLD."well_id"); RETURN NULL;', hash='edc75912b3c448a6cc35c182928a4d1f7beb9b65', operation='UPDATE', pgid='pgtrigger_before_update_update_71ab5', table='drinking_systemfacility', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemfacility',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."activity_status" IS DISTINCT FROM (NEW."activity_status") OR OLD."added_by_hand" IS DISTINCT FROM (NEW."added_by_hand") OR OLD."availability" IS DISTINCT FROM (NEW."availability") OR OLD."epa_facility_id" IS DISTINCT FROM (NEW."epa_facility_id") OR OLD."facility_id" IS DISTINCT FROM (NEW."facility_id") OR OLD."facility_type" IS DISTINCT FROM (NEW."facility_type") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_source" IS DISTINCT FROM (NEW."is_source") OR OLD."local_name" IS DISTINCT FROM (NEW."local_name") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id") OR OLD."water_type" IS DISTINCT FROM (NEW."water_type") OR OLD."well_id" IS DISTINCT FROM (NEW."well_id"))', func='INSERT INTO "drinking_systemfacilityevent" ("activity_status", "added_by_hand", "availability", "epa_facility_id", "facility_id", "facility_type", "id", "is_source", "local_name", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "system_id", "water_type", "well_id") VALUES (NEW."activity_status", NEW."added_by_hand", NEW."availability", NEW."epa_facility_id", NEW."facility_id", NEW."facility_type", NEW."id", NEW."is_source", NEW."local_name", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."system_id", NEW."water_type", NEW."well_id"); RETURN NULL;', hash='ff9ff24155f73a9ce424f4892e9d95a3c1311dc2', operation='UPDATE', pgid='pgtrigger_update_update_51d92', table='drinking_systemfacility', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemfacility',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_systemfacilityevent" ("activity_status", "added_by_hand", "availability", "epa_facility_id", "facility_id", "facility_type", "id", "is_source", "local_name", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "system_id", "water_type", "well_id") VALUES (OLD."activity_status", OLD."added_by_hand", OLD."availability", OLD."epa_facility_id", OLD."facility_id", OLD."facility_type", OLD."id", OLD."is_source", OLD."local_name", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."system_id", OLD."water_type", OLD."well_id"); RETURN NULL;', hash='0a8d11440663765d671cfbd71d19661f7ebaecba', operation='DELETE', pgid='pgtrigger_delete_delete_bbebd', table='drinking_systemfacility', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemproduction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_systemproductionevent" ("annual_in_january", "created_at", "facility_id", "id", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "provenance", "system_id", "type_code", "unit_as_reported", "volume_acre_feet", "volume_as_reported", "volume_gallons", "year") VALUES (NEW."annual_in_january", NEW."created_at", NEW."facility_id", NEW."id", NEW."month", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."provenance", NEW."system_id", NEW."type_code", NEW."unit_as_reported", NEW."volume_acre_feet", NEW."volume_as_reported", NEW."volume_gallons", NEW."year"); RETURN NULL;', hash='614d49263ee647dc0f77a4b42a49341c77886beb', operation='INSERT', pgid='pgtrigger_insert_insert_ec12a', table='drinking_systemproduction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemproduction',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."annual_in_january" IS DISTINCT FROM (NEW."annual_in_january") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."facility_id" IS DISTINCT FROM (NEW."facility_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."month" IS DISTINCT FROM (NEW."month") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."provenance" IS DISTINCT FROM (NEW."provenance") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id") OR OLD."type_code" IS DISTINCT FROM (NEW."type_code") OR OLD."unit_as_reported" IS DISTINCT FROM (NEW."unit_as_reported") OR OLD."volume_acre_feet" IS DISTINCT FROM (NEW."volume_acre_feet") OR OLD."volume_as_reported" IS DISTINCT FROM (NEW."volume_as_reported") OR OLD."volume_gallons" IS DISTINCT FROM (NEW."volume_gallons") OR OLD."year" IS DISTINCT FROM (NEW."year"))', func='INSERT INTO "drinking_systemproductionevent" ("annual_in_january", "created_at", "facility_id", "id", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "provenance", "system_id", "type_code", "unit_as_reported", "volume_acre_feet", "volume_as_reported", "volume_gallons", "year") VALUES (OLD."annual_in_january", OLD."created_at", OLD."facility_id", OLD."id", OLD."month", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."provenance", OLD."system_id", OLD."type_code", OLD."unit_as_reported", OLD."volume_acre_feet", OLD."volume_as_reported", OLD."volume_gallons", OLD."year"); RETURN NULL;', hash='ac942476f5aea74bf085baab730fc737f4d8e1c5', operation='UPDATE', pgid='pgtrigger_before_update_update_f9141', table='drinking_systemproduction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemproduction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."annual_in_january" IS DISTINCT FROM (NEW."annual_in_january") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."facility_id" IS DISTINCT FROM (NEW."facility_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."month" IS DISTINCT FROM (NEW."month") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."provenance" IS DISTINCT FROM (NEW."provenance") OR OLD."system_id" IS DISTINCT FROM (NEW."system_id") OR OLD."type_code" IS DISTINCT FROM (NEW."type_code") OR OLD."unit_as_reported" IS DISTINCT FROM (NEW."unit_as_reported") OR OLD."volume_acre_feet" IS DISTINCT FROM (NEW."volume_acre_feet") OR OLD."volume_as_reported" IS DISTINCT FROM (NEW."volume_as_reported") OR OLD."volume_gallons" IS DISTINCT FROM (NEW."volume_gallons") OR OLD."year" IS DISTINCT FROM (NEW."year"))', func='INSERT INTO "drinking_systemproductionevent" ("annual_in_january", "created_at", "facility_id", "id", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "provenance", "system_id", "type_code", "unit_as_reported", "volume_acre_feet", "volume_as_reported", "volume_gallons", "year") VALUES (NEW."annual_in_january", NEW."created_at", NEW."facility_id", NEW."id", NEW."month", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."provenance", NEW."system_id", NEW."type_code", NEW."unit_as_reported", NEW."volume_acre_feet", NEW."volume_as_reported", NEW."volume_gallons", NEW."year"); RETURN NULL;', hash='1755d6434a0418be48a845695bfb4600278f1bbf', operation='UPDATE', pgid='pgtrigger_update_update_9f584', table='drinking_systemproduction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='systemproduction',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_systemproductionevent" ("annual_in_january", "created_at", "facility_id", "id", "month", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "provenance", "system_id", "type_code", "unit_as_reported", "volume_acre_feet", "volume_as_reported", "volume_gallons", "year") VALUES (OLD."annual_in_january", OLD."created_at", OLD."facility_id", OLD."id", OLD."month", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."provenance", OLD."system_id", OLD."type_code", OLD."unit_as_reported", OLD."volume_acre_feet", OLD."volume_as_reported", OLD."volume_gallons", OLD."year"); RETURN NULL;', hash='eae56259c2134be6f51d3783aa1928572e878e71', operation='DELETE', pgid='pgtrigger_delete_delete_92e2f', table='drinking_systemproduction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watersystem',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_watersystemevent" ("activity_status", "connections_agricultural", "connections_combined", "connections_commercial", "connections_industrial", "connections_residential", "id", "is_school_or_daycare", "is_wholesaler", "mailing_address_line1", "mailing_address_line2", "mailing_city", "mailing_state", "mailing_zip", "name", "owner_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "population_non_transient", "population_residential", "population_served_total", "population_transient", "primary_source_code", "pws_type", "pwsid", "regulating_agency", "seller_pwsid", "service_connections_total", "state_classification") VALUES (NEW."activity_status", NEW."connections_agricultural", NEW."connections_combined", NEW."connections_commercial", NEW."connections_industrial", NEW."connections_residential", NEW."id", NEW."is_school_or_daycare", NEW."is_wholesaler", NEW."mailing_address_line1", NEW."mailing_address_line2", NEW."mailing_city", NEW."mailing_state", NEW."mailing_zip", NEW."name", NEW."owner_type", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."population_non_transient", NEW."population_residential", NEW."population_served_total", NEW."population_transient", NEW."primary_source_code", NEW."pws_type", NEW."pwsid", NEW."regulating_agency", NEW."seller_pwsid", NEW."service_connections_total", NEW."state_classification"); RETURN NULL;', hash='e382ca03dbcac865ce99bb8eddb6b234bcf42120', operation='INSERT', pgid='pgtrigger_insert_insert_d6fcf', table='drinking_watersystem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watersystem',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "drinking_watersystemevent" ("activity_status", "connections_agricultural", "connections_combined", "connections_commercial", "connections_industrial", "connections_residential", "id", "is_school_or_daycare", "is_wholesaler", "mailing_address_line1", "mailing_address_line2", "mailing_city", "mailing_state", "mailing_zip", "name", "owner_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "population_non_transient", "population_residential", "population_served_total", "population_transient", "primary_source_code", "pws_type", "pwsid", "regulating_agency", "seller_pwsid", "service_connections_total", "state_classification") VALUES (OLD."activity_status", OLD."connections_agricultural", OLD."connections_combined", OLD."connections_commercial", OLD."connections_industrial", OLD."connections_residential", OLD."id", OLD."is_school_or_daycare", OLD."is_wholesaler", OLD."mailing_address_line1", OLD."mailing_address_line2", OLD."mailing_city", OLD."mailing_state", OLD."mailing_zip", OLD."name", OLD."owner_type", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."population_non_transient", OLD."population_residential", OLD."population_served_total", OLD."population_transient", OLD."primary_source_code", OLD."pws_type", OLD."pwsid", OLD."regulating_agency", OLD."seller_pwsid", OLD."service_connections_total", OLD."state_classification"); RETURN NULL;', hash='a3b357689ba8003a82be643f87e4c86182ddd723', operation='UPDATE', pgid='pgtrigger_before_update_update_f6489', table='drinking_watersystem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watersystem',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "drinking_watersystemevent" ("activity_status", "connections_agricultural", "connections_combined", "connections_commercial", "connections_industrial", "connections_residential", "id", "is_school_or_daycare", "is_wholesaler", "mailing_address_line1", "mailing_address_line2", "mailing_city", "mailing_state", "mailing_zip", "name", "owner_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "population_non_transient", "population_residential", "population_served_total", "population_transient", "primary_source_code", "pws_type", "pwsid", "regulating_agency", "seller_pwsid", "service_connections_total", "state_classification") VALUES (NEW."activity_status", NEW."connections_agricultural", NEW."connections_combined", NEW."connections_commercial", NEW."connections_industrial", NEW."connections_residential", NEW."id", NEW."is_school_or_daycare", NEW."is_wholesaler", NEW."mailing_address_line1", NEW."mailing_address_line2", NEW."mailing_city", NEW."mailing_state", NEW."mailing_zip", NEW."name", NEW."owner_type", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."population_non_transient", NEW."population_residential", NEW."population_served_total", NEW."population_transient", NEW."primary_source_code", NEW."pws_type", NEW."pwsid", NEW."regulating_agency", NEW."seller_pwsid", NEW."service_connections_total", NEW."state_classification"); RETURN NULL;', hash='061c70dc339c46a7d650cc2363d8bb7d3157f337', operation='UPDATE', pgid='pgtrigger_update_update_f8724', table='drinking_watersystem', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watersystem',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "drinking_watersystemevent" ("activity_status", "connections_agricultural", "connections_combined", "connections_commercial", "connections_industrial", "connections_residential", "id", "is_school_or_daycare", "is_wholesaler", "mailing_address_line1", "mailing_address_line2", "mailing_city", "mailing_state", "mailing_zip", "name", "owner_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "population_non_transient", "population_residential", "population_served_total", "population_transient", "primary_source_code", "pws_type", "pwsid", "regulating_agency", "seller_pwsid", "service_connections_total", "state_classification") VALUES (OLD."activity_status", OLD."connections_agricultural", OLD."connections_combined", OLD."connections_commercial", OLD."connections_industrial", OLD."connections_residential", OLD."id", OLD."is_school_or_daycare", OLD."is_wholesaler", OLD."mailing_address_line1", OLD."mailing_address_line2", OLD."mailing_city", OLD."mailing_state", OLD."mailing_zip", OLD."name", OLD."owner_type", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."population_non_transient", OLD."population_residential", OLD."population_served_total", OLD."population_transient", OLD."primary_source_code", OLD."pws_type", OLD."pwsid", OLD."regulating_agency", OLD."seller_pwsid", OLD."service_connections_total", OLD."state_classification"); RETURN NULL;', hash='61435ab5560e63d45ae552d1c86e2b2e4b85e76c', operation='DELETE', pgid='pgtrigger_delete_delete_20486', table='drinking_watersystem', when='AFTER')),
        ),
        migrations.AddField(
            model_name='sampleresultevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='sampleresultevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='drinking.sampleresult'),
        ),
        migrations.AddField(
            model_name='samplingscheduleevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='samplingscheduleevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='drinking.samplingschedule'),
        ),
        migrations.AddField(
            model_name='systemfacilityevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='systemfacilityevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='drinking.systemfacility'),
        ),
        migrations.AddField(
            model_name='systemproductionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='systemproductionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='drinking.systemproduction'),
        ),
        migrations.AddField(
            model_name='watersystemevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='watersystemevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='drinking.watersystem'),
        ),
    ]
