# Generated by Django 5.2.14 on 2026-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('database', 'Database'), ('disk', 'Disk'), ('sync_freshness', 'Sync Freshness'), ('ledger_integrity', 'Ledger Integrity'), ('orphans', 'Orphans'), ('ssl', 'SSL'), ('docker', 'Docker'), ('migrations', 'Migrations')], max_length=50)),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
