# Generated by Django 5.2.15 on 2026-07-18 23:31
#
# Choices-only change (math eval 2026-07-18, item 9). Django emits an AlterField
# for any choices edit, but choices are validated in Python, never in Postgres —
# this issues no column change and needs no backfill. Contrast
# accounting/0015_calculationrun_period_start, where the auto-generated migration
# was NOT sufficient on its own.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckresult',
            name='category',
            field=models.CharField(choices=[('database', 'Database'), ('disk', 'Disk'), ('sync_freshness', 'Sync Freshness'), ('ledger_integrity', 'Ledger Integrity'), ('orphans', 'Orphans'), ('cache_duplication', 'Cache Duplication'), ('pod_fractions', 'POD Fractions'), ('unallocated_delivery', 'Unallocated Delivery'), ('period_alignment', 'Period Alignment'), ('et_meter_agreement', 'ET / Meter Agreement'), ('ssl', 'SSL'), ('docker', 'Docker'), ('migrations', 'Migrations')], max_length=50),
        ),
    ]
