# Generated by Django 5.2.15 on 2026-07-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_healthcheckresult_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckresult',
            name='status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('skipped', 'Skipped')], max_length=10),
        ),
    ]
