# Generated by Django 5.2.15 on 2026-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_healthcheckresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckresult',
            name='category',
            field=models.CharField(choices=[('database', 'Database'), ('disk', 'Disk'), ('sync_freshness', 'Sync Freshness'), ('ledger_integrity', 'Ledger Integrity'), ('orphans', 'Orphans'), ('cache_duplication', 'Cache Duplication'), ('pod_fractions', 'POD Fractions'), ('unallocated_delivery', 'Unallocated Delivery'), ('period_alignment', 'Period Alignment'), ('et_meter_agreement', 'ET / Meter Agreement'), ('ssl', 'SSL'), ('docker', 'Docker'), ('migrations', 'Migrations'), ('calculation', 'Calculation')], max_length=50),
        ),
    ]
