# Generated by Django 5.2.14 on 2026-05-24 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('geography', '0001_initial'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationplan',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.zone'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationplan',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.reportingperiod'),
        ),
        migrations.AddField(
            model_name='wateraccountparcel',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='wateraccountparcel',
            name='reporting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.reportingperiod'),
        ),
        migrations.AddField(
            model_name='wateraccountparcel',
            name='water_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.wateraccount'),
        ),
        migrations.AddField(
            model_name='allocationplan',
            name='water_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.watertype'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='reporting_period_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='wateraccountparcel',
            unique_together={('water_account', 'parcel', 'reporting_period')},
        ),
        migrations.AlterUniqueTogether(
            name='allocationplan',
            unique_together={('zone', 'water_type', 'reporting_period')},
        ),
    ]
