# Generated by Django 5.2.14 on 2026-06-01 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_allocationplan_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_type', models.ForeignKey(blank=True, help_text='Reserved for future per-water-type scoping; unused in 38-02.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.watertype')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('et_gross', 'Gross ET'), ('subtract_effective_precip', 'Subtract effective precipitation'), ('subtract_surface_water', 'Subtract surface water delivered'), ('facility_only_zero', 'Zero out facility-only parcels'), ('clamp_floor', 'Clamp at floor')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('label', models.CharField(help_text='Human-readable name for the audit trail.', max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounting.calculationplan')),
            ],
            options={
                'ordering': ['plan', 'order'],
                'unique_together': {('plan', 'order')},
            },
        ),
    ]
