# Generated by Django 5.2.14 on 2026-06-01 02:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_calculationplan_calculationstep'),
        ('parcels', '0004_alter_parcelledger_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_period', models.CharField(help_text='Month the surplus was banked, as YYYY-MM.', max_length=7)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Surplus banked (acre-feet, positive). The principal — never mutated.', max_digits=12)),
                ('origin', models.CharField(choices=[('precip_surplus', 'Precip surplus'), ('allocation_carryover', 'Allocation carryover')], default='precip_surplus', max_length=24)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Per-period geometric decay (0 = no decay; >=1 = gone after one period).', max_digits=5)),
                ('expires_period', models.CharField(blank=True, help_text='Month at/after which the credit is dead, as YYYY-MM. Null = never expires.', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
            ],
            options={
                'ordering': ['origin_period'],
            },
        ),
        migrations.CreateModel(
            name='WaterCreditDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_period', models.CharField(help_text='Month the draw was applied, as YYYY-MM.', max_length=7)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Depreciated value drawn in this period (acre-feet, positive).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='accounting.watercredit')),
            ],
            options={
                'ordering': ['draw_period'],
            },
        ),
    ]
