# Generated by Django 5.2.14 on 2026-06-01 03:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_watercredit_watercreditdraw'),
        ('parcels', '0004_alter_parcelledger_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Month, as YYYY-MM.', max_length=7)),
                ('gross_et_af', models.DecimalField(decimal_places=4, help_text="Chain's starting gross ET magnitude (positive AF).", max_digits=12)),
                ('effective_precip_af', models.DecimalField(blank=True, decimal_places=4, help_text='Effective precipitation subtracted (AF); null if no precip step ran.', max_digits=12, null=True)),
                ('surface_water_af', models.DecimalField(blank=True, decimal_places=4, help_text='Surface water subtracted (AF); null if no surface-water step ran.', max_digits=12, null=True)),
                ('banked_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Surplus deposited as a WaterCredit this period (AF).', max_digits=12)),
                ('drawn_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Credit drawn down to reduce the bill this period (AF).', max_digits=12)),
                ('final_af', models.DecimalField(decimal_places=4, help_text='Final billable magnitude (POSITIVE; equals -ledger.amount_acre_feet).', max_digits=12)),
                ('breakdown', models.JSONField(default=list, help_text='The evaluate_chain per-step list, stored verbatim.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
