# Generated by Django 5.2.14 on 2026-06-01 14:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_calculationrun'),
        ('geography', '0003_boundary_basin_code_boundary_huc_zone_basin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCarryover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_year', models.PositiveIntegerField(help_text='Year this carry-over applies TO (opening-balance year), labelled by the calendar year it ends in.')),
                ('source_water_year', models.PositiveIntegerField(blank=True, help_text='The closed water year this was rolled forward from (normally water_year - 1). Provenance for the audit trail.', null=True)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Signed carry-over (acre-feet): + surplus carried forward, − debt borrowed against this year.', max_digits=12)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Per-period geometric decay of a carried-forward SURPLUS (0 = no decay). A debt is never depreciated.', max_digits=5)),
                ('expires_period', models.CharField(blank=True, help_text='Month at/after which the carried surplus is dead, as YYYY-MM. Null = never expires.', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.watertype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.zone')),
            ],
            options={
                'verbose_name': 'Allocation carryover',
                'verbose_name_plural': 'Allocation carryovers',
                'ordering': ['-water_year', 'zone', 'water_type'],
                'unique_together': {('zone', 'water_type', 'water_year')},
            },
        ),
    ]
