# Generated by Django 5.2.14 on 2026-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_allocationcarryover'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='config_hash',
            field=models.CharField(blank=True, default='', help_text='sha256[:12] of the ordered enabled steps + config — the methodology fingerprint behind this number.', max_length=12),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='methodology_plan_id',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of the CalculationPlan id in force at run time.', null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='methodology_plan_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the plan name in force at run time.', max_length=200),
        ),
    ]
