# Generated by Django 5.2.14 on 2026-06-04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_allocationcarryover_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='net_consumptive_use_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Net consumptive use = gross ET − effective precip (positive AF). The source-agnostic spine quantity, recorded for every parcel with ET regardless of supply source or whether a well exists.', max_digits=12),
        ),
    ]
