# Generated by Django 5.2.14 on 2026-06-04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_calculationrun_net_consumptive_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='residual_disposition',
            field=models.CharField(choices=[('groundwater', 'Groundwater extraction'), ('unmet_demand', 'Unmet demand / unallocated')], default='groundwater', help_text='How the ET − precip − surface residual was resolved: written as a calculated groundwater extraction (the parcel has a well) or recorded as unmet demand (no well — under-irrigation or a surface-allocation error).', max_length=20),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='unmet_demand_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Positive shortfall (ET − precip − surface) on a parcel with no well: under-irrigation or a surface-allocation error. Recorded explicitly, NEVER written as a calculated groundwater row.', max_digits=12),
        ),
    ]
