# Generated by Django 5.2.14 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_calculationrun_residual_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrun',
            name='residual_disposition',
            field=models.CharField(choices=[('groundwater', 'Groundwater extraction'), ('unmet_demand', 'Unmet demand / unallocated'), ('metered', 'Metered extraction (authoritative)')], default='groundwater', help_text='How the ET − precip − surface residual was resolved: written as a calculated groundwater extraction (the parcel has a well), recorded as unmet demand (no well — under-irrigation or a surface-allocation error), or marked metered (the parcel carries an authoritative meter reading that owns its groundwater — the run is an ET reference value, no calculated row).', max_length=20),
        ),
    ]
