# Generated by Django 5.2.14 on 2026-06-08 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_calculationrun_metered_disposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationplan',
            options={'verbose_name': 'Allocation Plan', 'verbose_name_plural': 'Allocation Plans'},
        ),
        migrations.AlterField(
            model_name='allocationplan',
            name='allocation_acre_feet',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Allocation (AF)'),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='net_consumptive_use_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Net consumptive use = gross ET − effective precip (positive AF) — an ET-based estimate used where meters are absent. This is distinct from the calculation-chain residual, which goes a step further and also subtracts surface water; the two 'net consumptive use' senses are not the same number. A source-agnostic quantity, recorded for every parcel with ET regardless of supply source or whether a well exists.", max_digits=12),
        ),
    ]
