# Generated by Django 5.2.15 on 2026-07-18 21:05

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_allocationplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.Func(models.F('start_date'), models.F('end_date'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='reporting_period_no_overlap'),
        ),
    ]
