# Generated by Django 5.2.15 on 2026-07-18 23:00

from django.db import migrations, models


def backfill_period_start(apps, schema_editor):
    """Derive period_start for every existing run.

    WITHOUT this, every historical CalculationRun keeps period_start=NULL and is
    INVISIBLE to the new date-based period selector — balances and filed totals
    would silently drop to zero for all prior months. This backfill is the
    load-bearing half of the migration, not a nicety.

    Done in SQL so it never loads the table into memory: `period` is a 'YYYY-MM'
    string, so appending '-01' parses as a date. Rows whose period does not match
    that shape are left NULL rather than failing the migration — the model
    derives NULL for an unparseable period too, and a malformed period is a
    pre-existing data problem to surface, not to mask.
    """
    schema_editor.execute(
        """
        UPDATE accounting_calculationrun
           SET period_start = to_date(period || '-01', 'YYYY-MM-DD')
         WHERE period ~ '^[0-9]{4}-[0-9]{2}$'
        """
    )


def noop_reverse(apps, schema_editor):
    """Reversing drops the column; there is nothing to undo in the data."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_reportingperiod_reporting_period_no_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, editable=False, help_text="First day of `period`'s month. Derived; do not set directly.", null=True),
        ),
        migrations.RunPython(backfill_period_start, noop_reverse),
    ]
