# Generated by Django 5.2.15 on 2026-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_calculationrun_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationcarryover',
            name='expires_period',
            field=models.CharField(blank=True, help_text='Month at or after which the carried surplus expires, as YYYY-MM. Blank = never expires.', max_length=7, null=True),
        ),
    ]
