# Generated by Django 5.2.15 on 2026-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_literary_sentence_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercredit',
            name='expires_period',
            field=models.CharField(blank=True, help_text='Month at or after which the credit expires, as YYYY-MM. Blank = never expires.', max_length=7, null=True),
        ),
    ]
