# Generated by Django 5.2.15 on 2026-09-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_literary_sentence_help_text_credit'),
        ('wells', '0005_derive_dwr_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateraccount',
            name='delivery_well',
            field=models.ForeignKey(blank=True, help_text="This account's delivery well, if it has one. An account is delivered through a point of diversion or a well, never both.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_accounts', to='wells.well'),
        ),
        migrations.AddField(
            model_name='wateraccount',
            name='unit_kind',
            field=models.CharField(blank=True, choices=[('farm_unit', 'Farm unit'), ('place_of_use', 'Place of use'), ('water_right', 'Water right'), ('other', 'Other')], help_text='Which real thing this account stands for: a farm unit that holds fields, a place of use under a right, or a right itself.', max_length=20, null=True),
        ),
    ]
