# Generated by Django 5.2.15 on 2026-09-24 00:48

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_default_unit_kind_farm_unit'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCarryoverEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('zone', models.BigIntegerField(blank=True, db_column='zone_id', null=True, verbose_name='zone')),
                ('water_type', models.BigIntegerField(blank=True, db_column='water_type_id', null=True, verbose_name='water type')),
                ('id', models.BigIntegerField()),
                ('water_year', models.PositiveIntegerField(help_text='Year this carry-over applies TO (opening-balance year), labelled by the calendar year it ends in.')),
                ('source_water_year', models.PositiveIntegerField(blank=True, help_text='The closed water year this was rolled forward from (normally water_year - 1). Provenance for the audit trail.', null=True)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Signed carry-over (acre-feet): + surplus carried forward, − debt borrowed against this year.', max_digits=12)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Per-period geometric decay of a carried-forward SURPLUS (0 = no decay). A debt is never depreciated.', max_digits=5)),
                ('expires_period', models.CharField(blank=True, help_text='Month at or after which the carried surplus expires, as YYYY-MM. Blank = never expires.', max_length=7, null=True)),
                ('origin', models.CharField(choices=[('allocation_carryover', 'Allocation carryover'), ('basin_recharge_pool', 'Basin recharge pool (managed)'), ('incidental_recharge_pool', 'Basin recharge pool (incidental)')], default='allocation_carryover', help_text='What kind of row this is: a year-end allocation carryover, or a GSA basin recharge pool (managed / incidental).', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationPlanEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('zone', models.BigIntegerField(blank=True, db_column='zone_id', null=True, verbose_name='zone')),
                ('water_type', models.BigIntegerField(blank=True, db_column='water_type_id', null=True, verbose_name='water type')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('allocation_acre_feet', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Allocation (AF)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationPlanEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('water_type', models.BigIntegerField(blank=True, db_column='water_type_id', null=True, verbose_name='water type')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationRunEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('id', models.BigIntegerField()),
                ('period', models.CharField(help_text='Month, as YYYY-MM.', max_length=7)),
                ('period_start', models.DateField(blank=True, editable=False, help_text="First day of `period`'s month. Derived; do not set directly.", null=True)),
                ('gross_et_af', models.DecimalField(decimal_places=4, help_text="Chain's starting gross ET magnitude (positive AF).", max_digits=12)),
                ('effective_precip_af', models.DecimalField(blank=True, decimal_places=4, help_text='Effective precipitation subtracted (AF); null if no precip step ran.', max_digits=12, null=True)),
                ('surface_water_af', models.DecimalField(blank=True, decimal_places=4, help_text='Surface water subtracted (AF); null if no surface-water step ran.', max_digits=12, null=True)),
                ('net_consumptive_use_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Net consumptive use = gross ET − effective precip (positive AF) — an ET-based estimate used where meters are absent. This is distinct from the calculation-chain residual, which goes a step further and also subtracts surface water; the two 'net consumptive use' senses are not the same number. A source-agnostic quantity, recorded for every parcel with ET regardless of supply source or whether a well exists.", max_digits=12)),
                ('residual_disposition', models.CharField(choices=[('groundwater', 'Groundwater extraction'), ('unmet_demand', 'Unmet demand / unallocated'), ('metered', 'Metered extraction (authoritative)')], default='groundwater', help_text='How the ET − precip − surface residual was resolved: written as a calculated groundwater extraction (the parcel has a well), recorded as unmet demand (no well — under-irrigation or a surface-allocation error), or marked metered (the parcel carries an authoritative meter reading that owns its groundwater — the run is an ET reference value, no calculated row).', max_length=20)),
                ('unmet_demand_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Positive shortfall (ET − precip − surface) on a parcel with no well: under-irrigation or a surface-allocation error. Recorded explicitly, NEVER written as a calculated groundwater row.', max_digits=12)),
                ('banked_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Surplus deposited as a WaterCredit this period (AF).', max_digits=12)),
                ('drawn_af', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Credit drawn down to reduce the bill this period (AF).', max_digits=12)),
                ('final_af', models.DecimalField(decimal_places=4, help_text='Final billable magnitude (POSITIVE; equals -ledger.amount_acre_feet).', max_digits=12)),
                ('breakdown', models.JSONField(default=list, help_text='The evaluate_chain per-step list, stored verbatim.')),
                ('methodology_plan_id', models.PositiveIntegerField(blank=True, help_text='Snapshot of the CalculationPlan id in force at run time.', null=True)),
                ('methodology_plan_name', models.CharField(blank=True, default='', help_text='Snapshot of the plan name in force at run time.', max_length=200)),
                ('config_hash', models.CharField(blank=True, default='', help_text='sha256[:12] of the ordered enabled steps + config — the methodology fingerprint behind this number.', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationStepEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('plan', models.BigIntegerField(blank=True, db_column='plan_id', null=True, verbose_name='plan')),
                ('id', models.BigIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('et_gross', 'Gross ET'), ('subtract_effective_precip', 'Subtract effective precipitation'), ('subtract_surface_water', 'Subtract surface water delivered'), ('facility_only_zero', 'Zero out facility-only parcels'), ('clamp_floor', 'Clamp at floor')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('label', models.CharField(help_text='Human-readable name for the audit trail.', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriodEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('finalized_by', models.BigIntegerField(blank=True, db_column='finalized_by_id', null=True, verbose_name='finalized by')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterAccountEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('delivery_well', models.BigIntegerField(blank=True, db_column='delivery_well_id', null=True, verbose_name='delivery well')),
                ('id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('unit_kind', models.CharField(blank=True, choices=[('farm_unit', 'Farm unit'), ('place_of_use', 'Place of use'), ('water_right', 'Water right'), ('other', 'Other')], help_text='Which real thing this account stands for: a farm unit that holds fields, a place of use under a right, or a right itself.', max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterAccountParcelEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('water_account', models.BigIntegerField(blank=True, db_column='water_account_id', null=True, verbose_name='water account')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('reporting_period', models.BigIntegerField(blank=True, db_column='reporting_period_id', null=True, verbose_name='reporting period')),
                ('id', models.BigIntegerField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('removed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterCreditDrawEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('credit', models.BigIntegerField(blank=True, db_column='credit_id', null=True, verbose_name='credit')),
                ('id', models.BigIntegerField()),
                ('draw_period', models.CharField(help_text='Month the draw was applied, as YYYY-MM.', max_length=7)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Depreciated value drawn in this period (acre-feet, positive).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterCreditEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('parcel', models.BigIntegerField(blank=True, db_column='parcel_id', null=True, verbose_name='parcel')),
                ('id', models.BigIntegerField()),
                ('origin_period', models.CharField(help_text='Month the surplus was banked, as YYYY-MM.', max_length=7)),
                ('amount_af', models.DecimalField(decimal_places=4, help_text='Surplus banked (acre-feet, positive). The principal — never mutated.', max_digits=12)),
                ('origin', models.CharField(choices=[('precip_surplus', 'Precip surplus'), ('allocation_carryover', 'Allocation carryover')], default='precip_surplus', max_length=24)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Per-period geometric decay (0 = no decay; >=1 = gone after one period).', max_digits=5)),
                ('expires_period', models.CharField(blank=True, help_text='Month at or after which the credit expires, as YYYY-MM. Blank = never expires.', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationcarryover',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_allocationcarryoverevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_water_year", "water_type_id", "water_year", "zone_id") VALUES (NEW."amount_af", NEW."created_at", NEW."depreciation_rate", NEW."expires_period", NEW."id", NEW."origin", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_water_year", NEW."water_type_id", NEW."water_year", NEW."zone_id"); RETURN NULL;', hash='a4dbf9e6045fd77f7cba82ece2f4bc167aa2226b', operation='INSERT', pgid='pgtrigger_insert_insert_5df63', table='accounting_allocationcarryover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationcarryover',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_allocationcarryoverevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_water_year", "water_type_id", "water_year", "zone_id") VALUES (OLD."amount_af", OLD."created_at", OLD."depreciation_rate", OLD."expires_period", OLD."id", OLD."origin", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."source_water_year", OLD."water_type_id", OLD."water_year", OLD."zone_id"); RETURN NULL;', hash='bed230a8fa914f9f781a136361c9359538e696c3', operation='UPDATE', pgid='pgtrigger_before_update_update_7670c', table='accounting_allocationcarryover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationcarryover',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_allocationcarryoverevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_water_year", "water_type_id", "water_year", "zone_id") VALUES (NEW."amount_af", NEW."created_at", NEW."depreciation_rate", NEW."expires_period", NEW."id", NEW."origin", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_water_year", NEW."water_type_id", NEW."water_year", NEW."zone_id"); RETURN NULL;', hash='7f50c4a5341901e2d5cda6deeb3679557af26178', operation='UPDATE', pgid='pgtrigger_update_update_ae590', table='accounting_allocationcarryover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationcarryover',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_allocationcarryoverevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_water_year", "water_type_id", "water_year", "zone_id") VALUES (OLD."amount_af", OLD."created_at", OLD."depreciation_rate", OLD."expires_period", OLD."id", OLD."origin", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."source_water_year", OLD."water_type_id", OLD."water_year", OLD."zone_id"); RETURN NULL;', hash='45ef3a900f76a20ab68394a81c7b3ea80e2fb285', operation='DELETE', pgid='pgtrigger_delete_delete_894eb', table='accounting_allocationcarryover', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationplan',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_allocationplanevent" ("allocation_acre_feet", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "water_type_id", "zone_id") VALUES (NEW."allocation_acre_feet", NEW."created_at", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reporting_period_id", NEW."water_type_id", NEW."zone_id"); RETURN NULL;', hash='6bef41139e8c95a323ddcdb228408ce582f4c6c4', operation='INSERT', pgid='pgtrigger_insert_insert_34c93', table='accounting_allocationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationplan',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."allocation_acre_feet" IS DISTINCT FROM (NEW."allocation_acre_feet") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."reporting_period_id" IS DISTINCT FROM (NEW."reporting_period_id") OR OLD."water_type_id" IS DISTINCT FROM (NEW."water_type_id") OR OLD."zone_id" IS DISTINCT FROM (NEW."zone_id"))', func='INSERT INTO "accounting_allocationplanevent" ("allocation_acre_feet", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "water_type_id", "zone_id") VALUES (OLD."allocation_acre_feet", OLD."created_at", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."reporting_period_id", OLD."water_type_id", OLD."zone_id"); RETURN NULL;', hash='fa753d8e905d90cdfb3bee107a9f28c48d52a6c2', operation='UPDATE', pgid='pgtrigger_before_update_update_758a2', table='accounting_allocationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationplan',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."allocation_acre_feet" IS DISTINCT FROM (NEW."allocation_acre_feet") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."reporting_period_id" IS DISTINCT FROM (NEW."reporting_period_id") OR OLD."water_type_id" IS DISTINCT FROM (NEW."water_type_id") OR OLD."zone_id" IS DISTINCT FROM (NEW."zone_id"))', func='INSERT INTO "accounting_allocationplanevent" ("allocation_acre_feet", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "water_type_id", "zone_id") VALUES (NEW."allocation_acre_feet", NEW."created_at", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reporting_period_id", NEW."water_type_id", NEW."zone_id"); RETURN NULL;', hash='5009dadb97e9217bedc92a5657bb8ab29149156f', operation='UPDATE', pgid='pgtrigger_update_update_e7710', table='accounting_allocationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='allocationplan',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_allocationplanevent" ("allocation_acre_feet", "created_at", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reporting_period_id", "water_type_id", "zone_id") VALUES (OLD."allocation_acre_feet", OLD."created_at", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."reporting_period_id", OLD."water_type_id", OLD."zone_id"); RETURN NULL;', hash='cccb790fde791ab46ef91fb57e81b456d5afdbba', operation='DELETE', pgid='pgtrigger_delete_delete_100e1', table='accounting_allocationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationplan',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationplanevent" ("created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_type_id") VALUES (NEW."created_at", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."water_type_id"); RETURN NULL;', hash='0f249813b14e8824c4df01df95bf2208143dd1f1', operation='INSERT', pgid='pgtrigger_insert_insert_0df64', table='accounting_calculationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationplan',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationplanevent" ("created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_type_id") VALUES (OLD."created_at", OLD."id", OLD."is_active", OLD."name", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."water_type_id"); RETURN NULL;', hash='2145d31395e737c0f615ad88b97be0423c8983af', operation='UPDATE', pgid='pgtrigger_before_update_update_55874', table='accounting_calculationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationplan',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationplanevent" ("created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_type_id") VALUES (NEW."created_at", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."water_type_id"); RETURN NULL;', hash='5d72eb4139286b3973049db7b9d7a509464962f1', operation='UPDATE', pgid='pgtrigger_update_update_ec868', table='accounting_calculationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationplan',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationplanevent" ("created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "water_type_id") VALUES (OLD."created_at", OLD."id", OLD."is_active", OLD."name", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."water_type_id"); RETURN NULL;', hash='240e7d1401db666cca02da74d47d8004f48ac486', operation='DELETE', pgid='pgtrigger_delete_delete_0b79a', table='accounting_calculationplan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."residual_disposition", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='7158d406371337f87030667ea26fe1744092aac2', operation='INSERT', pgid='pgtrigger_insert_insert_a01e3', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."residual_disposition", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='a47836660d0f1d02d99682d91bdc607457228e7c', operation='UPDATE', pgid='pgtrigger_before_update_update_45312', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."residual_disposition", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='63750952a1548efbf5e9c7f1892d4a713ce82f9d', operation='UPDATE', pgid='pgtrigger_update_update_6d8b5', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."residual_disposition", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='d0a45dcaddfb5c517f6a2f9f934d1d97822ef52b', operation='DELETE', pgid='pgtrigger_delete_delete_80d48', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationstep',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationstepevent" ("config", "enabled", "id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "step_type") VALUES (NEW."config", NEW."enabled", NEW."id", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plan_id", NEW."step_type"); RETURN NULL;', hash='7496ffc61e3851967da2d0a523e42704baf9af34', operation='INSERT', pgid='pgtrigger_insert_insert_718ea', table='accounting_calculationstep', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationstep',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationstepevent" ("config", "enabled", "id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "step_type") VALUES (OLD."config", OLD."enabled", OLD."id", OLD."label", OLD."order", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."plan_id", OLD."step_type"); RETURN NULL;', hash='5361dd2ccecaec780f604a8509d5336629b5fa65', operation='UPDATE', pgid='pgtrigger_before_update_update_550d4', table='accounting_calculationstep', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationstep',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationstepevent" ("config", "enabled", "id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "step_type") VALUES (NEW."config", NEW."enabled", NEW."id", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plan_id", NEW."step_type"); RETURN NULL;', hash='71308d3a4991bf641296f0cd99caaf2f6498aefb', operation='UPDATE', pgid='pgtrigger_update_update_74d53', table='accounting_calculationstep', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationstep',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationstepevent" ("config", "enabled", "id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "step_type") VALUES (OLD."config", OLD."enabled", OLD."id", OLD."label", OLD."order", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."plan_id", OLD."step_type"); RETURN NULL;', hash='554fddbc0153098e11f075752e3dadbe92dd9217', operation='DELETE', pgid='pgtrigger_delete_delete_95685', table='accounting_calculationstep', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportingperiod',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_reportingperiodevent" ("created_at", "end_date", "finalized_at", "finalized_by_id", "id", "is_finalized", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_date") VALUES (NEW."created_at", NEW."end_date", NEW."finalized_at", NEW."finalized_by_id", NEW."id", NEW."is_finalized", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_date"); RETURN NULL;', hash='9cf073aae8af0d32fca656e7c33a8a2f7c168827', operation='INSERT', pgid='pgtrigger_insert_insert_3c259', table='accounting_reportingperiod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportingperiod',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."end_date" IS DISTINCT FROM (NEW."end_date") OR OLD."finalized_at" IS DISTINCT FROM (NEW."finalized_at") OR OLD."finalized_by_id" IS DISTINCT FROM (NEW."finalized_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_finalized" IS DISTINCT FROM (NEW."is_finalized") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."start_date" IS DISTINCT FROM (NEW."start_date"))', func='INSERT INTO "accounting_reportingperiodevent" ("created_at", "end_date", "finalized_at", "finalized_by_id", "id", "is_finalized", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_date") VALUES (OLD."created_at", OLD."end_date", OLD."finalized_at", OLD."finalized_by_id", OLD."id", OLD."is_finalized", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."start_date"); RETURN NULL;', hash='d7d551dd94616ee6db88d6e133a322f328d6fd3c', operation='UPDATE', pgid='pgtrigger_before_update_update_db4c2', table='accounting_reportingperiod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportingperiod',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."end_date" IS DISTINCT FROM (NEW."end_date") OR OLD."finalized_at" IS DISTINCT FROM (NEW."finalized_at") OR OLD."finalized_by_id" IS DISTINCT FROM (NEW."finalized_by_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_finalized" IS DISTINCT FROM (NEW."is_finalized") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."start_date" IS DISTINCT FROM (NEW."start_date"))', func='INSERT INTO "accounting_reportingperiodevent" ("created_at", "end_date", "finalized_at", "finalized_by_id", "id", "is_finalized", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_date") VALUES (NEW."created_at", NEW."end_date", NEW."finalized_at", NEW."finalized_by_id", NEW."id", NEW."is_finalized", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_date"); RETURN NULL;', hash='1567741cf5b5b2c655762a26ce9dfe8df0dcdafb', operation='UPDATE', pgid='pgtrigger_update_update_754b9', table='accounting_reportingperiod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='reportingperiod',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_reportingperiodevent" ("created_at", "end_date", "finalized_at", "finalized_by_id", "id", "is_finalized", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_date") VALUES (OLD."created_at", OLD."end_date", OLD."finalized_at", OLD."finalized_by_id", OLD."id", OLD."is_finalized", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."start_date"); RETURN NULL;', hash='707f76f116934fa54d72dc13cd736245fd03c3b5', operation='DELETE', pgid='pgtrigger_delete_delete_03041', table='accounting_reportingperiod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccount',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_wateraccountevent" ("account_number", "contact_email", "contact_name", "created_at", "delivery_well_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unit_kind") VALUES (NEW."account_number", NEW."contact_email", NEW."contact_name", NEW."created_at", NEW."delivery_well_id", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."unit_kind"); RETURN NULL;', hash='d6ad96c6d604e5e9e5f54323e8abec463bd4b549', operation='INSERT', pgid='pgtrigger_insert_insert_036a3', table='accounting_wateraccount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccount',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."account_number" IS DISTINCT FROM (NEW."account_number") OR OLD."contact_email" IS DISTINCT FROM (NEW."contact_email") OR OLD."contact_name" IS DISTINCT FROM (NEW."contact_name") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."delivery_well_id" IS DISTINCT FROM (NEW."delivery_well_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."unit_kind" IS DISTINCT FROM (NEW."unit_kind"))', func='INSERT INTO "accounting_wateraccountevent" ("account_number", "contact_email", "contact_name", "created_at", "delivery_well_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unit_kind") VALUES (OLD."account_number", OLD."contact_email", OLD."contact_name", OLD."created_at", OLD."delivery_well_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."status", OLD."unit_kind"); RETURN NULL;', hash='dbf90659c6a02e38e7b2f63bf65e0676f3979e2a', operation='UPDATE', pgid='pgtrigger_before_update_update_9ad5e', table='accounting_wateraccount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccount',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."account_number" IS DISTINCT FROM (NEW."account_number") OR OLD."contact_email" IS DISTINCT FROM (NEW."contact_email") OR OLD."contact_name" IS DISTINCT FROM (NEW."contact_name") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."delivery_well_id" IS DISTINCT FROM (NEW."delivery_well_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."unit_kind" IS DISTINCT FROM (NEW."unit_kind"))', func='INSERT INTO "accounting_wateraccountevent" ("account_number", "contact_email", "contact_name", "created_at", "delivery_well_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unit_kind") VALUES (NEW."account_number", NEW."contact_email", NEW."contact_name", NEW."created_at", NEW."delivery_well_id", NEW."id", NEW."name", NEW."notes", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."unit_kind"); RETURN NULL;', hash='d9f12e3af110edb1e21f7603bf1dee21302f5999', operation='UPDATE', pgid='pgtrigger_update_update_d54b1', table='accounting_wateraccount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccount',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_wateraccountevent" ("account_number", "contact_email", "contact_name", "created_at", "delivery_well_id", "id", "name", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unit_kind") VALUES (OLD."account_number", OLD."contact_email", OLD."contact_name", OLD."created_at", OLD."delivery_well_id", OLD."id", OLD."name", OLD."notes", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."status", OLD."unit_kind"); RETURN NULL;', hash='a275450fd2f8fa877192a29949d93235c2878bea', operation='DELETE', pgid='pgtrigger_delete_delete_24bc9', table='accounting_wateraccount', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountparcel',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_wateraccountparcelevent" ("added_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "reporting_period_id", "water_account_id") VALUES (NEW."added_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."removed_date", NEW."reporting_period_id", NEW."water_account_id"); RETURN NULL;', hash='9b20884d3697c588d619a193f43ee7527f30aeb7', operation='INSERT', pgid='pgtrigger_insert_insert_ff8d9', table='accounting_wateraccountparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountparcel',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_wateraccountparcelevent" ("added_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "reporting_period_id", "water_account_id") VALUES (OLD."added_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."removed_date", OLD."reporting_period_id", OLD."water_account_id"); RETURN NULL;', hash='1285770eeb610b9f3002a7c85c67f7428770cd19', operation='UPDATE', pgid='pgtrigger_before_update_update_ef47a', table='accounting_wateraccountparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountparcel',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_wateraccountparcelevent" ("added_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "reporting_period_id", "water_account_id") VALUES (NEW."added_date", NEW."id", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."removed_date", NEW."reporting_period_id", NEW."water_account_id"); RETURN NULL;', hash='ddad4b7aa46870e2769289bd77e0a1dfc6ae09a6', operation='UPDATE', pgid='pgtrigger_update_update_4279e', table='accounting_wateraccountparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='wateraccountparcel',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_wateraccountparcelevent" ("added_date", "id", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed_date", "reporting_period_id", "water_account_id") VALUES (OLD."added_date", OLD."id", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."removed_date", OLD."reporting_period_id", OLD."water_account_id"); RETURN NULL;', hash='f37f6925143bbd4dd2aac8cd2bc6fa6f2ffeabb1', operation='DELETE', pgid='pgtrigger_delete_delete_4485d', table='accounting_wateraccountparcel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercredit',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_watercreditevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "origin_period", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."amount_af", NEW."created_at", NEW."depreciation_rate", NEW."expires_period", NEW."id", NEW."origin", NEW."origin_period", NEW."parcel_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='c7e88a1636bc9083de4db54bb09c15fd54713304', operation='INSERT', pgid='pgtrigger_insert_insert_d111d', table='accounting_watercredit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercredit',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_watercreditevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "origin_period", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."amount_af", OLD."created_at", OLD."depreciation_rate", OLD."expires_period", OLD."id", OLD."origin", OLD."origin_period", OLD."parcel_id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id"); RETURN NULL;', hash='5146aed49e561d79de7b8b71a2d49e86a40cfb0d', operation='UPDATE', pgid='pgtrigger_before_update_update_7a82e', table='accounting_watercredit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercredit',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_watercreditevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "origin_period", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."amount_af", NEW."created_at", NEW."depreciation_rate", NEW."expires_period", NEW."id", NEW."origin", NEW."origin_period", NEW."parcel_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='135d477883264bfaf25c7f636b80a75986a13093', operation='UPDATE', pgid='pgtrigger_update_update_e358e', table='accounting_watercredit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercredit',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_watercreditevent" ("amount_af", "created_at", "depreciation_rate", "expires_period", "id", "origin", "origin_period", "parcel_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."amount_af", OLD."created_at", OLD."depreciation_rate", OLD."expires_period", OLD."id", OLD."origin", OLD."origin_period", OLD."parcel_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='3eb78035c96dc83585fb5dad25fad3cc60658f4e', operation='DELETE', pgid='pgtrigger_delete_delete_6fc88', table='accounting_watercredit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercreditdraw',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_watercreditdrawevent" ("amount_af", "created_at", "credit_id", "draw_period", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."amount_af", NEW."created_at", NEW."credit_id", NEW."draw_period", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='3acb340b5daf7566013ede1b5518a0769f8dfc8d', operation='INSERT', pgid='pgtrigger_insert_insert_dd5e0', table='accounting_watercreditdraw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercreditdraw',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_watercreditdrawevent" ("amount_af", "created_at", "credit_id", "draw_period", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."amount_af", OLD."created_at", OLD."credit_id", OLD."draw_period", OLD."id", _pgh_attach_context(), NOW(), \'before_update\', OLD."id"); RETURN NULL;', hash='92dd7c8bfcc68fa9bc76d5efc0dc0569b9d03bab', operation='UPDATE', pgid='pgtrigger_before_update_update_198c3', table='accounting_watercreditdraw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercreditdraw',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_watercreditdrawevent" ("amount_af", "created_at", "credit_id", "draw_period", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."amount_af", NEW."created_at", NEW."credit_id", NEW."draw_period", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='89d46ed1d1a57952a7c1c27d69cbe15c2f5c3e3b', operation='UPDATE', pgid='pgtrigger_update_update_9a9b1', table='accounting_watercreditdraw', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='watercreditdraw',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_watercreditdrawevent" ("amount_af", "created_at", "credit_id", "draw_period", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."amount_af", OLD."created_at", OLD."credit_id", OLD."draw_period", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash='00d67357390c4ccf5f838976e2973c428917456d', operation='DELETE', pgid='pgtrigger_delete_delete_773e6', table='accounting_watercreditdraw', when='AFTER')),
        ),
        migrations.AddField(
            model_name='allocationcarryoverevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='allocationcarryoverevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.allocationcarryover'),
        ),
        migrations.AddField(
            model_name='allocationplanevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='allocationplanevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.allocationplan'),
        ),
        migrations.AddField(
            model_name='calculationplanevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='calculationplanevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.calculationplan'),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.calculationrun'),
        ),
        migrations.AddField(
            model_name='calculationstepevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='calculationstepevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.calculationstep'),
        ),
        migrations.AddField(
            model_name='reportingperiodevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='reportingperiodevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.reportingperiod'),
        ),
        migrations.AddField(
            model_name='wateraccountevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wateraccountevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.wateraccount'),
        ),
        migrations.AddField(
            model_name='wateraccountparcelevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='wateraccountparcelevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.wateraccountparcel'),
        ),
        migrations.AddField(
            model_name='watercreditdrawevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='watercreditdrawevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.watercreditdraw'),
        ),
        migrations.AddField(
            model_name='watercreditevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='watercreditevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='accounting.watercredit'),
        ),
    ]
