# Generated by Django 5.2.15 on 2026-09-24 15:10

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_allocationcarryover_finalized_period_lock_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='surface_delivered_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Recorded delivery for the month (AF), before the field's efficiency is applied. Null when no surface-water step ran or the run predates 148-02.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='surface_efficiency',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The field-efficiency factor applied to this run's surface delivery. Null when the apply_efficiency knob is off, nothing was delivered, or the step ran on a plan from before 148-02.", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='surface_delivered_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Recorded delivery for the month (AF), before the field's efficiency is applied. Null when no surface-water step ran or the run predates 148-02.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='surface_efficiency',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The field-efficiency factor applied to this run's surface delivery. Null when the apply_efficiency knob is off, nothing was delivered, or the step ran on a plan from before 148-02.", max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='surface_water_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Surface water subtracted (AF); null if no surface-water step ran. With the apply_efficiency knob on, this is the CONSUMED part of a canal delivery (delivered x efficiency); with the knob off, or on an old run from before 148-02, it is the delivered magnitude itself.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrunevent',
            name='surface_water_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Surface water subtracted (AF); null if no surface-water step ran. With the apply_efficiency knob on, this is the CONSUMED part of a canal delivery (delivered x efficiency); with the knob off, or on an old run from before 148-02, it is the delivered magnitude itself.', max_digits=12, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='7c5fc2209c3fe1922d0ea3155b4f9ada49832ed9', operation='INSERT', pgid='pgtrigger_insert_insert_a01e3', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='08306a7dcd3e822ddf338d887352f2fea2e51ba8', operation='UPDATE', pgid='pgtrigger_before_update_update_45312', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='7da2555b55103b98c2e996a4e7b0b82e2254b6d0', operation='UPDATE', pgid='pgtrigger_update_update_6d8b5', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='7adfde653702f4aae457ce3e8979e236d1321c6c', operation='DELETE', pgid='pgtrigger_delete_delete_80d48', table='accounting_calculationrun', when='AFTER')),
        ),
    ]
