# Generated by Django 5.2.15 on 2026-09-24 21:06

import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_calculationrun_surface_delivered'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='over_delivery_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="148-02 (Q1, an over-delivery is nobody's credit): the month's canal water the crop could use beyond its net use, read off the clamp_floor step's incidental_recharge_af. No ledger row is written for it — the amount is recorded here only, never a recharge credit and never a personal or pooled deposit. 0 on a run with no over-delivery.", max_digits=12),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='over_delivery_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="148-02 (Q1, an over-delivery is nobody's credit): the month's canal water the crop could use beyond its net use, read off the clamp_floor step's incidental_recharge_af. No ledger row is written for it — the amount is recorded here only, never a recharge credit and never a personal or pooled deposit. 0 on a run with no over-delivery.", max_digits=12),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='67d4ad18b27952ceb25db0c85fa991e8b23e0c28', operation='INSERT', pgid='pgtrigger_insert_insert_a01e3', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='7f535e617e296efebaf9ed3be3a79f12f2b178a8', operation='UPDATE', pgid='pgtrigger_before_update_update_45312', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='bd25476def26e5e28c7694ec5b9652a43082df8b', operation='UPDATE', pgid='pgtrigger_update_update_6d8b5', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='6a6762657ee8dc805f51dc0744a2aba246fcb2c5', operation='DELETE', pgid='pgtrigger_delete_delete_80d48', table='accounting_calculationrun', when='AFTER')),
        ),
    ]
