# Generated by Django 5.2.15 on 2026-09-24 21:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_calculationrun_over_delivery'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='deep_percolation_gw_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-02 Task 4 (Q2): gw_extracted_af minus final_af -- the pumped water the crop did not consume, returning to the aquifer. Neither crop use nor a credit; feeds parcel_mass_balance's own output term of the same name so an estimated field-year still closes. Null wherever gw_extracted_af is null.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='gw_extracted_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-02 Task 4 (Q2): the estimated field's pumped magnitude -- final_af divided by SiteConfig.groundwater_efficiency AT COMPUTE TIME (read once when this run was written, never re-derived from a setting that may have moved since — a finalized period's billable groundwater must not move when someone tunes the setting, ISS-177). Null on a metered run (the meter is the number) or a no-well run (unmet demand, never a phantom extraction). 0 on a zero-residual estimated month.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='deep_percolation_gw_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-02 Task 4 (Q2): gw_extracted_af minus final_af -- the pumped water the crop did not consume, returning to the aquifer. Neither crop use nor a credit; feeds parcel_mass_balance's own output term of the same name so an estimated field-year still closes. Null wherever gw_extracted_af is null.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='gw_extracted_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-02 Task 4 (Q2): the estimated field's pumped magnitude -- final_af divided by SiteConfig.groundwater_efficiency AT COMPUTE TIME (read once when this run was written, never re-derived from a setting that may have moved since — a finalized period's billable groundwater must not move when someone tunes the setting, ISS-177). Null on a metered run (the meter is the number) or a no-well run (unmet demand, never a phantom extraction). 0 on a zero-residual estimated month.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='residual_disposition',
            field=models.CharField(choices=[('groundwater', 'Groundwater consumed (estimated)'), ('unmet_demand', 'Unmet demand / unallocated'), ('metered', 'Metered extraction (authoritative)')], default='groundwater', help_text='How the ET − precip − surface residual was resolved: written as a calculated groundwater extraction (the parcel has a well), recorded as unmet demand (no well — under-irrigation or a surface-allocation error), or marked metered (the parcel carries an authoritative meter reading that owns its groundwater — the run is an ET reference value, no calculated row).', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculationrunevent',
            name='residual_disposition',
            field=models.CharField(choices=[('groundwater', 'Groundwater consumed (estimated)'), ('unmet_demand', 'Unmet demand / unallocated'), ('metered', 'Metered extraction (authoritative)')], default='groundwater', help_text='How the ET − precip − surface residual was resolved: written as a calculated groundwater extraction (the parcel has a well), recorded as unmet demand (no well — under-irrigation or a surface-allocation error), or marked metered (the parcel carries an authoritative meter reading that owns its groundwater — the run is an ET reference value, no calculated row).', max_length=20),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."deep_percolation_gw_af", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."gw_extracted_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='248715d5e90267867926c75767e466d508cace6f', operation='INSERT', pgid='pgtrigger_insert_insert_a01e3', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."deep_percolation_gw_af", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."gw_extracted_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='4f7f7b4c57c0d0d2e2df7383f7ef99af440a1ab7', operation='UPDATE', pgid='pgtrigger_before_update_update_45312', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."deep_percolation_gw_af", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."gw_extracted_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='39f63f7c3d1fd4169524209de64f51f0214f2721', operation='UPDATE', pgid='pgtrigger_update_update_6d8b5', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."deep_percolation_gw_af", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."gw_extracted_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='f68114652ff607f00a132912cb58ec5cfc42aaf9', operation='DELETE', pgid='pgtrigger_delete_delete_80d48', table='accounting_calculationrun', when='AFTER')),
        ),
    ]
