# Generated by Django 5.2.15 on 2026-09-28 12:41

import pgtrigger.compiler
import pgtrigger.migrations
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_remove_calculationrun_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='before_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='calculationrun',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='over_delivery_credit_pooled',
            field=models.BooleanField(default=False, help_text="148-04: True when over_delivery_credited_af went to the field's zone's shared basin pool rather than the field's own ledger — a no-well field has no well to pump a personal credit back with, so its credited share joins the zone's shared account instead (ISS-053's routing rule, applied again under 'credited'). False (the default) on every run that credited nothing, or credited the field itself."),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='over_delivery_credited_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-04: the amount this run actually credited — to the field's own ledger (over_delivery_credit_pooled False) or to its zone's shared pool (over_delivery_credit_pooled True). Null unless 'credited' treatment credited something this run: a month with no over-delivery credits nothing, and a no-well field with no management-area zone has nowhere to credit it either.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='over_delivery_leave_behind',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="148-04: the SiteConfig.over_delivery_leave_behind share in force when this run was written. Stamped whenever over_delivery_treatment is 'credited' on this run, whether or not there was an over-delivery to apply it to this month; null under 'not_credited' or 'named_line'.", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='over_delivery_treatment',
            field=models.CharField(choices=[('not_credited', 'Not credited'), ('credited', 'Credited to the landowner, less a share left in the basin'), ('named_line', 'Its own line, not a credit')], default='not_credited', help_text="148-04: the SiteConfig.over_delivery_treatment setting in force when THIS run was written — read once at compute time, never re-read, so a later change to the setting moves no figure on this run until it is re-run (ISS-177, the same rule that protects gw_extracted_af). Default 'not_credited' so a run written before this setting existed reads as what it always was.", max_length=20),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='over_delivery_credit_pooled',
            field=models.BooleanField(default=False, help_text="148-04: True when over_delivery_credited_af went to the field's zone's shared basin pool rather than the field's own ledger — a no-well field has no well to pump a personal credit back with, so its credited share joins the zone's shared account instead (ISS-053's routing rule, applied again under 'credited'). False (the default) on every run that credited nothing, or credited the field itself."),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='over_delivery_credited_af',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="148-04: the amount this run actually credited — to the field's own ledger (over_delivery_credit_pooled False) or to its zone's shared pool (over_delivery_credit_pooled True). Null unless 'credited' treatment credited something this run: a month with no over-delivery credits nothing, and a no-well field with no management-area zone has nowhere to credit it either.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='over_delivery_leave_behind',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="148-04: the SiteConfig.over_delivery_leave_behind share in force when this run was written. Stamped whenever over_delivery_treatment is 'credited' on this run, whether or not there was an over-delivery to apply it to this month; null under 'not_credited' or 'named_line'.", max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='calculationrunevent',
            name='over_delivery_treatment',
            field=models.CharField(choices=[('not_credited', 'Not credited'), ('credited', 'Credited to the landowner, less a share left in the basin'), ('named_line', 'Its own line, not a credit')], default='not_credited', help_text="148-04: the SiteConfig.over_delivery_treatment setting in force when THIS run was written — read once at compute time, never re-read, so a later change to the setting moves no figure on this run until it is re-run (ISS-177, the same rule that protects gw_extracted_af). Default 'not_credited' so a run written before this setting existed reads as what it always was.", max_length=20),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='over_delivery_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="148-02 (Q1, an over-delivery is nobody's credit under the default): the month's canal water the crop could use beyond its net use, read off the clamp_floor step's incidental_recharge_af. Under the default (not_credited) and under named_line, no ledger row is written for it and it is never a personal or pooled deposit — the amount is recorded here only. 148-04: under 'credited', see over_delivery_treatment / over_delivery_credited_af / over_delivery_credit_pooled for what this run actually did with it. 0 on a run with no over-delivery.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='calculationrunevent',
            name='over_delivery_af',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="148-02 (Q1, an over-delivery is nobody's credit under the default): the month's canal water the crop could use beyond its net use, read off the clamp_floor step's incidental_recharge_af. Under the default (not_credited) and under named_line, no ledger row is written for it and it is never a personal or pooled deposit — the amount is recorded here only. 148-04: under 'credited', see over_delivery_treatment / over_delivery_credited_af / over_delivery_credit_pooled for what this run actually did with it. 0 on a run with no over-delivery.", max_digits=12),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "over_delivery_credit_pooled", "over_delivery_credited_af", "over_delivery_leave_behind", "over_delivery_treatment", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."deep_percolation_gw_af", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."gw_extracted_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."over_delivery_credit_pooled", NEW."over_delivery_credited_af", NEW."over_delivery_leave_behind", NEW."over_delivery_treatment", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='82bf3dada0d52f43755fb75662a43ec65f6d3f5c', operation='INSERT', pgid='pgtrigger_insert_insert_a01e3', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='before_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "over_delivery_credit_pooled", "over_delivery_credited_af", "over_delivery_leave_behind", "over_delivery_treatment", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."deep_percolation_gw_af", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."gw_extracted_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."over_delivery_credit_pooled", OLD."over_delivery_credited_af", OLD."over_delivery_leave_behind", OLD."over_delivery_treatment", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'before_update\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='b9a722b6cceb4723535e9e8d396f61bf3b890b52', operation='UPDATE', pgid='pgtrigger_before_update_update_45312', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "over_delivery_credit_pooled", "over_delivery_credited_af", "over_delivery_leave_behind", "over_delivery_treatment", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (NEW."banked_af", NEW."breakdown", NEW."config_hash", NEW."created_at", NEW."deep_percolation_gw_af", NEW."drawn_af", NEW."effective_precip_af", NEW."final_af", NEW."gross_et_af", NEW."gw_extracted_af", NEW."id", NEW."methodology_plan_id", NEW."methodology_plan_name", NEW."net_consumptive_use_af", NEW."over_delivery_af", NEW."over_delivery_credit_pooled", NEW."over_delivery_credited_af", NEW."over_delivery_leave_behind", NEW."over_delivery_treatment", NEW."parcel_id", NEW."period", NEW."period_start", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."residual_disposition", NEW."surface_delivered_af", NEW."surface_efficiency", NEW."surface_water_af", NEW."unmet_demand_af"); RETURN NULL;', hash='363705dcfd113f2f4aaa42e1877a37beae54c678', operation='UPDATE', pgid='pgtrigger_update_update_6d8b5', table='accounting_calculationrun', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='calculationrun',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "accounting_calculationrunevent" ("banked_af", "breakdown", "config_hash", "created_at", "deep_percolation_gw_af", "drawn_af", "effective_precip_af", "final_af", "gross_et_af", "gw_extracted_af", "id", "methodology_plan_id", "methodology_plan_name", "net_consumptive_use_af", "over_delivery_af", "over_delivery_credit_pooled", "over_delivery_credited_af", "over_delivery_leave_behind", "over_delivery_treatment", "parcel_id", "period", "period_start", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "residual_disposition", "surface_delivered_af", "surface_efficiency", "surface_water_af", "unmet_demand_af") VALUES (OLD."banked_af", OLD."breakdown", OLD."config_hash", OLD."created_at", OLD."deep_percolation_gw_af", OLD."drawn_af", OLD."effective_precip_af", OLD."final_af", OLD."gross_et_af", OLD."gw_extracted_af", OLD."id", OLD."methodology_plan_id", OLD."methodology_plan_name", OLD."net_consumptive_use_af", OLD."over_delivery_af", OLD."over_delivery_credit_pooled", OLD."over_delivery_credited_af", OLD."over_delivery_leave_behind", OLD."over_delivery_treatment", OLD."parcel_id", OLD."period", OLD."period_start", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."residual_disposition", OLD."surface_delivered_af", OLD."surface_efficiency", OLD."surface_water_af", OLD."unmet_demand_af"); RETURN NULL;', hash='4ab93715a73fa2b8153ae781c7397fd98b694278', operation='DELETE', pgid='pgtrigger_delete_delete_80d48', table='accounting_calculationrun', when='AFTER')),
        ),
    ]
