# Generated by Django 5.2.15 on 2026-10-06 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_calculationrun_over_delivery_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('screen', 'A person pressed the button'), ('schedule', 'The nightly schedule'), ('diversion_saved', 'A diversion record was saved'), ('ledger_saved', 'A delivery record was saved'), ('command', 'The command line')], default='command', max_length=20)),
                ('months', models.JSONField(blank=True, default=list, help_text='The months to calculate, oldest first, each as "YYYY-MM". Rewritten to the months actually calculated when the request runs.')),
                ('months_done', models.PositiveIntegerField(default=0, help_text='How many of the months have been calculated and saved so far.')),
                ('status', models.CharField(choices=[('queued', 'Waiting to start'), ('running', 'Running'), ('succeeded', 'Finished'), ('finished_with_notes', 'Finished, with notes'), ('failed', 'Stopped')], default='queued', max_length=24)),
                ('outcome', models.TextField(blank=True, help_text='One or two plain sentences for a person: what happened.')),
                ('notes', models.JSONField(blank=True, default=list, help_text="Plain sentences for a person reading the outcome, one per thing worth knowing: months left out until their data arrives, own delivery records that add up to more than the headgate, canal water left over.")),
                ('error_detail', models.TextField(blank=True, help_text='Exception, month and the end of the traceback. For an administrator only; never shown to a viewer.')),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_requests', to='accounting.reportingperiod')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='accounting__status_78250e_idx')],
            },
        ),
    ]
