# Generated by Django 5.2.15 on 2026-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_calculationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationcarryover',
            name='origin',
            field=models.CharField(choices=[('allocation_carryover', 'Allocation carryover'), ('basin_recharge_pool', 'Basin recharge pool (managed)'), ('incidental_recharge_pool', 'Basin recharge pool (incidental)'), ('conveyance_seepage_pool', 'District seepage pool (canal)')], default='allocation_carryover', help_text='What kind of row this is: a year-end allocation carryover, or a GSA basin recharge pool (managed / incidental) or a canal seepage pool.', max_length=24),
        ),
        migrations.AlterField(
            model_name='allocationcarryoverevent',
            name='origin',
            field=models.CharField(choices=[('allocation_carryover', 'Allocation carryover'), ('basin_recharge_pool', 'Basin recharge pool (managed)'), ('incidental_recharge_pool', 'Basin recharge pool (incidental)'), ('conveyance_seepage_pool', 'District seepage pool (canal)')], default='allocation_carryover', help_text='What kind of row this is: a year-end allocation carryover, or a GSA basin recharge pool (managed / incidental) or a canal seepage pool.', max_length=24),
        ),
    ]
