# Generated by Django 5.2.14 on 2026-05-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable machine key, e.g. groundwater_level_depth, discharge.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human label, e.g. "Depth to Groundwater".', max_length=200)),
                ('usgs_pcode', models.CharField(blank=True, help_text='5-digit USGS parameter code, e.g. 72019. Blank where the concept has no USGS code (CDEC reservoir sensors, OpenET ET).', max_length=10)),
                ('wqx_characteristic_name', models.CharField(blank=True, help_text='EPA WQX CharacteristicName.', max_length=255)),
                ('ucum_unit', models.CharField(blank=True, help_text='UCUM unit code (unitsofmeasure.org), e.g. [cft_i]/s, [ft_i], Cel.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('definition_url', models.URLField(blank=True, help_text='Optional canonical definition link.')),
            ],
            options={
                'verbose_name': 'Observed Property',
                'verbose_name_plural': 'Observed Properties',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SourceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(help_text='Adapter code: "usgs", "cdec", "dwr_wdl", etc.', max_length=50)),
                ('parameter_code', models.CharField(help_text="The source's native code (the PARAMETER_MAP dict key).", max_length=50)),
                ('native_name', models.CharField(blank=True, help_text="The source's own label (from PARAMETER_MAP name).", max_length=200)),
                ('native_unit', models.CharField(blank=True, help_text="The source's own unit string (from PARAMETER_MAP unit).", max_length=50)),
                ('observed_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_parameters', to='standards.observedproperty')),
            ],
            options={
                'verbose_name': 'Source Parameter',
                'verbose_name_plural': 'Source Parameters',
                'ordering': ['source_code', 'parameter_code'],
                'unique_together': {('source_code', 'parameter_code')},
            },
        ),
    ]
