# Generated by Django 5.2.14 on 2026-05-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0004_rename_datasync_op_parcel__a6c8d7_idx_datasync_op_parcel__8c9892_idx_and_more'),
        ('measurements', '0004_meterreading_quality_sensormeasurement_quality'),
        ('standards', '0001_initial'),
        ('wells', '0003_monitoringwell_vertical_datum_well_usgs_site_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitored_station', models.ForeignKey(blank=True, help_text='The SensorThings Thing for an external/surface telemetry series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datastreams', to='datasync.monitoredstation')),
                ('observed_property', models.ForeignKey(help_text='What is measured (the canonical concept).', on_delete=django.db.models.deletion.PROTECT, related_name='datastreams', to='standards.observedproperty')),
                ('sensor', models.ForeignKey(blank=True, help_text='The SensorThings Sensor — the instrument/procedure.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datastreams', to='measurements.sensor')),
                ('well', models.ForeignKey(blank=True, help_text='The SensorThings Thing for a groundwater series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datastreams', to='wells.well')),
            ],
            options={
                'verbose_name': 'Datastream',
                'verbose_name_plural': 'Datastreams',
                'ordering': ['name'],
                'unique_together': {('observed_property', 'sensor', 'well', 'monitored_station')},
            },
        ),
    ]
